import {activeViewLabel,regionKeyLabel} from '/shared/ai/ai-workspace-contract.v3991_0.js?v=3991_0';
const BAND_LABELS=Object.freeze({upper:'稍高参考',near:'接近参考',steady:'更稳参考'});
const STAGE_LABELS=Object.freeze({start:'刚开始',feasible_set:'建立可行范围',expand_directions:'横向看方向',narrow_region:'逐步缩地区',school_focus:'开始看学校',compare:'做比较',verify:'核验事实',plan_review:'检查家庭方案'});
const PRIORITY_LABELS=Object.freeze({employment:'就业',city:'城市机会',school:'学校平台',major:'专业匹配',cost:'成本',stability:'稳定性',income:'收入',study_duration:'培养周期'});
const GOAL_LABELS=Object.freeze({employment_stability:'就业稳定',income_upside:'收入上限',city_opportunity:'城市机会',school_platform:'学校平台',major_fit:'专业匹配',cost_control:'成本控制',public_service:'考公/体制路径',undecided:'尚未明确'});
export function node(tag,className='',text=''){const el=document.createElement(tag);if(className)el.className=className;if(text!==''&&text!=null)el.textContent=String(text);return el;}
export function safeHref(value){const text=String(value||'').trim();if(text.startsWith('/'))return text;try{const url=new URL(text);return url.protocol==='https:'?url.toString():'';}catch{return '';}}
function numberText(value){const n=Number(value);return Number.isFinite(n)?n.toLocaleString('zh-CN'):'';}
function bottomLineText(value){return({all:'全部项目',public_first:'公办优先',public_regular_only:'公办普通',public_include_sino:'公办含中外合作'})[value]||'全部项目';}
function regionText(values=[]){const list=Array.isArray(values)?values:[];if(!list.length||list.includes('all'))return'全国';return list.map(regionKeyLabel).join('、');}
function bandLabel(value){return BAND_LABELS[String(value||'')]||'历史参考';}
function scoreGapText(recordScore,candidateScore){const record=Number(recordScore),candidate=Number(candidateScore);if(!Number.isFinite(record)||!Number.isFinite(candidate))return'';const gap=record-candidate;if(gap===0)return'与当前同分';return gap>0?`比当前高${Math.abs(gap)}分`:`比当前低${Math.abs(gap)}分`;}
function rankGapText(recordRank,candidateRank){const record=Number(recordRank),candidate=Number(candidateRank);if(!Number.isFinite(record)||!Number.isFinite(candidate))return'';const gap=record-candidate;if(gap===0)return'位次接近当前';return gap<0?`历史位次比当前靠前${numberText(Math.abs(gap))}位`:`历史位次比当前靠后${numberText(Math.abs(gap))}位`;}
function promptButton(label,prompt,onPrompt,className='question-button',reason=''){const button=node('button',className);button.type='button';button.dataset.prompt=prompt;button.append(node('strong','',label));if(reason)button.append(node('span','',reason));button.addEventListener('click',()=>onPrompt(prompt));return button;}
function countStrip(counts={}){const strip=node('div','count-strip');for(const [key,label] of [['upper','稍高'],['near','接近'],['steady','更稳'],['total','共']]){const pill=node('span','count-pill');pill.append(node('b','',numberText(counts[key]||0)),document.createTextNode(label));strip.append(pill);}return strip;}
function candidateCard(record={},context={}){const item=node('article','candidate-item'),head=node('div','candidate-head');head.append(node('div','candidate-school',record.school||record.schoolName||'学校待核'),node('div','candidate-major',record.major||record.majorName||'专业待核'),node('div','candidate-location',record.displayLocation||record.city||record.province||''));item.append(head);const reference=node('div','candidate-reference'),recordScore=Number(record.score2026??record.score),recordRank=Number(record.rank2026??record.rank),year=Number(context.dataYear||2026),main=[];if(Number.isFinite(recordScore))main.push(`${recordScore}分`);if(Number.isFinite(recordRank))main.push(`${numberText(recordRank)}位`);reference.append(node('span','reference-main',`${year}参考${main.length?` · ${main.join(' · ')}`:''}`));const gap=scoreGapText(recordScore,context.candidateScore);if(gap)reference.append(node('span','reference-gap',gap));reference.append(node('span','band-badge',bandLabel(record.bandKey||record.band)));item.append(reference);const rankGap=rankGapText(recordRank,context.candidateRank);if(rankGap)item.append(node('div','candidate-rank-context',rankGap));return item;}
function candidateList(block){const list=node('div','candidate-list');for(const record of block.records||[])list.append(candidateCard(record,block));return list;}
function renderComparison(block,box){const grid=node('div','comparison-grid');for(const item of block.items||[]){const card=node('article','comparison-card');card.append(node('h4','',item.label||'比较对象'),countStrip(item.counts||item.result?.counts||{}));const schoolCount=Number(item.reachableSchoolCount||0),majorCount=Number(item.reachableMajorCount||0);if(schoolCount||majorCount)card.append(node('p','',`当前可见：${schoolCount}所学校 · ${majorCount}个专业样本`));grid.append(card);}box.append(grid);if(block.pendingEvidenceDimensions?.length)box.append(node('p','muted',`没有可靠统一证据的维度不强行比较：${block.pendingEvidenceDimensions.join('、')}`));}
function renderDecisionDetails(block){const details=node('details','details-card');details.append(node('summary','',block.title||'需要时再看依据'));const list=node('div','detail-list');for(const item of block.pendingChecks||[])list.append(node('div','detail-item',item.text||String(item)));for(const item of block.evidence||[]){const row=node('div','detail-item'),href=safeHref(item.sourceUrl);if(href){const a=node('a','',item.sourceName||'官方来源');a.href=href;a.target='_blank';a.rel='noopener noreferrer';row.append(a);}else row.append(node('span','',item.sourceName||'官方来源'));if(item.scope)row.append(node('div','muted',item.scope));list.append(row);}details.append(list);return details;}
function renderBlock(block,onPrompt){const type=block?.type||'plain';if(type==='assistant_message')return null;const classes=['result-card'];if(type==='fact_summary')classes.push('fact');if(type==='decision_guidance')classes.push('guidance');if(type==='clarification')classes.push('warning');if(type==='change_explanation')classes.push('change');const box=node('section',classes.join(' '));if(block.title)box.append(node('h3','',block.title));if(block.text)box.append(node('p','',block.text));if(type==='candidate_routes'){if(block.interpretation)box.append(node('p','candidate-meaning',block.interpretation));box.append(countStrip(block.counts||{}));if(block.records?.length)box.append(candidateList(block));}if(type==='comparison')renderComparison(block,box);if(type==='selection_review'&&block.review?.findings?.length){const list=node('div','detail-list');for(const item of block.review.findings.slice(0,8))list.append(node('div','detail-item',item.text||String(item)));box.append(list);}if(type==='next_questions'){const list=node('div','question-list');for(const item of block.items||[])list.append(promptButton(item.label||item.prompt,item.prompt,onPrompt,'question-button',item.reason||''));box.append(list);}if(type==='decision_details')return renderDecisionDetails(block);return box;}
function renderTurn(turn,onPrompt){const wrap=node('article','turn'),user=node('div','user-line');user.append(node('div','user-bubble',turn.userText||''));wrap.append(user);const assistant=node('div','assistant-turn'),lead=node('div','assistant-lead'),first=(turn.blocks||[]).find(block=>block.type==='assistant_message');lead.append(node('p','',first?.text||turn.changeSummary||turn.assistantSummary||'我按你这句话继续处理。'));const stage=STAGE_LABELS[turn.stage]||'';if(stage)lead.append(node('div','stage-note',stage));assistant.append(lead);for(const block of turn.blocks||[]){const rendered=renderBlock(block,onPrompt);if(rendered)assistant.append(rendered);}wrap.append(assistant);return wrap;}
function profileItems(workspace){const explicit=workspace.decisionProfile?.explicit||{},items=[];if(explicit.primaryGoal&&explicit.primaryGoal!=='undecided')items.push({label:'主要目标',text:GOAL_LABELS[explicit.primaryGoal]||explicit.primaryGoal});if(explicit.priorities?.length)items.push({label:'你明确看重',text:explicit.priorities.map(key=>PRIORITY_LABELS[key]||key).join('、')});if(explicit.familyResourceSensitivity==='resource_sensitive')items.push({label:'家庭现实',text:'资源/预算比较敏感'});if(explicit.studyDurationTolerance==='prefer_short')items.push({label:'培养周期',text:'更偏好本科就业 / 不把长期深造当必选'});if(explicit.studyDurationTolerance==='long_ok')items.push({label:'培养周期',text:'可以接受较长培养/深造路径'});return items;}
export function renderAdvisor(workspace,els,onPrompt){const view=workspace.activeView||{},has=Boolean(view.score||(view.majorKeywords||[]).length||((view.regionKeys||[]).length&&!view.regionKeys.includes('all'))||(view.schoolNames||[]).length||view.bottomLineMode!=='all');els.activeViewBar.hidden=!has;els.activeViewChips.replaceChildren();if(has){els.currentContextTitle.textContent=activeViewLabel(view);if(view.score)els.activeViewChips.append(node('span','view-chip',`${view.score}分${workspace.examContext?.rank?` · 约${numberText(workspace.examContext.rank)}位`:''}`));els.activeViewChips.append(node('span','view-chip',regionText(view.regionKeys)));for(const major of view.majorKeywords||[])els.activeViewChips.append(node('span','view-chip',major));for(const school of view.schoolNames||[])els.activeViewChips.append(node('span','view-chip',school));if(view.bottomLineMode&&view.bottomLineMode!=='all')els.activeViewChips.append(node('span','view-chip',bottomLineText(view.bottomLineMode)));if((view.majorKeywords||[]).length)els.activeViewChips.append(promptButton('专业不限','专业先不限，其他条件不变',onPrompt,'view-chip actionable'));if((view.regionKeys||[]).some(key=>key!=='all'))els.activeViewChips.append(promptButton('地区放开','地区先放开，其他条件不变',onPrompt,'view-chip actionable'));}
  els.conversation.replaceChildren();const turns=workspace.turnHistory||[];els.starter.hidden=turns.length>0;for(const turn of turns)els.conversation.append(renderTurn(turn,onPrompt));
  els.constraintList.replaceChildren();const entries=[...profileItems(workspace)];for(const item of workspace.hardConstraints||[])entries.push({label:item.label||item.key,text:item.key.startsWith('region')?(item.values||[]).map(regionKeyLabel).join('、'):(item.values||[]).join(' / ')});if(workspace.selectionSnapshot?.items?.length)entries.push({label:'家庭方案',text:`已导入${workspace.selectionSnapshot.items.length}项只读快照`});if(!entries.length)els.constraintList.append(node('p','empty-note','这里目前没有长期条件。临时说“省内”“沈阳”不会自动写成家庭底线。'));for(const entry of entries){const row=node('div','support-item');row.append(node('strong','',entry.label),node('span','',entry.text));els.constraintList.append(row);}
  els.pendingList.replaceChildren();if(!(workspace.pendingChecks||[]).length)els.pendingList.append(node('p','empty-note','当前没有新增待核验事项。'));for(const item of workspace.pendingChecks||[])els.pendingList.append(node('div','support-item',item.text||String(item)));
  els.evidenceList.replaceChildren();if(!(workspace.evidence||[]).length)els.evidenceList.append(node('p','empty-note','需要核验学校、专业、政策事实时，这里再出现官方入口。'));for(const item of (workspace.evidence||[]).slice(0,10)){const row=node('div','support-item'),href=safeHref(item.sourceUrl);if(href){const a=node('a','',item.sourceName||'官方来源');a.href=href;a.target='_blank';a.rel='noopener noreferrer';row.append(a);}else row.append(node('span','',item.sourceName||'官方来源'));if(item.scope)row.append(node('div','muted',item.scope));els.evidenceList.append(row);}}
