// V2.9.8 path explain engine: catalog-verified interest match + path review + export evidence.
(function(){
  function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
  function uniq(arr){return [...new Set((arr||[]).filter(Boolean))];}
  function imatch(r){return window.LN_CHILD_INTEREST_RUNTIME_V298?.matchRecord?.(r)||window.LN_CHILD_INTEREST_RUNTIME_V296?.matchRecord?.(r)||null;}
  function evidenceText(im){if(!im?.evidence)return ''; const e=im.evidence; const code=e.code||e.catalogMajorCode||e.catalogCategoryCode||''; const name=e.standardName||e.catalogMajorName||e.catalogCategoryName||''; const src=e.source==='keyword'?'招生名称关键词':e.source==='majorCode'?'本科专业代码':e.source==='categoryCode'?'本科专业类代码':e.source==='standardName'?'本科目录标准名':e.source||'匹配依据'; return `${src}${code||name?'：':''}${code}${name?(' '+name):''}`.trim();}
  function computeRaw(r,ctx){
    const im=imatch(r); const mis=window.LN_MAJOR_MISREAD_RULES_V2976?.match?.(r)||[]; const reviews=window.LN_PATH_REVIEW_RULES_V2976?.match?.(r)||[]; const band=window.LN_SCORE_RANK_BAND_RULES_V2976?.current?.()||null; const conflicts=window.LN_INTENT_CONFLICT_RULES_V2976?.detect?.()||[]; const scenario=window.LN_PATH_SCENARIO_RULES_V2976?.summary?.()||{hints:[]}; const ordered=[...mis,...reviews].sort((a,b)=>(b.priority||0)-(a.priority||0)); const usableBand=band&&band.id&&band.id!=='unknown'?band:null;
    let interestTag=''; if(im?.active&&im.level&&im.level!=='none'&&im.level!=='no') interestTag=`孩子关注：${im.intentShort||im.group?.short||'兴趣'}｜${im.label}`; else if(im?.active&&im.level==='none') interestTag='综合备选';
    const tags=uniq([interestTag,...ordered.flatMap(x=>x.tags||[]),...(usableBand?.tags||[])]).slice(0,3);
    const ev=evidenceText(im); let cardMessage='';
    if(im?.active&&im.level&&im.level!=='none'&&im.level!=='no') cardMessage=`${interestTag}。${ev?`依据：${ev}。`:''}${im.message||'该候选为当前真实数据命中项，会在 B「看专业」中软加权。'}`;
    else if(im?.active&&im.level==='none') cardMessage='综合备选：未直接命中孩子关注点，但符合位次和家庭底线。';
    else cardMessage=(ordered[0]?.message||usableBand?.message||'').trim();
    const details=uniq([im?.message, ev?`匹配依据：${ev}`:'', ...(ordered[0]?.detailMessages||[]), ...ordered.slice(1,3).map(x=>x.message), usableBand?.message]).slice(0,3);
    return {im,mis,reviews,band:usableBand,conflicts,scenario,tags,cardMessage,detailMessages:details,first:ordered[0]||null,evidenceText:ev};
  }
  function explainRaw(r,ctx){if(!r)return {tags:[],cardMessage:'',detailMessages:[],hardExclude:false,sourceRuleIds:[]}; const raw=computeRaw(r,ctx||{}); const conflictMessages=(raw.conflicts||[]).map(x=>x.message).slice(0,1); const scenarioHints=(raw.scenario?.hints||[]).map(x=>x.title).slice(0,3); const sourceRuleIds=uniq([...(raw.mis||[]).map(x=>x.id),...(raw.reviews||[]).map(x=>x.id),raw.band?.id,raw.im?.interestId,raw.im?.evidence?.code]).filter(Boolean); return {tags:raw.tags,cardMessage:raw.cardMessage||'',detailMessages:raw.detailMessages||[],intentMessage:raw.im?.reason||'',bandMessage:raw.band?.message||'',conflictMessages,scenarioHints,reviewLevel:raw.tags.length||raw.cardMessage?'review':'normal',hardExclude:false,sourceRuleIds,interestMatch:raw.im||null,evidenceText:raw.evidenceText||''};}
  function explain(r,ctx){try{const cache=window.LN_CANDIDATE_CACHE_V296; if(cache?.get)return cache.get(r,'pathExplainV298',()=>explainRaw(r,ctx)); if(r){if(!r._pathExplainV298)r._pathExplainV298=explainRaw(r,ctx); return r._pathExplainV298;}}catch(e){return explainRaw(r,ctx);} return explainRaw(r,ctx);}
  function matchHtml(r){const ex=explain(r); const im=ex.interestMatch; if(!im?.active)return ''; const level=im.level==='none'?'none':im.level; const text=im.level==='none'?'综合备选：未直接命中孩子关注点，但符合位次和家庭底线。':(im.reason||`孩子关注：${im.intentShort||'兴趣'}｜${im.label}`); const ev=ex.evidenceText?`<small>依据：${esc(ex.evidenceText)}</small>`:''; return `<div class="interest-match-v2976 ${esc(level)}">${esc(text)}${ev}</div>`;}
  function badgesHtml(r){const ex=explain(r); if(!ex.tags.length)return ''; return `<div class="path-tags-v2975">${ex.tags.slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div>`;}
  function cardHtml(r){const ex=explain(r); if(!ex.cardMessage&&!ex.tags.length&&!ex.interestMatch?.active)return ''; return `<div class="path-reminder-v2975">${matchHtml(r)}${badgesHtml(r)}${ex.cardMessage?`<p>${esc(ex.cardMessage)}</p>`:''}</div>`;}
  function detailHtml(r){const ex=explain(r); if(!ex.detailMessages.length&&!ex.conflictMessages.length)return ''; const lines=uniq([...(ex.detailMessages||[]),...(ex.conflictMessages||[])]).slice(0,3).map(x=>`<li>${esc(x)}</li>`).join(''); return `<details class="path-detail-v2975"><summary><span>路径复核</span><b>${esc((ex.tags||[]).slice(0,3).join('｜')||'专业路径提醒')}</b></summary><div><ul>${lines}</ul><p>该提醒不代表不建议填报；系统只对当前真实候选做本科目录匹配，不会生成不存在的专业。</p></div></details>`;}
  function exportTags(r){return (explain(r).tags||[]).join('|');}
  function exportMessage(r){const ex=explain(r); return ex.cardMessage||ex.detailMessages?.[0]||'';}
  function exportEvidence(r){const im=explain(r).interestMatch; const e=im?.evidence||{}; return {childInterest: im?.intentShort||'', activeInterest: im?.group?.name||'', matchLevel: im?.label||'', evidence: explain(r).evidenceText||'', catalogMajorCode:e.catalogMajorCode||'', catalogMajorName:e.catalogMajorName||'', catalogCategoryCode:e.catalogCategoryCode||'', catalogCategoryName:e.catalogCategoryName||'', reviewMessage: exportMessage(r)};}
  function sample(){const items=[{major:'动物医学',officialMajorCode:'090401',officialCategoryCode:'0904',officialMajorName:'动物医学'},{major:'生物工程',officialMajorCode:'083001',officialCategoryCode:'0830',officialMajorName:'生物工程'},{major:'动物科学',officialMajorCode:'090301',officialCategoryCode:'0903',officialMajorName:'动物科学'},{major:'电气工程及其自动化',officialMajorCode:'080601',officialCategoryCode:'0806',officialMajorName:'电气工程及其自动化'}]; return items.map(x=>({major:x.major,explain:explainRaw(x)}));}
  const api={explain,explainRaw,cardHtml,detailHtml,badgesHtml,matchHtml,exportTags,exportMessage,exportEvidence,evidenceText,sample,ready:true}; window.LN_PATH_EXPLAIN_ENGINE_V298=api; window.LN_PATH_EXPLAIN_ENGINE_V2976=api; window.LN_PATH_EXPLAIN_ENGINE_V2975=api;
})();
