import { ALL_211_SCHOOL_BACKGROUND_INDEX } from '../../kb/211-mainline/211-school-background.generated.js?v=3947_4';
import { fetchApiJson, formatApiErrorForHuman, apiErrorDiagnosticHtml } from '../shared/api-client.js?v=3947_4';
const $ = (id) => document.getElementById(id);
const DEBUG = new URLSearchParams(location.search).get('debug') === '1';
function esc(value=''){return String(value==null?'':value).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function fmt(value){const n=Number(value);return Number.isFinite(n)?n.toLocaleString('zh-CN'):esc(value||'');}
const state={tab:'school',index:ALL_211_SCHOOL_BACKGROUND_INDEX};
function levelClass(level){return level==='primary'?'primary':level==='secondary'?'secondary':'trajectory'}
function levelFromLabel(label){return label==='本校方向'?'primary':label==='本校相关'?'secondary':'trajectory'}
function stat(s){return {primary:s.primaryDirections?.length||0,secondary:s.secondaryDirections?.length||0,trajectory:s.trajectoryWarnings?.length||0}}
function schoolCard(s){const c=stat(s);const muted=s.isMilitarySpecial?' is-soft-muted':'';return `<article class="lm-card jm-school-card${muted}"><div class="lm-card-top"><div><h3>${esc(s.school)}</h3><p>${esc(s.batch||'211 院校')}</p></div><span class="lm-pill ${s.isMilitarySpecial?'muted':'primary'}">${s.isMilitarySpecial?'特殊边界':'211'}</span></div><p class="lm-card-note">${esc((s.summaryForParent||'该校已有 211 背景记录，建议结合本科专业再看。').slice(0,110))}</p><div class="lm-stat-row"><span>本校方向 ${fmt(c.primary)}</span><span>本校相关 ${fmt(c.secondary)}</span><span>方向提醒 ${fmt(c.trajectory)}</span></div>${s.isMilitarySpecial?`<p class="lm-card-note is-subtle">${esc(s.specialBoundary)}</p>`:`<button class="lm-card-action" data-school-detail="${esc(s.school)}">查看学校背景</button>`}</article>`}
function renderSchools(){const q=($('schoolSearch')?.value||'').trim();let arr=state.index.schools.filter(s=>!q||s.school.includes(q)||String(s.summaryForParent||'').includes(q));$('schoolList').innerHTML=arr.length?arr.slice(0,q?80:42).map(schoolCard).join(''):`<div class="lm-empty"><b>没有找到明确的 211 学校背景</b><p>可以换个学校名。未命中不代表学校不好，只说明当前 KB 没有前台可触发记录。</p></div>`;$('schoolList').querySelectorAll('[data-school-detail]').forEach(b=>b.addEventListener('click',()=>showSchool(b.dataset.schoolDetail)));}
function directionGroup(title, lines){if(!lines?.length)return '';return `<section class="lm-direction-group"><div class="lm-direction-head"><h3>${esc(title)}</h3><span>${fmt(lines.length)} 条</span></div>${lines.map(line=>`<div class="lm-record-card"><div class="lm-mainline-row"><span class="lm-pill ${levelClass(line.level)}">${esc(line.displayLabel)}</span> ${esc(line.direction)}</div><p class="lm-card-note">本科专业：${esc((line.majors||[]).join(' / '))}</p><p class="lm-review-row">建议再看：${esc((line.reviewPoints||['培养方案','招生章程']).slice(0,4).join(' / '))}</p>${line.evidenceText?`<p class="lm-card-note is-subtle">证据摘要：${esc(line.evidenceText.slice(0,120))}</p>`:''}</div>`).join('')}</section>`}
function showSchool(name){const s=state.index.schools.find(x=>x.school===name);if(!s)return;const root=$('schoolDetail');root.hidden=false;root.innerHTML=`<div class="lm-detail-head"><h2>${esc(s.school)}：先看学校背景，再看本科专业对应</h2><p>${esc(s.summaryForParent||state.index.copy.boundary)}</p>${s.isMilitarySpecial?`<p class="lm-card-note is-subtle">${esc(s.specialBoundary)}</p>`:''}</div>${directionGroup('本校方向',s.primaryDirections)}${directionGroup('本校相关',s.secondaryDirections)}${directionGroup('方向提醒',s.trajectoryWarnings)}${s.pendingReview?.length?`<section class="lm-direction-group"><h3>待核验</h3><ul>${s.pendingReview.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`:''}`;root.scrollIntoView({behavior:'smooth',block:'nearest'});}
function majorCard(m){const primary=m.schools.filter(x=>x.level==='primary').length;const secondary=m.schools.filter(x=>x.level==='secondary').length;const trajectory=m.schools.filter(x=>x.level==='trajectory').length;return `<article class="lm-card"><div class="lm-card-top"><div><h3>${esc(m.major)}</h3><p>涉及 ${fmt(m.schools.length)} 所 211 院校</p></div><span class="lm-pill primary">专业</span></div><div class="lm-stat-row"><span>本校方向 ${fmt(primary)}</span><span>本校相关 ${fmt(secondary)}</span><span>方向提醒 ${fmt(trajectory)}</span></div><button class="lm-card-action" data-major-detail="${esc(m.major)}">查看相关学校</button></article>`}
function renderMajors(){const q=($('majorSearch')?.value||'').trim();let arr=state.index.majors.filter(m=>!q||m.major.includes(q)||m.schools.some(s=>s.school.includes(q)||s.direction.includes(q)));$('majorList').innerHTML=arr.length?arr.slice(0,q?80:45).map(majorCard).join(''):`<div class="lm-empty"><b>没有找到明确的专业背景提示</b><p>可以换个专业名。未命中不代表专业不好，只说明当前 KB 没有前台可触发记录。</p></div>`;$('majorList').querySelectorAll('[data-major-detail]').forEach(b=>b.addEventListener('click',()=>showMajor(b.dataset.majorDetail)));}
function showMajor(major){const m=state.index.majors.find(x=>x.major===major);if(!m)return;const groups=['primary','secondary','trajectory'].map(level=>({level,items:m.schools.filter(x=>x.level===level)}));const root=$('majorDetail');root.hidden=false;root.innerHTML=`<div class="lm-detail-head"><h2>${esc(major)}：不同 211 院校的背景提示</h2><p>同名专业在不同学校可能对应不同学科、学院和培养方向，建议继续看培养方案和招生章程。</p></div>${groups.map(g=>g.items.length?`<section class="lm-direction-group"><div class="lm-direction-head"><h3>${g.level==='primary'?'本校方向':g.level==='secondary'?'本校相关':'方向提醒'}</h3><span>${fmt(g.items.length)} 所</span></div><div class="lm-record-list">${g.items.map(x=>`<article class="lm-record-card"><div class="lm-record-top"><div><h3>${esc(x.school)}</h3><p>${esc(x.direction)}</p></div><span class="lm-pill ${levelClass(x.level)}">${esc(x.label)}</span></div><p class="lm-review-row">建议再看：${esc((x.reviewPoints||[]).join(' / ')||'培养方案 / 招生章程')}</p></article>`).join('')}</div></section>`:'').join('')}`;root.scrollIntoView({behavior:'smooth',block:'nearest'});}
function recordCard(r){const bg=r.mainline211||{};const score2025=r.score2025??r.score;const rank2025=r.rank2025??r.rank;const delta=Number.isFinite(Number(r.scoreDelta))?(Number(r.scoreDelta)>0?`+${r.scoreDelta}`:`${r.scoreDelta}`):'';return `<article class="lm-record-card"><div class="lm-record-top"><div><h3>${esc(r.school)}</h3><p>${esc(r.major)}</p></div><span class="lm-pill ${levelClass(levelFromLabel(bg.label||r.label))}">${esc(bg.label||r.label||'背景提示')}</span></div><div class="lm-data-row"><span>历史最低分：${fmt(score2025)}</span><span>位次：${fmt(rank2025)}</span>${delta?`<span>相对分数：${esc(delta)}</span>`:''}</div><div class="lm-mainline-row">${esc(bg.short||r.backgroundText||'211 背景提示')}</div><p class="lm-review-row">建议再看：${esc((bg.reviewPoints||r.reviewPoints||['培养方案','招生章程']).join(' / '))}</p></article>`}
function scoreSection(title, desc, records){return `<section class="lm-score-section"><h3>${esc(title)}</h3><p class="lm-score-section-desc">${esc(desc)}</p>${records?.length?records.slice(0,40).map(recordCard).join(''):`<div class="lm-empty"><b>这一段暂时没有可显示记录</b><p>可以调整查看方式，或先按学校 / 专业入口复核。</p></div>`}</section>`}
function scoreActionHtml(){return `<div class="lm-error-actions"><button type="button" class="lm-secondary" data-score-retry>重新试一次</button><button type="button" class="lm-secondary" data-score-tab="school">按学校看</button><button type="button" class="lm-secondary" data-score-tab="major">按专业看</button></div>`}
async function queryScore(){const score=Number($('scoreInput')?.value);const root=$('scoreResult');if(!Number.isFinite(score)||score<=0){root.innerHTML='<div class="lm-empty"><b>请先输入有效分数</b><p>例如 666。</p></div>';return;}root.innerHTML='<div class="lm-empty is-loading"><b>正在按孩子位置读取历史数据…</b><p>这里只做历史记录和学校背景复核，不代表录取判断。</p></div>';try{const level=$('scoreLevel')?.value||'primary_secondary';const data=await fetchApiJson(`/api/211-mainline?mode=position&score=${encodeURIComponent(score)}&level=${encodeURIComponent(level)}`,{userMessage:'211 分数入口暂时没有读取成功。可以稍后重试。'});const count=Number(data.count||0);const emptyHead=count===0?`<div class="lm-empty lm-score-empty"><b>这个当前位置附近暂时没有可显示的 211 背景记录</b><p>${esc(data.humanMessage||'可以换一个分数位置，或先按学校 / 专业入口查看 211 背景。')}</p>${scoreActionHtml()}</div>`:'';root.innerHTML=`<div class="lm-detail-head"><h2>按孩子当前位置查看 211 专业历史记录</h2><p>${esc(data.boundary||state.index.copy.scoreBoundary)}</p></div>${emptyHead}${scoreSection('接近当前位置的历史记录','当前参考窗口下，历史最低分在孩子位置附近。',data.grouped?.near||[])}${scoreSection('稍高一些的历史记录','当前参考窗口下，历史最低分稍高一些。',data.grouped?.upper||[])}${scoreSection('低一些可讨论的历史记录','当前参考窗口下，历史最低分低一些，可作为家庭讨论。',data.grouped?.lower||[])}`;}catch(error){root.innerHTML=`<div class="lm-empty"><b>211 分数入口暂时没有读取成功</b><p>${esc(formatApiErrorForHuman(error,'这不影响按学校和按专业查看 211 背景，也不影响主页面专业初选。'))}</p><p>这不影响按学校和按专业查看 211 背景，也不影响主页面专业初选。</p>${scoreActionHtml()}${DEBUG?`<details class="lm-tech-detail"><summary>给技术人员看的排查信息</summary>${apiErrorDiagnosticHtml(error,esc)||esc(error.message||String(error))}</details>`:''}</div>`;}}
function switchTab(tab){state.tab=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.tab===tab));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==tab);}
function mountQuick(){const q=['计算机','电气','通信工程','法学','金融学','临床医学','材料','交通运输'];const root=$('majorQuickRow'); if(root) root.innerHTML=q.map(x=>`<button type="button" data-quick-major="${esc(x)}">${esc(x)}</button>`).join(''); root?.querySelectorAll('[data-quick-major]').forEach(b=>b.addEventListener('click',()=>{ $('majorSearch').value=b.dataset.quickMajor; renderMajors(); }));}
function boot(){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));document.querySelectorAll('[data-start-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.startTab)));$('schoolSearch')?.addEventListener('input',renderSchools);$('majorSearch')?.addEventListener('input',renderMajors);$('scoreQuery')?.addEventListener('click',queryScore);$('scoreResult')?.addEventListener('click',(event)=>{const retry=event.target.closest('[data-score-retry]');if(retry){queryScore();return;}const tab=event.target.closest('[data-score-tab]')?.dataset.scoreTab;if(tab)switchTab(tab);});mountQuick();renderSchools();renderMajors();const params=new URLSearchParams(location.search);if(params.get('major')){switchTab('major');$('majorSearch').value=params.get('major');renderMajors();}else if(params.get('school')){switchTab('school');$('schoolSearch').value=params.get('school');renderSchools();const s=state.index.schools.find(x=>x.school.includes(params.get('school')));if(s)showSchool(s.school);} }
boot();
