#!/usr/bin/env python3
"""Preserve stable artifact-only metadata after the unified school build.

This module does not parse the MOE workbook and owns no school facts. It only keeps
legacy generated-file headers and an equivalent historic MOE page URL so existing
large artifacts do not churn for non-data reasons.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

CANONICAL_PAGE = "https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/202606/t20260618_1441074.html"
REGION_COMPAT_PAGE = "https://www.moe.gov.cn/jyb_xxgk/s5743/s5744/A03/202606/t20260618_1441074.html"
PROFILE_HEADER = "// Generated by tools/schools/build-school-profile-center-v3957.py. Do not edit by hand."


def apply_profile_header(path: Path) -> None:
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    if not lines:
        raise RuntimeError(f"学校资料文件为空：{path}")
    if not lines[0].startswith("// Generated by tools/schools/"):
        raise RuntimeError(f"学校资料生成器标记异常：{lines[0]}")
    lines[0] = PROFILE_HEADER
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def apply_region_source_page(path: Path) -> None:
    payload = json.loads(path.read_text(encoding="utf-8"))
    source = payload.get("source") or {}
    page = str(source.get("pageUrl") or "")
    if page not in {CANONICAL_PAGE, REGION_COMPAT_PAGE}:
        raise RuntimeError(f"Tongxue地域索引来源页异常：{page}")
    source["pageUrl"] = REGION_COMPAT_PAGE
    payload["source"] = source
    path.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")


def apply_all(profile_path: Path, region_path: Path) -> None:
    apply_profile_header(profile_path)
    apply_region_source_page(region_path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", default="shared/resources/schools/school-profile-data.20260617-v3957.js")
    parser.add_argument("--region", default="tongxue/data/school-search-index.20260617-v150.json")
    args = parser.parse_args()
    apply_all(Path(args.profile).resolve(), Path(args.region).resolve())
    print(json.dumps({
        "profile": str(Path(args.profile).resolve()),
        "region": str(Path(args.region).resolve()),
        "factOwner": "tools/schools/school_resource_bundle.py",
        "compatibilityOnly": True,
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
