import { LIAONING_PHYSICS_EXAM_CONFIG, SUPPORTED_LIAONING_PHYSICS_YEARS } from '../exam/liaoning-physics.js';

const EXAM = LIAONING_PHYSICS_EXAM_CONFIG;

export const CURRENT_RELEASE = Object.freeze({
  display: 'v3.9.68.0',
  version: 'v3.9.68.0',
  asset: '3968_0',
  assetVersion: 'v3968_0',
  release: 'v3.9.68.0-unified-academic-background-evidence-no-fenxi',
  releaseName: 'v3.9.68.0-unified-academic-background-evidence-no-fenxi',
  label: 'unified-academic-background-evidence-no-fenxi',
  dataYear: EXAM.dataYear,
  audienceYear: EXAM.audienceYear,
  rankTableYear: EXAM.rankYear,
  rankTableYears: SUPPORTED_LIAONING_PHYSICS_YEARS,
  region: EXAM.region,
  subject: EXAM.subject,
  noFenxiIncluded: true,
  resourceOwnershipVersion: 'resource-ownership-v3968_0',
  resourceExecutionVersion: 'resource-execution-v3968_0',
  derivationTraceVersion: 'derivation-trace-v3968_0',
  uiOrchestrationVersion: 'ui-orchestration-v3968_0',
  uiComponentExecutionVersion: 'ui-component-execution-v3967_0',
  algorithmOrchestrationVersion: 'algorithm-orchestration-v3968',
  resultRankingVersion: 'result-ranking-v3967_0',
  trendInterpretationVersion: 'trend-interpretation-v3967_0',
  historicalRankSelectionVersion: 'historical-rank-selection-v3967_0',
  academicBackgroundVersion: 'academic-background-v3968_0',
  academicBackgroundMatcherVersion: 'academic-background-matcher-v3968_0',
  academicBackgroundProviderVersion: 'academic-background-provider-v3968_0',
  selectionWorkspaceVersion: 'selection-workspace-orchestration-v3967_0',
  searchIntentVersion: 'score-school-search-v3967_0',
  schoolAllModeVersion: 'school-all-mode-v3967_0',
  schoolUiGovernanceVersion: 'school-ui-governance-v3967_0',
  schoolModeMountVersion: 'school-mode-static-mount-v3967_0',
  runtimeCacheVersion: 'runtime-cache-coherence-v3968_0',
  staticContentTypeOwnershipVersion: 'static-content-type-ownership-v3967_0',
  cacheRecoveryVersion: 'cached-runtime-recovery-v3967_0',
  reportFrontendVersion: 'feishu-browser-v3967_0',
  historyEvidenceVersion: 'ln-physics-history-evidence-v3967_0',
  tongxueRuntimeVersion: 'tongxue-runtime-v159-r3968',
  resourceOwners: Object.freeze({
    release: '/shared/resources/release/current-release.js',
    releasePresenter: '/shared/resources/release/release-presenter.v3968_0.js',
    resourceExecution: '/shared/governance/resource-execution-contract.v3968_0.js',
    exam: '/shared/resources/exam/liaoning-physics.js',
    rankTables: '/functions/_lib/rank-table-provider.js',
    historyScoreRankEvidence: '/functions/_lib/historical-score-rank-evidence.js',
    historyEvidenceContract: '/shared/resources/exam/historical-score-rank-contract.js',
    historyEvidencePresenter: '/ln-rank/js/feature/major-pool/history-score-render.v3967_0.js',
    regions: '/shared/resources/geo/china-region-catalog.js',
    schools: '/shared/resources/schools/school-profile-center.js',
    schoolIdentity: '/shared/resources/schools/school-identity-center.js',
    majors: '/shared/resources/majors/major-catalog-contract.js',
    academicBackgroundContract: '/shared/resources/background/academic-background-contract.v3968_0.js',
    academicBackgroundSources: '/shared/resources/background/academic-background-source-registry.v3968_0.js',
    academicBackgroundProvider: '/functions/_lib/academic-background-provider.js',
    academicBackgroundService: '/functions/_lib/academic-background-api.js',
    academicBackgroundApi: '/functions/api/academic-background.js',
    academicBackgroundMatcher: '/shared/algorithms/background/academic-background-matcher.v3968_0.js',
    academicBackgroundRuntime: '/ln-rank/js/academic-background/academic-background-app.v3968_0.js',
    academicBackgroundStyles: '/ln-rank/css/academic-background.v3968_0.css',
    reports: '/shared/resources/reports/feishu-report-contract.v3966_0.js',
    reportFrontend: '/ln-rank/js/feature/feishu/index.v3967_0.js',
    reportFeedbackState: '/ln-rank/js/feature/feishu/report-controller.v3967_0.js',
    ui: '/shared/ui/ui-registry.v3965_0.js',
    uiComponents: '/shared/ui/component-registry.v3967_0.js',
    uiActions: '/shared/ui/contracts/action-contract.v3959_0.js',
    uiSemantic: '/shared/ui/tokens/semantic.v3959_0.css',
    uiModeSwitch: '/shared/ui/components/mode-switch.v3963_0.css',
    algorithms: '/shared/algorithms/algorithm-registry.js',
    resultRanking: '/shared/algorithms/ranking/result-ranking.v3967_0.js',
    trendResource: '/shared/resources/trends/liaoning-major-trend.v3967_0.js',
    trendInterpretation: '/shared/algorithms/trend/trend-interpretation.v3967_0.js',
    historicalRankSelection: '/shared/algorithms/position/historical-rank-selection.v3967_0.js',
    liaoningKeySubjects: '/shared/resources/auxiliary/liaoning-key-subjects.v3967_0.js',
    searchIntentStructure: '/ln-rank/index.html',
    runtimeCache: '/shared/resources/release/runtime-cache-contract.v3968_0.js',
    runtimeBootstrap: '/ln-rank/js/app.v3968_0.js',
    searchIntentState: '/ln-rank/js/workspace/selection-workspace-orchestrator.v3967_0.js',
    resultCommit: '/ln-rank/js/workspace/result-commit.v3967_0.js',
    familyCardPresentation: '/ln-rank/js/workspace/family-card-presenter.v3967_0.js',
    schoolResults: '/ln-rank/js/feature/school-majors/school-all-mode.v3967_0.js',
    schoolResultsStyles: '/ln-rank/css/school-all-mode.v3967_0.css',
    mainPageStyles: '/ln-rank/css/ln-rank-workspace.v3967_0.css',
    historyEvidenceStyles: '/ln-rank/css/history-evidence.v3967_0.css',
    selectionPageStyles: '/ln-rank/css/selection-pool.v3964_0.css',
    selectionRuntime: '/ln-rank/js/selection-pool-runtime.v3967_0.js',
    selectionStoreAdapter: '/ln-rank/js/feature/selection-pool/store.v3967_0.js',
    diagnoseTransport: '/ln-rank/js/feature/diagnose/api.v3967_0.js',
    localMainlineRuntime: '/ln-rank/js/academic-background/academic-background-app.v3968_0.js',
    all211MainlineRuntime: '/ln-rank/js/academic-background/academic-background-app.v3968_0.js',
    selectionQuickEntryStructure: '/ln-rank/index.html#selectionPoolShell',
    tongxueRuntime: '/tongxue/app/tongxue-runtime-v159-r3968.js',
    tongxueState: '/tongxue/app/tongxue-runtime-controller-v159.js',
    reportHistoryPlacement: 'appendix-only'
  })
});

export function getCurrentRelease() { return CURRENT_RELEASE; }
export function currentAssetQuery() { return CURRENT_RELEASE.assetVersion; }
