import { CURRENT_RELEASE } from './current-release.js?v=3972_5';

export const SITE_RUNTIME_CONTRACT = Object.freeze({
  version: 'site-runtime-coherence-v3972_5',
  generation: CURRENT_RELEASE.siteRuntimeGeneration,
  queryVersion: CURRENT_RELEASE.asset,
  releaseVersion: CURRENT_RELEASE.version,
  scope: 'whole-site-active-generation',
  activeEntrypoints: Object.freeze({
    releaseCenter: '/shared/resources/release/current-release.js?v=3972_5',
    releasePresenter: '/shared/resources/release/release-presenter.v3972_5.js?v=3972_5',
    runtimeCache: '/shared/resources/release/runtime-cache-contract.v3972_5.js?v=3972_5',
    resourceExecution: '/shared/governance/resource-execution-contract.v3972_5.js?v=3972_5',
    homePage: '/',
    homeRuntime: '/ln-rank/js/ux/family-home.v3972_5.js?v=3972_5',
    familyShell: '/shared/ui/shell/family-shell.v3972_5.js?v=3972_5',
    familyShellStyles: '/shared/ui/shell/family-shell.v3972_5.css?v=3972_5',
    familyPlanEntry: '/shared/ui/components/family-plan-entry.v3972_5.js?v=3972_5',
    familyPlanEntryStyles: '/shared/ui/components/family-plan-entry.v3972_5.css?v=3972_5',
    selectionPage: '/ln-rank/',
    selectionBootstrap: '/ln-rank/js/app.v3972_5.js?v=3972_5',
    selectionRuntime: '/ln-rank/js/app-runtime.v3972_5.js?v=3972_5',
    selectionWorkspace: '/ln-rank/js/workspace/selection-workspace-orchestrator.v3972_5.js?v=3972_5',
    interactionRuntime: '/shared/ui/interaction/interaction-transaction.v3972_5.js?v=3972_5',
    interactionStyles: '/shared/ui/interaction/interaction-transaction.v3972_5.css?v=3972_5',
    familyPlanPage: '/ln-rank/selection-pool.html',
    familyPlanBootstrap: '/ln-rank/js/selection-pool.v3972_5.js?v=3972_5',
    familyPlanRuntime: '/ln-rank/js/selection-pool-runtime.v3972_5.js?v=3972_5'
  }),
  stablePageEntrypoints: Object.freeze({
    tongxuePage: '/tongxue/',
    tongxueRuntime: '/tongxue/app/tongxue-runtime-v159-r3968.js?v=3968_0',
    localStrengthPage: '/ln-rank/local-mainline.html',
    localStrengthRuntime: '/ln-rank/js/local-strength/local-strength-app.v3971_2.js?v=3972_3',
    localStrengthStyles: '/ln-rank/css/local-strength.v3971_2.css?v=3971_2',
    localStrengthScorePositionStyles: '/ln-rank/css/local-strength-score-position.v3972_3.css?v=3972_3',
    localStrengthData: '/ln-rank/data/local-strength/local-strength-index.v3971_2.json',
    all211Page: '/ln-rank/211-mainline.html',
    all211Runtime: '/ln-rank/js/academic-background/all211-static-app.v3972_0.js?v=3972_0',
    all211Styles: '/ln-rank/css/all211-static.v3972_0.css?v=3972_0',
    all211Data: '/ln-rank/data/211-static/211-static-index.v3972_0.json'
  }),
  owners: Object.freeze({
    release: '/shared/resources/release/current-release.js',
    activeGeneration: '/shared/resources/release/site-runtime-contract.v3972_5.js',
    cache: '/shared/resources/release/runtime-cache-contract.v3972_5.js',
    execution: '/shared/governance/resource-execution-contract.v3972_5.js',
    home: '/ln-rank/js/ux/family-home.v3972_5.js',
    sharedShell: '/shared/ui/shell/family-shell.v3972_5.js',
    familyPlanEntry: '/shared/ui/components/family-plan-entry.v3972_5.js',
    selectionBootstrap: '/ln-rank/js/app.v3972_5.js',
    selectionRuntime: '/ln-rank/js/app-runtime.v3972_5.js',
    selectionWorkspace: '/ln-rank/js/workspace/selection-workspace-orchestrator.v3972_5.js',
    interaction: '/shared/ui/interaction/interaction-transaction.v3972_5.js',
    disclosure: '/shared/ui/interaction/interaction-transaction.v3972_5.js',
    auxiliaryNavigation: '/shared/ui/interaction/interaction-transaction.v3972_5.js',
    familyPlanBootstrap: '/ln-rank/js/selection-pool.v3972_5.js',
    tongxue: '/tongxue/app/tongxue-runtime-v159-r3968.js',
    localStrength: '/ln-rank/js/local-strength/local-strength-app.v3971_2.js',
    all211: '/ln-rank/js/academic-background/all211-static-app.v3972_0.js'
  }),
  stableDependencies: Object.freeze([
    '/shared/resources/exam/liaoning-physics.js',
    '/shared/resources/geo/china-region-catalog.js',
    '/shared/resources/schools/school-query-contract.v3969_0.js',
    '/shared/resources/schools/school-query-engine.v3969_0.js',
    '/shared/resources/schools/liaoning-2026-admission-school-directory.v3969_0.json',
    '/shared/algorithms/algorithm-registry.js',
    '/shared/ui/ui-registry.v3970_0.js',
    '/shared/ui/component-registry.v3970_0.js',
    '/shared/ui/contracts/action-contract.v3970_0.js',
    '/shared/ui/contracts/copy-contract.v3970_0.js',
    '/shared/ui/contracts/state-contract.v3970_0.js',
    '/shared/ui/shell/family-shell.v3970_0.css',
    '/shared/ui/components/family-plan-entry.v3970_0.css',
    '/ln-rank/js/domain/family-decision-contract.v3970_0.js',
    '/ln-rank/js/domain/family-plan-copy-adapter.v3970_0.js',
    '/ln-rank/js/workspace/selection-workspace-orchestrator.v3969_0.js',
    '/ln-rank/js/selection-pool-runtime.v3967_0.js',
    '/ln-rank/js/feature/school-majors/school-all-mode.v3969_0.js',
    '/ln-rank/js/feature/feishu/index.v3967_0.js',
    '/ln-rank/js/feature/report/payload-builder.v3967_0.js',
    '/ln-rank/js/feature/selection-pool/index.v3967_0.js',
    '/ln-rank/js/feature/major-pool/index.v3967_0.js',
    '/ln-rank/js/workspace/result-commit.v3967_0.js',
    '/ln-rank/js/workspace/scroll-policy.v3961_0.js',
    '/ln-rank/js/workspace/viewport-orchestrator.v3961_0.js',
    '/tongxue/app/tongxue-runtime-v159-r3968.js',
    '/tongxue/app/tongxue-runtime-controller-v159.js',
    '/tongxue/app/tongxue-runtime-search-view-v159.js',
    '/tongxue/app/tongxue-runtime-result-view-v159.js',
    '/tongxue/app/tongxue-runtime-utils-v159.js',
    '/shared/resources/release/release-presenter.v3968_0.js',
    '/ln-rank/js/local-strength/local-strength-app.v3971_2.js',
    '/ln-rank/css/local-strength.v3971_2.css',
    '/ln-rank/css/local-strength-score-position.v3972_3.css',
    '/ln-rank/data/local-strength/local-strength-index.v3971_2.json',
    '/shared/resources/release/release-presenter.v3971_2.js',
    '/ln-rank/js/academic-background/all211-static-app.v3972_0.js',
    '/ln-rank/css/all211-static.v3972_0.css',
    '/ln-rank/data/211-static/211-static-index.v3972_0.json',
    '/shared/resources/release/release-presenter.v3972_0.js'
  ]),
  preservedBusinessResources: Object.freeze({
    tongxue: 'tongxue-runtime-v159-r3968',
    localStrength: 'local-strength-static-v3971_2',
    all211: 'all-211-static-v3972_0',
    majorBands: 'major-bands-static-v3972_2'
  }),
  policies: Object.freeze({
    oneActiveGeneration: true,
    activeEntrypointsMustMatchGeneration: true,
    stableDependenciesMustBeDeclared: true,
    stablePageEntrypointsMustBeDeclared: true,
    stableDependenciesCannotOwnNavigation: true,
    stableDependenciesCannotOwnDisclosure: true,
    stableDependenciesCannotOwnReleaseState: true,
    stableDependenciesCannotOwnCacheState: true,
    nativeAuxiliaryHrefForbidden: true,
    explicitNavigationOwnerRequired: true,
    nativeChooserRequiresStableFrames: 2,
    nativeChooserRequiresVisualViewportStability: true,
    freshPointerCannotBypassChooserTransaction: true,
    deviceSpecificBusinessBranchForbidden: true,
    htmlMustRevalidate: true,
    immutableAssetsRequired: true,
    productionGraphMustMatchSourceGraph: true
  })
});

export function getSiteRuntimeContract() {
  return SITE_RUNTIME_CONTRACT;
}
