import { CURRENT_RELEASE } from './current-release.js?v=3990_2';
import { ACTIVE_RESOURCE_MANIFEST } from './active-resource-manifest.v3990_2.js?v=3990_2';

const CURRENT = 'current-generation';
const STABLE = 'declared-stable-dependency';
const TRANSITIVE = 'declared-transitive-implementation';
const DATA = 'current-data-resource';

export const SITE_RUNTIME_CONTRACT = Object.freeze({
  version: 'site-runtime-coherence-v3990_2',
  generation: CURRENT_RELEASE.siteRuntimeGeneration,
  queryVersion: CURRENT_RELEASE.asset,
  releaseVersion: CURRENT_RELEASE.version,
  scope: 'whole-site-active-generation-with-declared-stable-dependencies',
  activeEntrypoints: Object.freeze({
    releaseCenter: '/shared/resources/release/current-release.js?v=3990_2',
    releasePresenter: '/shared/resources/release/release-presenter.v3990_2.js?v=3990_2',
    runtimeCache: '/shared/resources/release/runtime-cache-contract.v3990_2.js?v=3990_2',
    resourceExecution: '/shared/governance/resource-execution-contract.v3990_2.js?v=3990_2',
    majorBandsRankIndex: '/functions/_lib/major-bands-rank-index.v3990_2.js',
    majorBandsQueryKernel: '/functions/_lib/major-bands-rank-query-kernel.v3990_2.js',
    majorBandsBucketLoader: '/functions/_lib/major-bands-rank-bucket-loader.v3990_2.js',
    majorBandsResultOrder: '/functions/_lib/major-bands-result-order.v3990_2.js',
    majorBandsResponseTransport: '/functions/_lib/major-bands-response-transport.v3990_2.js',
    homePage: '/',
    homeRuntime: '/ln-rank/js/ux/family-home.v3990_2.js?v=3990_2',
    familyShell: '/shared/ui/shell/family-shell.v3990_2.js?v=3990_2',
    familyShellStyles: '/shared/ui/shell/family-shell.v3972_5.css?v=3972_5',
    familyPlanEntry: '/shared/ui/components/family-plan-entry.v3990_2.js?v=3990_2',
    familyPlanEntryStyles: '/shared/ui/components/family-plan-entry.v3972_5.css?v=3972_5',
    selectionPage: '/ln-rank/',
    selectionBootstrap: '/ln-rank/js/app.v3990_2.js?v=3990_2',
    selectionRuntime: '/ln-rank/js/app-runtime.v3990_2.js?v=3990_2',
    selectionWorkspace: '/ln-rank/js/workspace/selection-workspace-orchestrator.v3990_2.js?v=3990_2',
    interactionRuntime: '/shared/ui/interaction/interaction-transaction.v3990_2.js?v=3990_2',
    interactionStyles: '/shared/ui/interaction/interaction-transaction.v3990_2.css?v=3990_2',
    familyPlanPage: '/ln-rank/selection-pool.html',
    familyPlanBootstrap: '/ln-rank/js/selection-pool.v3990_2.js?v=3990_2',
    familyPlanRuntime: '/ln-rank/js/selection-pool-runtime.v3990_2.js?v=3990_2',
    aiPage: '/aiplus/',
    aiRuntime: '/aiplus/app.v3990_2.js?v=3990_2',
    aiStyles: '/aiplus/workspace.v3990_2.css?v=3990_2',
    aiWorkspaceContract: '/shared/ai/ai-workspace-contract.v3990_2.js?v=3990_2',
    majorBandsFilter: '/functions/_lib/major-filter.v3990_2.js',
    majorBandsRegionCatalog: '/shared/resources/geo/china-region-catalog.v3990_2.js',
  }),
  activeEntrypointClassifications: Object.freeze({
    releaseCenter: CURRENT,
    releasePresenter: CURRENT,
    runtimeCache: CURRENT,
    resourceExecution: CURRENT,
    majorBandsRankIndex: CURRENT,
    majorBandsQueryKernel: CURRENT,
    majorBandsBucketLoader: CURRENT,
    majorBandsResultOrder: CURRENT,
    majorBandsResponseTransport: CURRENT,
    homePage: CURRENT,
    homeRuntime: CURRENT,
    familyShell: CURRENT,
    familyShellStyles: STABLE,
    familyPlanEntry: CURRENT,
    familyPlanEntryStyles: STABLE,
    selectionPage: CURRENT,
    selectionBootstrap: CURRENT,
    selectionRuntime: CURRENT,
    selectionWorkspace: CURRENT,
    interactionRuntime: CURRENT,
    interactionStyles: CURRENT,
    familyPlanPage: CURRENT,
    familyPlanBootstrap: CURRENT,
    familyPlanRuntime: CURRENT,
    aiPage: CURRENT,
    aiRuntime: CURRENT,
    aiStyles: CURRENT,
    aiWorkspaceContract: CURRENT,
    majorBandsFilter: CURRENT,
    majorBandsRegionCatalog: CURRENT,
  }),
  declaredResourceGraph: Object.freeze({
    manifest: ACTIVE_RESOURCE_MANIFEST,
    transitiveImplementationClassification: TRANSITIVE,
    currentDataClassification: DATA
  }),
  stablePageEntrypoints: Object.freeze({
    tongxuePage: '/tongxue/',
    tongxueRuntime: '/tongxue/app/tongxue-runtime-v159-r3968.js?v=3968_0',
    localStrengthPage: '/ln-rank/local-mainline.html',
    localStrengthRuntime: '/ln-rank/js/local-strength/local-strength-app.v3971_2.js?v=3972_3',
    localStrengthStyles: '/ln-rank/css/local-strength.v3971_2.css?v=3971_2',
    localStrengthScorePositionStyles: '/ln-rank/css/local-strength-score-position.v3972_3.css?v=3972_3',
    localStrengthData: '/ln-rank/data/local-strength/local-strength-index.v3971_2.json',
    all211Page: '/ln-rank/211-mainline.html',
    all211Runtime: '/ln-rank/js/academic-background/all211-static-app.v3972_0.js?v=3972_0',
    all211Styles: '/ln-rank/css/all211-static.v3972_0.css?v=3972_0',
    all211Data: '/ln-rank/data/211-static/211-static-index.v3972_0.json'
  }),
  owners: Object.freeze({
    release: '/shared/resources/release/current-release.js',
    resourceManifest: '/shared/resources/release/active-resource-manifest.v3990_2.js',
    activeGeneration: '/shared/resources/release/site-runtime-contract.v3990_2.js',
    cache: '/shared/resources/release/runtime-cache-contract.v3990_2.js',
    execution: '/shared/governance/resource-execution-contract.v3990_2.js',
    majorBandsRankIndex: '/functions/_lib/major-bands-rank-index.v3990_2.js',
    majorBandsQueryKernel: '/functions/_lib/major-bands-rank-query-kernel.v3990_2.js',
    majorBandsBucketLoader: '/functions/_lib/major-bands-rank-bucket-loader.v3990_2.js',
    majorBandsResultOrder: '/functions/_lib/major-bands-result-order.v3990_2.js',
    majorBandsResponseTransport: '/functions/_lib/major-bands-response-transport.v3990_2.js',
    home: '/ln-rank/js/ux/family-home.v3990_2.js',
    sharedShell: '/shared/ui/shell/family-shell.v3990_2.js',
    familyPlanEntry: '/shared/ui/components/family-plan-entry.v3990_2.js',
    selectionBootstrap: '/ln-rank/js/app.v3990_2.js',
    selectionRuntime: '/ln-rank/js/app-runtime.v3990_2.js',
    selectionWorkspace: '/ln-rank/js/workspace/selection-workspace-orchestrator.v3990_2.js',
    selectionWorkspaceStableImplementation: '/ln-rank/js/workspace/selection-workspace-orchestrator.v3969_2.js',
    interaction: '/shared/ui/interaction/interaction-transaction.v3990_2.js',
    disclosure: '/shared/ui/interaction/interaction-transaction.v3990_2.js',
    auxiliaryNavigation: '/shared/ui/interaction/interaction-transaction.v3990_2.js',
    nativeChooserActivation: '/shared/ui/interaction/interaction-transaction.v3990_2.js',
    familyPlanBootstrap: '/ln-rank/js/selection-pool.v3990_2.js',
    familyPlanRuntime: '/ln-rank/js/selection-pool-runtime.v3990_2.js',
    ai: '/aiplus/app.v3990_2.js',
    aiWorkspace: '/shared/ai/ai-workspace-contract.v3990_2.js',
    aiplusWorkspaceImplementation: ACTIVE_RESOURCE_MANIFEST.aiplus.transitiveImplementation.workspaceContract.owner,
    aiplusRenderImplementation: ACTIVE_RESOURCE_MANIFEST.aiplus.transitiveImplementation.render.owner,
    aiplusHistoryImplementation: ACTIVE_RESOURCE_MANIFEST.aiplus.transitiveImplementation.history.owner,
    majorSourceProfile: ACTIVE_RESOURCE_MANIFEST.majorSourceProfile.owner,
    schoolDirectory: ACTIVE_RESOURCE_MANIFEST.schoolDirectory.directoryLoader,
    schoolResourceCenter: ACTIVE_RESOURCE_MANIFEST.schoolDirectory.resourceCenter,
    schoolDirectoryData: ACTIVE_RESOURCE_MANIFEST.schoolDirectory.directoryData,
    majorBandsFilter: '/functions/_lib/major-filter.v3990_2.js',
    majorBandsRegionCatalog: '/shared/resources/geo/china-region-catalog.v3990_2.js',
    tongxue: '/tongxue/app/tongxue-runtime-v159-r3968.js',
    localStrength: '/ln-rank/js/local-strength/local-strength-app.v3971_2.js',
    all211: '/ln-rank/js/academic-background/all211-static-app.v3972_0.js',
  }),
  stableDependencies: Object.freeze([
    '/shared/resources/exam/liaoning-physics.js',
    '/shared/resources/geo/china-region-catalog.js',
    '/shared/resources/schools/school-query-contract.v3969_0.js',
    '/shared/resources/schools/school-query-engine.v3969_0.js',
    '/shared/resources/schools/liaoning-2026-admission-school-directory.v3969_0.json',
    '/shared/algorithms/algorithm-registry.js',
    '/shared/ui/ui-registry.v3970_0.js',
    '/shared/ui/component-registry.v3970_0.js',
    '/shared/ui/contracts/action-contract.v3970_0.js',
    '/shared/ui/contracts/copy-contract.v3970_0.js',
    '/shared/ui/contracts/state-contract.v3970_0.js',
    '/shared/ui/tokens/foundation.v3959_0.css',
    '/shared/ui/tokens/semantic.v3959_0.css',
    '/shared/ui/components/mode-switch.v3963_0.css',
    '/shared/ui/shell/family-shell.v3972_5.css',
    '/shared/ui/components/family-plan-entry.v3972_5.css',
    '/ln-rank/js/domain/family-decision-contract.v3970_0.js',
    '/ln-rank/js/domain/family-plan-copy-adapter.v3970_0.js',
    '/ln-rank/js/workspace/selection-workspace-orchestrator.v3969_2.js',
    '/ln-rank/js/selection-pool-runtime.v3967_0.js',
    '/ln-rank/js/feature/school-majors/school-all-mode.v3969_2.js',
    '/ln-rank/js/feature/feishu/index.v3967_0.js',
    '/ln-rank/js/feature/report/payload-builder.v3967_0.js',
    '/ln-rank/js/feature/selection-pool/index.v3967_0.js',
    '/ln-rank/js/feature/major-pool/index.v3967_0.js',
    '/ln-rank/js/workspace/result-commit.v3967_0.js',
    '/ln-rank/js/workspace/scroll-policy.v3961_0.js',
    '/ln-rank/js/workspace/viewport-orchestrator.v3961_0.js',
    '/tongxue/app/tongxue-runtime-v159-r3968.js',
    '/tongxue/app/tongxue-runtime-controller-v159.js',
    '/tongxue/app/tongxue-runtime-search-view-v159.js',
    '/tongxue/app/tongxue-runtime-result-view-v159.js',
    '/tongxue/app/tongxue-runtime-utils-v159.js',
    '/shared/resources/release/release-presenter.v3968_0.js',
    '/ln-rank/js/local-strength/local-strength-app.v3971_2.js',
    '/ln-rank/css/local-strength.v3971_2.css',
    '/ln-rank/css/local-strength-score-position.v3972_3.css',
    '/ln-rank/data/local-strength/local-strength-index.v3971_2.json',
    '/shared/resources/release/release-presenter.v3971_2.js',
    '/ln-rank/js/academic-background/all211-static-app.v3972_0.js',
    '/ln-rank/css/all211-static.v3972_0.css',
    '/ln-rank/data/211-static/211-static-index.v3972_0.json',
    '/shared/resources/release/release-presenter.v3972_0.js',
    '/ln-rank/data/major-bands-static-v3972_2/manifest.json',
    '/functions/api/major-bands-bucket.js',
    '/functions/_lib/major-bands-bucket-orchestrator.v3972_5.js',
    '/functions/_lib/major-bands-bucket-cache.v3972_5.js',
    '/functions/_lib/major-bands-bucket-transfer.v3972_5.js'
  ]),
  preservedBusinessResources: Object.freeze({
    tongxue: 'tongxue-runtime-v159-r3968',
    localStrength: 'local-strength-static-v3971_2',
    all211: 'all-211-static-v3972_0',
    majorBands: 'major-bands-static-v3972_2',
    majorBandsWorker: 'major-bands-bounded-fanout-v3972_5'
  }),
  policies: Object.freeze({
    oneActiveGeneration: true,
    activeEntrypointsMustMatchGenerationOrDeclaredStableDependency: true,
    stableDependenciesMustBeDeclared: true,
    stablePageEntrypointsMustBeDeclared: true,
    stableDependenciesCannotOwnCurrentInteraction: true,
    stableDependenciesCannotOwnCurrentReleaseState: true,
    stableDependenciesCannotOwnCurrentCacheState: true,
    currentInfrastructureCannotImportRetiredReleaseQuery: true,
    nativeAuxiliaryHrefForbidden: true,
    explicitNavigationOwnerRequired: true,
    nativeChooserRequiresStableFrames: 2,
    nativeChooserRequiresVisualViewportStability: true,
    nativeChooserPreActivationDomMutationForbidden: true,
    nativeChooserSinglePhysicalEventFamily: true,
    nativeChooserTailGuardAfterOutcomeOnly: true,
    nativeChooserFocusReturnBounded: true,
    freshPointerCannotBypassChooserTransaction: true,
    deviceSpecificBusinessBranchForbidden: true,
    htmlMustRevalidate: true,
    immutableAssetsRequired: true,
    productionGraphMustMatchSourceGraph: true,
    majorBandsRankTruthEqualsRecall: true,
    majorBandsAllPresetsExecutable: true,
    majorBandsStableSnapshotPagination: true,
    majorBandsStrictNextOffset: true,
    majorBandsHighBoundaryReturnsEmpty200: true,
    majorBandsPublicHttpSelfFanoutForbidden: true,
    aiModelCannotOwnBusinessFacts: true,
    aiTemporaryViewCannotBecomeFamilyConstraint: true,
    aiLatestRequestOnlyCanCommit: true
  })
});

export function getSiteRuntimeContract() {
  return SITE_RUNTIME_CONTRACT;
}
