import { state } from '../../state/app-state.v3963_1.js?v=3963_1';
import { resolveMajorQueryCandidates } from '../../knowledge/major-understanding-resolver.js?v=3949_0';
import { createSelectionPoolAdapter, refreshSelectionPool } from '../selection-pool/index.v3964_0.js?v=3964_0';

export const MAJOR_ALL_MODE_VERSION = 'major-all-mode-v002';
const API_PATH = '/api/ai/major-history';
const MODE = 'major-all';
const PAGE_SIZE = 40;
const selectionPool = createSelectionPoolAdapter();
const view = { data: null, loading: false, error: '', dirty: false, offset: 0, requestId: 0 };
let mounted = false;
let lockedConfirmed = [];
const DEFAULT_MAJOR_PLACEHOLDER = '先输入一个，如：电气、机械或计算机';
const ADD_MAJOR_PLACEHOLDER = '继续添加一个，如：测控、材料或软件';

function byId(id) { return document.getElementById(id); }
function text(value) { return String(value == null ? '' : value).trim(); }
function esc(value) { return text(value).replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c])); }
function inputValue() { return text(byId('majorKeyword')?.value || state.filters.majorKeyword); }
function scoreValue() { const raw = text(byId('candidateScore')?.value).replace(/[^0-9]/g,''); const n=Number(raw); return raw && Number.isFinite(n) && n>=150 && n<=750 ? Math.round(n) : null; }
function rawScorePresent() { return Boolean(text(byId('candidateScore')?.value)); }
function projectMode() { const v=text(byId('majorProjectMode')?.value||'all'); return ['all','ordinary-only','sino-only'].includes(v)?v:'all'; }
function regionValue() { return text(byId('region')?.value || state.filters.region || 'all') || 'all'; }
function schoolValue() { return text(byId('schoolKeyword')?.value || state.filters.schoolKeyword); }
function uniqueTerms(values=[]) { return [...new Set(values.flatMap(value => String(value || '').split(/[,，、/；;|]+/).map(item => item.trim()).filter(Boolean)))]; }
function draftMajorText() { return uniqueTerms([...lockedConfirmed, inputValue()]).join('/'); }
function setQueryUrl() { const url=new URL(location.href); if(state.resultMode===MODE) url.searchParams.set('mode',MODE); const q=draftMajorText(),score=text(byId('candidateScore')?.value).replace(/[^0-9]/g,''),region=regionValue(),school=schoolValue(),project=projectMode(); if(q) url.searchParams.set('majorKeyword',q); else url.searchParams.delete('majorKeyword'); if(score) url.searchParams.set('score',score); else url.searchParams.delete('score'); if(region&&region!=='all') url.searchParams.set('region',region); else url.searchParams.delete('region'); if(school) url.searchParams.set('school',school); else url.searchParams.delete('school'); if(project&&project!=='all') url.searchParams.set('projectMode',project); else url.searchParams.delete('projectMode'); history.replaceState(history.state,'',url.pathname+url.search+url.hash); }
function candidates() { return resolveMajorQueryCandidates(draftMajorText()); }
function selectedNames() { return candidates().items.filter(x=>x.status==='resolved').map(x=>x.name).filter(Boolean); }
function queryReady() { const r=candidates(); return r.ready && r.resolvedCodes.length>0; }
function candidateSummary(item) { if(item.status==='class-level') return '这是专业类/大类，请继续选择具体本科专业，不能静默代替具体查询。'; if(item.status==='unresolved') return '暂未在2026本科专业目录中确认，请换正式名称、简称或代码。'; return '请选择规范本科专业；确认后才会读取招生历史。'; }
function renderCandidates() {
  const root=byId('majorCandidatePanel'); if(!root)return; const r=candidates(),resolvedCount=r.items.filter(item=>item.status==='resolved').length;
  if(!r.terms.length){ root.innerHTML='<div class="major-candidate-empty">先输入一个专业方向；确认后可以继续添加第二个、第三个专业。也支持一次输入“机械/测控/材料”。</div>'; return; }
  const sections=r.items.map(item=>{
    if(item.status==='resolved') return `<div class="major-candidate-row is-resolved"><span class="major-candidate-term">${esc(item.input)}</span><b>${esc(item.name)}</b><small>已确认 · ${esc(item.code)}</small><button type="button" class="ui-button ui-button--compact ui-button--tertiary" data-major-remove-term="${esc(item.input)}">移除</button></div>`;
    const buttons=(item.candidates||[]).slice(0,8).map(c=>`<button type="button" class="major-candidate-choice" data-major-candidate-input="${esc(item.input)}" data-major-candidate-name="${esc(c.name)}"><b>${esc(c.name)}</b><small>${esc(c.code)}${c.matchType?` · ${esc(c.matchType)}`:''}</small></button>`).join('');
    return `<div class="major-candidate-row is-pending"><div><span class="major-candidate-term">${esc(item.input)}</span><p>${esc(candidateSummary(item))}</p></div><div class="major-candidate-choices">${buttons||'<span class="major-candidate-none">没有可安全确认的候选</span>'}</div></div>`;
  }).join('');
  const addAction=r.ready&&resolvedCount?'<button type="button" class="ui-button ui-button--compact ui-button--secondary major-candidate-add" data-major-add-another>＋再添加一个专业</button>':'';
  const title=resolvedCount?`已添加 ${resolvedCount} 个专业`:'先确认具体本科专业';
  const stateText=r.ready?'已全部确认；还可以继续添加。':'还有专业待确认，确认后才查询。';
  root.innerHTML=`<div class="major-candidate-head"><div><b>${title}</b><span>${stateText}</span></div><div class="major-candidate-actions">${addAction}<button type="button" class="ui-button ui-button--compact ui-button--tertiary" data-major-clear>清空专业</button></div></div>${sections}`;
}
function positionText(r){ const rawCandidate=view.data?.candidateScore; const candidate=Number(rawCandidate); if(rawCandidate===null||rawCandidate===undefined||!Number.isFinite(candidate)) return '未填写参考分数'; const distance=Number(r.positionDistance2026); if(Number.isFinite(distance)) return `参考${candidate}分 · 相差约${distance.toLocaleString('zh-CN')}位`; const target=Number(view.data?.candidateReferenceRank2026); if(Number.isFinite(target)) return `参考${candidate}分 · 参考位次约第${target.toLocaleString('zh-CN')}位`; return `参考${candidate}分 · 历史位次待核验`; }
function yearText(r,y){ const s=Number(r[`score${y}`]), k=Number(r[`rank${y}`]), hasScore=Number.isFinite(s)&&s>0, hasRank=Number.isFinite(k)&&k>0; if(!hasScore&&!hasRank) return '暂无严格同口径记录'; return `${hasScore?`${s}分`:'分数待核验'} · ${hasRank?`第${k.toLocaleString('zh-CN')}位`:'位次待核验'}`; }
function trendText(r){ const ks=[2024,2025,2026].map(y=>Number(r[`rank${y}`])).filter(value=>Number.isFinite(value)&&value>0); if(ks.length<2) return '数据不完整，不能判断三年趋势'; const d=ks.at(-1)-ks.at(-2); if(Math.abs(d)<=Math.max(500,ks.at(-2)*.025)) return '近两年最低投档位次基本稳定'; return d<0?'近两年最低投档所需位次相对靠前':'近两年最低投档所需位次相对靠后'; }
function recordKey(r){ return text(r.id)||[r.school,r.major,r.majorCode2026,r.score2026,r.rank2026].join('|'); }
function renderRecord(r){ const key=recordKey(r), on=selectionPool.has(r), project=r.projectLabel||(r.isSino?'中外合作/高收费（需核验）':'普通项目'), canonicalCode=r.standardMajorCode||r.majorCode2026; return `<article class="major-all-record" data-major-record-key="${esc(key)}" data-major-path-record data-workspace-record-key="${esc(key)}"><header class="major-all-record-head"><div><h3>${esc(r.school||'学校名称待核验')}</h3><p>${esc(r.displayLocation||'地域待核验')} · ${esc(r.major||'专业名称待核验')}</p></div><span class="major-all-project ${r.isSino?'is-sino':''}">${esc(project)}</span></header><div class="major-all-record-meta"><span>专业代码 ${esc(canonicalCode||'待核验')}</span><span>${esc(positionText(r))}</span><span>2026历史投档记录</span></div><div class="major-all-years" aria-label="三年同口径历史数据"><div><b>2026</b><span>${esc(yearText(r,2026))}</span></div><div><b>2025</b><span>${esc(yearText(r,2025))}</span></div><div><b>2024</b><span>${esc(yearText(r,2024))}</span></div></div><p class="major-all-trend"><b>趋势：</b>${esc(trendText(r))}。仅对当前学校、专业、项目记录做历史对照。</p><div class="major-all-record-actions"><button type="button" class="ui-button ui-button--compact ui-button--secondary" data-major-selection-action="${on?'remove':'add'}" data-major-record-key="${esc(key)}" aria-pressed="${on}">${on?'移出家庭方案':'加入家庭方案'}</button><button type="button" class="ui-button ui-button--compact ui-button--tertiary" data-major-school="${esc(r.school)}">看这所学校的在辽专业</button></div><p class="major-all-boundary">这是历史投档数据，不是录取承诺；学费、校区、合作办学条件以当年招生计划和院校章程为准。</p></article>`; }
function mergeRecords(a,b){ const m=new Map((a||[]).map(r=>[recordKey(r),r])); (b||[]).forEach(r=>m.set(recordKey(r),r)); return [...m.values()]; }
function syncSelectionButtons(){ byId('majorAllContent')?.querySelectorAll('[data-major-selection-action]').forEach(btn=>{const r=(view.data?.records||[]).find(x=>recordKey(x)===btn.dataset.majorRecordKey); if(!r)return; const on=selectionPool.has(r); btn.dataset.majorSelectionAction=on?'remove':'add'; btn.setAttribute('aria-pressed',String(on)); btn.textContent=on?'移出家庭方案':'加入家庭方案';}); }
function renderResults(){ const root=byId('majorAllContent'), panel=byId('majorAllResultsPanel'); if(!root||!panel)return; const active=state.resultMode===MODE; panel.hidden=!active; byId('resultsPanel')?.toggleAttribute('hidden',active); byId('schoolAllResultsPanel')?.toggleAttribute('hidden',active||state.resultMode!=='school-all'); if(!active)return; renderCandidates(); const names=selectedNames(); if(view.loading&&!view.data){root.innerHTML='<div class="ui-state ui-state--loading major-all-message"><b>正在读取专业招生历史…</b><p>先保留你已经输入的条件。</p></div>';return;} if(view.error&&!view.data){root.innerHTML=`<div class="ui-state ui-state--error major-all-message"><b>这次没有读取成功</b><p>${esc(view.error)}</p><button type="button" class="ui-button ui-button--compact ui-button--secondary" data-major-retry>重新读取</button></div>`;return;} if(!view.data){root.innerHTML=`<div class="ui-state ui-state--pending major-all-message"><b>${names.length?'确认后点击查看专业招生历史':'先输入一个或多个专业方向'}</b><p>${names.length?'可选填写分数、地区、学校关键词和普通/中外项目条件。':'例如：电气、机械/测控/材料；模糊输入必须先确认规范名称。'}</p></div>`;return;} const d=view.data,s=d.summary||{},records=Array.isArray(d.records)?d.records:[]; const hasCandidateScore=d.candidateScore!==null&&d.candidateScore!==undefined&&Number.isFinite(Number(d.candidateScore)); root.innerHTML=`<div class="major-all-summary"><b>${esc(names.join('、'))}</b><span>当前条件下 ${Number(s.schoolCount||0).toLocaleString('zh-CN')} 所学校 · ${Number(s.total||d.total||0).toLocaleString('zh-CN')} 条招生记录 · ${hasCandidateScore?`参考${Number(d.candidateScore)}分，按历史位次排序`:'未填写参考分数'} · ${d.projectMode==='sino-only'?'仅中外/高收费':d.projectMode==='ordinary-only'?'仅普通项目':'普通与中外分开显示'}</span><small>2026为主口径，2025/2024只在同一学校、专业和项目可以对应时展示。</small></div><div class="major-all-record-list">${records.map(renderRecord).join('')}</div>${d.nextOffset!=null?'<button type="button" class="ui-button ui-button--compact ui-button--secondary major-all-load-more" data-major-load-more>继续加载专业结果</button>':'<p class="major-all-complete">当前条件下的专业招生记录已全部加载完成。</p>'}`; syncSelectionButtons();document.dispatchEvent(new CustomEvent('gaokao:major-result-render')); }
function syncAction(){ if(state.resultMode!==MODE)return; const btn=byId('queryButton'), guide=byId('queryGuide'),ready=queryReady(),names=selectedNames(),invalid=rawScorePresent()&&scoreValue()===null; if(!btn)return; btn.disabled=Boolean(view.loading||!ready||invalid); if(view.loading){btn.textContent='正在读取专业招生历史…';btn.className='query-button is-loading';if(guide)guide.textContent='正在按已确认的专业、地区和项目条件读取数据。';}else if(!draftMajorText()){btn.textContent='先输入专业方向';btn.className='query-button is-waiting';if(guide)guide.textContent='先输入一个或多个专业方向；不填分数也可以查询。';}else if(!ready){btn.textContent='先确认具体本科专业';btn.className='query-button is-waiting';if(guide)guide.textContent='模糊输入会先出现候选，确认后才查询，专业类不会静默替换。';}else if(invalid){btn.textContent='分数需为150—750';btn.className='query-button is-waiting';if(guide)guide.textContent='分数可不填；填写时请输入150—750之间的整数。';}else if(view.error){btn.textContent='重新读取专业历史';btn.className='query-button is-error';if(guide)guide.textContent='读取异常，可以检查网络或稍后重试。';}else if(view.data&&view.dirty){btn.textContent='按新条件更新专业历史';btn.className='query-button is-ready';if(guide)guide.textContent='条件已变化，下面保留上一轮结果，确认后再更新。';}else{btn.textContent=`查询 ${names.length} 个已确认专业`;btn.className='query-button is-ready';if(guide)guide.textContent='可以继续添加专业；点击后一次查询全部已确认专业。';}}
function syncMode(){const active=state.resultMode===MODE;byId('majorCandidatePanel')?.toggleAttribute('hidden',!active);byId('majorAllResultsPanel')?.toggleAttribute('hidden',!active);byId('resultsPanel')?.toggleAttribute('hidden',active);byId('schoolAllResultsPanel')?.toggleAttribute('hidden',active||state.resultMode!=='school-all');byId('majorProjectMode')?.closest('.major-all-project-filter')?.toggleAttribute('hidden',!active);if(active){const params=new URLSearchParams(location.search),savedRegion=params.get('region'),savedProject=params.get('projectMode');if(savedRegion&&byId('region')){byId('region').value=savedRegion;state.filters.region=savedRegion;}if(savedProject&&byId('majorProjectMode'))byId('majorProjectMode').value=savedProject;renderCandidates();renderResults();syncAction();setQueryUrl();document.dispatchEvent(new CustomEvent('gaokao:major-filter-restored'));}}
async function load(append=false){if(state.resultMode!==MODE||!queryReady()){syncAction();return;}if(rawScorePresent()&&scoreValue()===null){syncAction();return;}const names=selectedNames(),id=++view.requestId,offset=append?Number(view.data?.nextOffset||0):0;view.loading=true;view.error='';view.dirty=false;renderResults();syncAction();try{const p=new URLSearchParams();names.forEach(n=>p.append('major',n));p.set('region',regionValue());p.set('schoolKeyword',schoolValue());p.set('projectMode',projectMode());p.set('bottomLineMode',state.filters.bottomLineMode||'all');p.set('sort',scoreValue()?'position-near':'score-desc');if(scoreValue()!==null)p.set('candidateScore',String(scoreValue()));p.set('offset',String(offset));p.set('limit',String(PAGE_SIZE));const response=await fetch(`${API_PATH}?${p.toString()}`,{headers:{accept:'application/json'}}),payload=await response.json();if(!response.ok||payload?.ok===false)throw new Error(payload?.message||'专业历史读取失败。');if(id!==view.requestId)return;view.data=append&&view.data?{...payload,records:mergeRecords(view.data.records,payload.records),nextOffset:payload.nextOffset}:payload;view.dirty=false;}catch(e){if(id!==view.requestId)return;view.error=e?.message||'专业历史读取失败。';}finally{if(id!==view.requestId)return;view.loading=false;renderResults();syncAction();refreshSelectionPool(state);}}
function markDirty(){state.filters.majorKeyword=draftMajorText();view.dirty=Boolean(view.data);renderCandidates();renderResults();syncAction();setQueryUrl();}
function bind(){byId('majorKeyword')?.addEventListener('input',()=>markDirty());byId('majorKeyword')?.addEventListener('focus',()=>{if(lockedConfirmed.length)byId('majorKeyword').placeholder=ADD_MAJOR_PLACEHOLDER;});byId('majorProjectMode')?.addEventListener('change',markDirty);byId('region')?.addEventListener('change',markDirty);byId('schoolKeyword')?.addEventListener('input',markDirty);byId('majorCandidatePanel')?.addEventListener('click',e=>{const field=byId('majorKeyword');if(e.target.closest('[data-major-add-another]')){lockedConfirmed=selectedNames();field.value='';state.filters.majorKeyword='';field.placeholder=ADD_MAJOR_PLACEHOLDER;markDirty();field.focus();return;}const remove=e.target.closest('[data-major-remove-term]');if(remove){const term=remove.dataset.majorRemoveTerm;lockedConfirmed=lockedConfirmed.filter(x=>x!==term);const next=uniqueTerms([inputValue()]).filter(x=>x!==term).join('/');field.value=next;if(!lockedConfirmed.length&& !next)field.placeholder=DEFAULT_MAJOR_PLACEHOLDER;state.filters.majorKeyword=next;markDirty();field.focus();return;}if(e.target.closest('[data-major-clear]')){lockedConfirmed=[];field.value='';state.filters.majorKeyword='';field.placeholder=DEFAULT_MAJOR_PLACEHOLDER;markDirty();field.focus();return;}const b=e.target.closest('[data-major-candidate-name]');if(!b)return;const term=b.dataset.majorCandidateInput,raw=inputValue(),parts=raw.split(/[,，、/；;|]+/).map(x=>x.trim()).filter(Boolean),replacement=b.dataset.majorCandidateName;let next=parts.map(x=>x===term?replacement:x).join('/');if(next===raw&&raw.includes(term)){const index=raw.indexOf(term);next=raw.slice(0,index)+replacement+raw.slice(index+term.length);}field.value=next;state.filters.majorKeyword=next;markDirty();field.focus();});byId('majorAllContent')?.addEventListener('click',e=>{const a=e.target.closest('[data-major-selection-action]');if(a){const r=(view.data?.records||[]).find(x=>recordKey(x)===a.dataset.majorRecordKey);if(!r)return;const out=a.dataset.majorSelectionAction==='remove'?selectionPool.remove(recordKey(r)):selectionPool.add(r);if(out?.changed!==false)refreshSelectionPool(state);syncSelectionButtons();return;}const school=e.target.closest('[data-major-school]');if(school){document.dispatchEvent(new CustomEvent('gaokao:view-school-all',{detail:{school:school.dataset.majorSchool}}));return;}if(e.target.closest('[data-major-load-more]'))load(true);if(e.target.closest('[data-major-retry]'))load(false);});document.addEventListener('gaokao:result-mode-change',syncMode);document.addEventListener('gaokao:major-action-sync',syncAction);document.addEventListener('gaokao:major-search-submit',()=>load(false));document.addEventListener('gaokao:workspace-state',e=>{if(e.detail?.mode===MODE){renderResults();syncAction();}});window.addEventListener('popstate',syncMode);}
export function mountMajorAllMode(){if(mounted)return globalThis.__GAOKAO_MAJOR_ALL_MODE__;mounted=true;bind();syncMode();const api=Object.freeze({version:MAJOR_ALL_MODE_VERSION,submit:()=>load(false),getState:()=>({...view})});globalThis.__GAOKAO_MAJOR_ALL_MODE__=api;return api;}
export const majorAllModeReady=Promise.resolve(mountMajorAllMode());
