
import {createAiWorkspace,applyAiWorkspaceEvent,compactAiWorkspaceForServer,AI_WORKSPACE_CONTRACT_VERSION,activeViewLabel} from '/shared/ai/ai-workspace-contract.v3992_0.js?v=3992_0';
import {node,renderAdvisor,renderProcessingTurn,updateProcessingTurn} from '/ai/render.v3992_0.js?v=3992_0';
import {starterScenariosForScore} from '/ai/parent-starter.v3992_1.js?v=3992_1';
const DB_NAME='gaokao-ai-workspace-v3990_0',STORE_NAME='workspace',WORKSPACE_KEY='current',SELECTION_POOL_KEY='lnRank.selectionPool.lnPhysics.2026.v3951';
let workspace=createAiWorkspace(),pendingCommand=null,pendingInput='',activeTurnController=null,activeTurnSequence=0,processingTimer=null;
const $=selector=>document.querySelector(selector),els={conversation:$('#conversationStream'),starter:$('#starterPanel'),starterScore:$('#starterScore'),starterScoreApply:$('#starterScoreApply'),starterScenarios:$('#starterScenarios'),activeViewBar:$('#activeViewBar'),activeViewChips:$('#activeViewChips'),currentContextTitle:$('#currentContextTitle'),form:$('#promptForm'),input:$('#promptInput'),send:$('#sendButton'),stop:$('#stopButton'),newWorkspace:$('#newWorkspace'),constraintList:$('#constraintList'),pendingList:$('#pendingList'),evidenceList:$('#evidenceList'),importSelection:$('#importSelection'),importStatus:$('#importStatus'),health:$('#healthBar'),modelConfig:$('#modelConfig'),modelProbeResult:$('#modelProbeResult'),probeModel:$('#probeModel'),exportWorkspace:$('#exportWorkspace'),confirmDialog:$('#confirmDialog'),confirmText:$('#confirmText'),confirmApply:$('#confirmApply')};
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE_NAME))db.createObjectStore(STORE_NAME);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function loadWorkspace(){try{const db=await openDb(),value=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readonly'),req=tx.objectStore(STORE_NAME).get(WORKSPACE_KEY);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});db.close();workspace=createAiWorkspace(value||{});if(value?.contractVersion!==AI_WORKSPACE_CONTRACT_VERSION)await saveWorkspace();}catch{workspace=createAiWorkspace();}}
async function saveWorkspace(){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).put(workspace,WORKSPACE_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}catch{}}
function onPrompt(prompt){els.input.value=prompt;executeTurn(prompt);}
function renderStarterScenarios(scoreValue=els.starterScore?.value||workspace?.examContext?.score){if(!els.starterScenarios)return;els.starterScenarios.replaceChildren();const score=Math.round(Number(scoreValue));if(els.starterScore&&Number.isFinite(score)&&score>=150&&score<=750)els.starterScore.value=String(score);const items=starterScenariosForScore(score);if(!items.length){els.starterScenarios.append(node('p','empty-note','先输入一个大概分数，我再按这个位置给你几种真实家长常见的思考入口。'));return;}for(const item of items){const button=node('button','starter-scenario');button.type='button';button.append(node('strong','',item.label));if(item.reason)button.append(node('span','',item.reason));button.addEventListener('click',()=>onPrompt(item.prompt));els.starterScenarios.append(button);}}
function render(){renderAdvisor(workspace,els,onPrompt);renderStarterScenarios();}
async function checkHealth(){try{const response=await fetch('/api/ai/health',{headers:{accept:'application/json'},cache:'no-store'}),data=await response.json();if(!response.ok||!data?.ok)throw new Error('health failed');const provider=data.provider||{},ready=Boolean(provider.primaryReady);els.health.className=`health-bar ${ready?'is-ok':'is-warn'}`;els.health.textContent=ready?'顾问可用：招生事实由确定性数据执行，AI负责理解任务、上下文和追问。':'确定性查询仍可用；语义模型当前未就绪。';els.modelConfig.textContent=`语义层：${provider.primary||'deterministic'} · ${provider.primaryModel||'本地规则'}`;}catch{els.health.className='health-bar is-warn';els.health.textContent='系统状态暂时不可读；已保存的本地讨论不会因此丢失。';els.modelConfig.textContent='语义模型状态暂不可读';}}
async function probeModel(){els.probeModel.disabled=true;els.probeModel.textContent='测试中…';els.modelProbeResult.textContent='正在发起一次最小真实模型调用…';try{const response=await fetch('/api/ai/model-probe',{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:'{}'}),data=await response.json(),actual=data.actual||{};if(!response.ok||!data.ok)throw new Error(data.note||data.failures?.[0]?.error||'模型探针失败');els.modelProbeResult.textContent=`实测：${actual.provider} · ${actual.model} · ${actual.latencyMs}ms${actual.fallbackUsed?' · 使用备用模型':''}`;}catch(error){els.modelProbeResult.textContent=`实测失败：${String(error?.message||error)}。确定性查询仍可继续。`;}finally{els.probeModel.disabled=false;els.probeModel.textContent='测试语义模型';}}
function setRunning(running){els.stop.hidden=!running;els.stop.textContent='停止本轮';els.send.textContent=running?'改口并发送':'发送';els.send.disabled=false;}
function clearProcessingTimer(){if(processingTimer){clearInterval(processingTimer);processingTimer=null;}}
function stopActiveTurn(reason=''){activeTurnSequence+=1;if(activeTurnController)activeTurnController.abort();activeTurnController=null;clearProcessingTimer();setRunning(false);render();if(reason)els.conversation.append(node('div','error-inline',reason));}
function taskIdForResult(taskAction){return taskAction==='branch'?workspace.tasks[0]?.id||workspace.mainTaskId:workspace.mainTaskId;}
function scrollToPending(){const pending=els.conversation.querySelector('[data-processing="true"]');if(pending)pending.scrollIntoView({block:'nearest',behavior:'smooth'});}
const AI_BRIDGE_RECORD_FIELDS=Object.freeze(['id','school','major','score2026','rank2026','schoolCode2026','majorCode2026','displayLocation','city','province','projectLabel','bandKey','band','scoreDelta2026','rankGap2026','is985','is211','isSinoForeign','isHighFee','feeType','natureLabel','tuition']);
function compactMajorBandsBridgeRecord(record={}){const out={};for(const key of AI_BRIDGE_RECORD_FIELDS){const value=record?.[key];if(value!==undefined&&value!==null&&value!=='')out[key]=value;}return out;}
function compactMajorBandsToolPayload(data={}){const band=key=>({count:Number(data?.bands?.[key]?.count||0),records:Array.isArray(data?.bands?.[key]?.records)?data.bands[key].records.slice(0,16).map(compactMajorBandsBridgeRecord):[]});return{ok:Boolean(data.ok),meta:data.meta||{},counts:data.counts||{},bands:{upper:band('upper'),near:band('near'),steady:band('steady')},searchAdvices:Array.isArray(data.searchAdvices)?data.searchAdvices.slice(0,8):[],filterConflicts:Array.isArray(data.filterConflicts)?data.filterConflicts.slice(0,8):[],keywordWarnings:Array.isArray(data.keywordWarnings)?data.keywordWarnings.slice(0,8):[],source:data.source||{}};}
const DETERMINISTIC_TRANSIENT_STATUSES=new Set([502,503,504]),DETERMINISTIC_RETRY_DELAYS=Object.freeze([300,900,2100]);
function deterministicRetryDelay(ms,signal){if(signal?.aborted)return Promise.reject(new DOMException('Aborted','AbortError'));return new Promise((resolve,reject)=>{const onAbort=()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'));},timer=setTimeout(()=>{signal?.removeEventListener('abort',onAbort);resolve();},ms);signal?.addEventListener('abort',onAbort,{once:true});});}
async function executeDeterministicTool(tool,controller){if(!tool||tool.kind!=='major_bands'||tool.method!=='GET'||typeof tool.key!=='string'||typeof tool.url!=='string'||tool.key!==tool.url||!tool.url.startsWith('/api/major-bands?'))throw new Error('确定性候选请求合同无效');let lastError=null;for(let attempt=0;attempt<=DETERMINISTIC_RETRY_DELAYS.length;attempt+=1){try{const response=await fetch(tool.url,{method:'GET',headers:{accept:'application/json'},cache:'no-store',signal:controller.signal}),payload=await response.json().catch(()=>null);if(response.ok&&payload?.ok){const compact=compactMajorBandsToolPayload(payload),bridgeBytes=new TextEncoder().encode(JSON.stringify(compact)).byteLength;if(bridgeBytes>80*1024)throw new Error('确定性候选桥接超过80KiB安全预算');return{kind:'major_bands',key:tool.key,url:tool.url,status:response.status,payload:compact};}const error=new Error(payload?.message||`候选事实查询失败（HTTP ${response.status}）`);error.status=response.status;if(!DETERMINISTIC_TRANSIENT_STATUSES.has(response.status)||attempt===DETERMINISTIC_RETRY_DELAYS.length)throw error;lastError=error;}catch(error){if(controller.signal.aborted)throw error;const status=Number(error?.status||0),retryable=status?DETERMINISTIC_TRANSIENT_STATUSES.has(status):error instanceof TypeError;if(!retryable||attempt===DETERMINISTIC_RETRY_DELAYS.length)throw error;lastError=error;}await deterministicRetryDelay(DETERMINISTIC_RETRY_DELAYS[attempt],controller.signal);}throw lastError||new Error('候选事实查询失败');}
async function executeTurn(input,confirmedCommand=null){
  const text=String(input||'').trim();if(!text&&!confirmedCommand)return;
  if(activeTurnController){activeTurnController.abort();clearProcessingTimer();}
  const sequence=++activeTurnSequence,controller=new AbortController();activeTurnController=controller;setRunning(true);
  render();
  const processing=renderProcessingTurn(els.conversation,text,activeViewLabel(workspace.activeView));const started=Date.now();
  processingTimer=setInterval(()=>{if(sequence!==activeTurnSequence)return;const elapsed=Date.now()-started;updateProcessingTurn(processing,{elapsedMs:elapsed,slow:elapsed>=2500});},1000);
  requestAnimationFrame(scrollToPending);
  try{
    let continuationCommand=confirmedCommand;const deterministicToolResults={};let data=null;
    for(let hop=0;hop<5;hop+=1){
      const response=await fetch('/api/ai/turn',{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({workspace:compactAiWorkspaceForServer(workspace),input:text,confirmedCommand:continuationCommand,deterministicToolResults}),signal:controller.signal});data=await response.json();
      if(sequence!==activeTurnSequence)return;
      if(!response.ok||!data?.ok)throw new Error(data?.message||'本轮没有完成');
      if(data.pendingConfirmation){clearProcessingTimer();render();pendingCommand=data.command;pendingInput=text;els.confirmText.textContent=data.command?.reason||'请再明确一下你的意思。';els.confirmDialog.showModal();return;}
      if(data.pendingDeterministicTool){const entry=await executeDeterministicTool(data.toolRequest,controller);deterministicToolResults[entry.key]=entry;continuationCommand=data.command;updateProcessingTurn(processing,{elapsedMs:Date.now()-started,slow:true});continue;}
      workspace=applyAiWorkspaceEvent(workspace,data.event);
      const turn=data.turnRecord||{userText:text,assistantSummary:(data.blocks||[]).map(item=>item.text).filter(Boolean).join(' '),changeSummary:data.result?.changeSummary||'',blocks:data.blocks||[],command:data.command,stage:data.result?.decisionStage||'start',task:data.command?.agentTask||'',focus:data.command?.focus||{}};
      workspace=applyAiWorkspaceEvent(workspace,{type:'result_committed',payload:{taskId:taskIdForResult(data.taskAction),result:data.result,turn}});
      await saveWorkspace();if(sequence!==activeTurnSequence)return;clearProcessingTimer();render();els.input.value='';requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}));return;
    }
    throw new Error('确定性事实工具链超过安全步数，本轮没有提交。');
  }catch(error){
    if(error?.name==='AbortError'||controller.signal.aborted)return;
    if(sequence===activeTurnSequence){clearProcessingTimer();render();els.conversation.append(node('div','error-inline',`这轮没有改动已有讨论：${String(error?.message||error)}`));}
  }finally{if(sequence===activeTurnSequence){clearProcessingTimer();activeTurnController=null;setRunning(false);}}
}
function selectionSnapshotFromStorage(){let parsed;try{const raw=localStorage.getItem(SELECTION_POOL_KEY);if(!raw)return{version:'ln-rank-selection-snapshot-v3992_0',items:[]};parsed=JSON.parse(raw);}catch{return{version:'ln-rank-selection-snapshot-v3992_0',items:[]};}const items=Array.isArray(parsed)?parsed:(Array.isArray(parsed?.items)?parsed.items:[]);return{version:'ln-rank-selection-snapshot-v3992_0',items:items.slice(0,112).map(item=>({id:String(item?.id||'').slice(0,220),school:String(item?.school||'').slice(0,120),major:String(item?.major||'').slice(0,180),score2026:Number.isFinite(Number(item?.score2026??item?.score))?Number(item.score2026??item.score):null,rank2026:Number.isFinite(Number(item?.rank2026??item.rank))?Number(item.rank2026??item.rank):null,bandKey:String(item?.bandKey||item?.band||'').slice(0,40),displayLocation:String(item?.displayLocation||'').slice(0,80),natureLabel:String(item?.natureLabel||'').slice(0,60),tuition:String(item?.tuition||'').slice(0,80),userNote:String(item?.userNote||'').slice(0,240)}))};}
els.form.addEventListener('submit',event=>{event.preventDefault();const text=els.input.value.trim();if(text)executeTurn(text);});els.input.addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();els.form.requestSubmit();}});for(const button of document.querySelectorAll('[data-prompt]'))button.addEventListener('click',()=>onPrompt(button.dataset.prompt||''));els.starterScoreApply?.addEventListener('click',()=>renderStarterScenarios(els.starterScore?.value));els.starterScore?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();renderStarterScenarios(els.starterScore.value);}});els.stop.addEventListener('click',()=>stopActiveTurn('已停止这轮；之前的讨论没有被覆盖。'));els.probeModel.addEventListener('click',probeModel);els.confirmApply.addEventListener('click',async()=>{if(!pendingCommand)return;els.confirmDialog.close();const command=pendingCommand,input=pendingInput;pendingCommand=null;pendingInput='';await executeTurn(input,command);});els.importSelection.addEventListener('click',async()=>{const snapshot=selectionSnapshotFromStorage();workspace=applyAiWorkspaceEvent(workspace,{type:'selection_snapshot_imported',payload:{snapshot}});await saveWorkspace();els.importStatus.textContent=snapshot.items.length?`已导入${snapshot.items.length}项，只读，不会改原方案。`:'当前浏览器没有可导入的2026家庭方案。';render();});els.newWorkspace.addEventListener('click',async()=>{if(!confirm('新开讨论会清空当前 AI 对话，但不会删除专业初选和家庭方案。继续吗？'))return;stopActiveTurn();workspace=createAiWorkspace();await saveWorkspace();render();});els.exportWorkspace.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gaokao-family-advisor-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
await loadWorkspace();render();checkHealth();