import {createAiWorkspace,applyAiWorkspaceEvent,compactAiWorkspaceForServer,AI_WORKSPACE_CONTRACT_VERSION} from '/shared/ai/ai-workspace-contract.v3991_0.js?v=3991_0';
import {node,renderAdvisor} from '/ai/render.v3991_0.js?v=3991_0';
const DB_NAME='gaokao-ai-workspace-v3990_0',STORE_NAME='workspace',WORKSPACE_KEY='current',SELECTION_POOL_KEY='lnRank.selectionPool.lnPhysics.2026.v3951';
let workspace=createAiWorkspace(),pendingCommand=null,pendingInput='',activeTurnController=null,activeTurnSequence=0;
const $=selector=>document.querySelector(selector),els={conversation:$('#conversationStream'),starter:$('#starterPanel'),activeViewBar:$('#activeViewBar'),activeViewChips:$('#activeViewChips'),currentContextTitle:$('#currentContextTitle'),form:$('#promptForm'),input:$('#promptInput'),send:$('#sendButton'),stop:$('#stopButton'),newWorkspace:$('#newWorkspace'),constraintList:$('#constraintList'),pendingList:$('#pendingList'),evidenceList:$('#evidenceList'),importSelection:$('#importSelection'),importStatus:$('#importStatus'),health:$('#healthBar'),modelConfig:$('#modelConfig'),modelProbeResult:$('#modelProbeResult'),probeModel:$('#probeModel'),exportWorkspace:$('#exportWorkspace'),confirmDialog:$('#confirmDialog'),confirmText:$('#confirmText'),confirmApply:$('#confirmApply')};
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE_NAME))db.createObjectStore(STORE_NAME);};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function loadWorkspace(){try{const db=await openDb(),value=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readonly'),req=tx.objectStore(STORE_NAME).get(WORKSPACE_KEY);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});db.close();workspace=createAiWorkspace(value||{});if(value?.contractVersion!==AI_WORKSPACE_CONTRACT_VERSION)await saveWorkspace();}catch{workspace=createAiWorkspace();}}
async function saveWorkspace(){try{const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).put(workspace,WORKSPACE_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});db.close();}catch{}}
function onPrompt(prompt){els.input.value=prompt;executeTurn(prompt);}
function render(){renderAdvisor(workspace,els,onPrompt);}
async function checkHealth(){try{const response=await fetch('/api/ai/health',{headers:{accept:'application/json'},cache:'no-store'}),data=await response.json();if(!response.ok||!data?.ok)throw new Error('health failed');const provider=data.provider||{},ready=Boolean(provider.primaryReady);els.health.className=`health-bar ${ready?'is-ok':'is-warn'}`;els.health.textContent=ready?'顾问可用：招生事实由确定性数据执行，AI只负责理解上下文和追问。':'确定性查询仍可用；语义模型当前未就绪。';els.modelConfig.textContent=`语义层：${provider.primary||'deterministic'} · ${provider.primaryModel||'本地规则'}`;}catch{els.health.className='health-bar is-warn';els.health.textContent='系统状态暂时不可读；已保存的本地讨论不会因此丢失。';els.modelConfig.textContent='语义模型状态暂不可读';}}
async function probeModel(){els.probeModel.disabled=true;els.probeModel.textContent='测试中…';els.modelProbeResult.textContent='正在发起一次最小真实模型调用…';try{const response=await fetch('/api/ai/model-probe',{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:'{}'}),data=await response.json(),actual=data.actual||{};if(!response.ok||!data.ok)throw new Error(data.note||data.failures?.[0]?.error||'模型探针失败');els.modelProbeResult.textContent=`实测：${actual.provider} · ${actual.model} · ${actual.latencyMs}ms${actual.fallbackUsed?' · 使用备用模型':''}`;}catch(error){els.modelProbeResult.textContent=`实测失败：${String(error?.message||error)}。确定性查询仍可继续。`;}finally{els.probeModel.disabled=false;els.probeModel.textContent='测试语义模型';}}
function setRunning(running){els.stop.hidden=!running;els.send.textContent=running?'改口并发送':'发送';els.send.disabled=false;}
function stopActiveTurn(reason=''){activeTurnSequence+=1;if(activeTurnController)activeTurnController.abort();activeTurnController=null;setRunning(false);if(reason)els.conversation.append(node('div','error-inline',reason));}
function taskIdForResult(taskAction){return taskAction==='branch'?workspace.tasks[0]?.id||workspace.mainTaskId:workspace.mainTaskId;}
async function executeTurn(input,confirmedCommand=null){const text=String(input||'').trim();if(!text&&!confirmedCommand)return;if(activeTurnController)activeTurnController.abort();const sequence=++activeTurnSequence,controller=new AbortController();activeTurnController=controller;setRunning(true);try{const response=await fetch('/api/ai/turn',{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({workspace:compactAiWorkspaceForServer(workspace),input:text,confirmedCommand}),signal:controller.signal}),data=await response.json();if(sequence!==activeTurnSequence)return;if(!response.ok||!data?.ok)throw new Error(data?.message||'本轮没有完成');if(data.pendingConfirmation){pendingCommand=data.command;pendingInput=text;els.confirmText.textContent=data.command?.reason||'请再明确一下你的意思。';els.confirmDialog.showModal();return;}workspace=applyAiWorkspaceEvent(workspace,data.event);const turn=data.turnRecord||{userText:text,assistantSummary:(data.blocks||[]).map(item=>item.text).filter(Boolean).join(' '),changeSummary:data.result?.changeSummary||'',blocks:data.blocks||[],command:data.command,stage:data.result?.decisionStage||'start'};workspace=applyAiWorkspaceEvent(workspace,{type:'result_committed',payload:{taskId:taskIdForResult(data.taskAction),result:data.result,turn}});await saveWorkspace();if(sequence!==activeTurnSequence)return;render();els.input.value='';requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}));}catch(error){if(error?.name==='AbortError'||controller.signal.aborted)return;if(sequence===activeTurnSequence)els.conversation.append(node('div','error-inline',`这轮没有改动已有讨论：${String(error?.message||error)}`));}finally{if(sequence===activeTurnSequence){activeTurnController=null;setRunning(false);}}}
function selectionSnapshotFromStorage(){let parsed;try{const raw=localStorage.getItem(SELECTION_POOL_KEY);if(!raw)return{version:'ln-rank-selection-snapshot-v3991_0',items:[]};parsed=JSON.parse(raw);}catch{return{version:'ln-rank-selection-snapshot-v3991_0',items:[]};}const items=Array.isArray(parsed)?parsed:(Array.isArray(parsed?.items)?parsed.items:[]);return{version:'ln-rank-selection-snapshot-v3991_0',items:items.slice(0,112).map(item=>({id:String(item?.id||'').slice(0,220),school:String(item?.school||'').slice(0,120),major:String(item?.major||'').slice(0,180),score2026:Number.isFinite(Number(item?.score2026??item?.score))?Number(item.score2026??item.score):null,rank2026:Number.isFinite(Number(item?.rank2026??item?.rank))?Number(item.rank2026??item.rank):null,bandKey:String(item?.bandKey||item?.band||'').slice(0,40),displayLocation:String(item?.displayLocation||'').slice(0,80),natureLabel:String(item?.natureLabel||'').slice(0,60),tuition:String(item?.tuition||'').slice(0,80),userNote:String(item?.userNote||'').slice(0,240)}))};}
els.form.addEventListener('submit',event=>{event.preventDefault();const text=els.input.value.trim();if(text)executeTurn(text);});els.input.addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();els.form.requestSubmit();}});for(const button of document.querySelectorAll('[data-prompt]'))button.addEventListener('click',()=>onPrompt(button.dataset.prompt||''));els.stop.addEventListener('click',()=>stopActiveTurn('已停止这轮；之前的讨论没有被覆盖。'));els.probeModel.addEventListener('click',probeModel);els.confirmApply.addEventListener('click',async()=>{if(!pendingCommand)return;els.confirmDialog.close();const command=pendingCommand,input=pendingInput;pendingCommand=null;pendingInput='';await executeTurn(input,command);});els.importSelection.addEventListener('click',async()=>{const snapshot=selectionSnapshotFromStorage();workspace=applyAiWorkspaceEvent(workspace,{type:'selection_snapshot_imported',payload:{snapshot}});await saveWorkspace();els.importStatus.textContent=snapshot.items.length?`已导入${snapshot.items.length}项，只读，不会改原方案。`:'当前浏览器没有可导入的2026家庭方案。';render();});els.newWorkspace.addEventListener('click',async()=>{if(!confirm('新开讨论会清空当前 AI 对话，但不会删除专业初选和家庭方案。继续吗？'))return;stopActiveTurn();workspace=createAiWorkspace();await saveWorkspace();render();});els.exportWorkspace.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(workspace,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gaokao-family-advisor-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
await loadWorkspace();render();checkHealth();
