
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function badge(ok){return `<span class="status ${ok?'ok':'bad'}">${ok?'通过':'失败'}</span>`}
function row(x){return `<div class="case"><h3>${esc(x.name)} ${badge(x.ok)}</h3><div class="muted">${esc(x.detail||'')}</div>${x.suggestion?`<div class="mono">建议：${esc(x.suggestion)}</div>`:''}</div>`}
async function text(path){const r=await fetch(path,{cache:'no-store'}); if(!r.ok) throw new Error(path+' '+r.status); return await r.text()}
async function exists(path){try{const r=await fetch(path,{cache:'no-store'}); const t=await r.text(); return {ok:r.ok && !/^\s*</.test(t) || path.endsWith('.html'), text:t, status:r.status}}catch(e){return {ok:false,text:String(e),status:0}}}
function importSpecs(js){return [...js.matchAll(/(?:import|export)\s+(?:[^'\"]*?from\s*)?['\"]([^'\"]+\.js(?:\?v=[^'\"]+)?)['\"]/g)].map(m=>m[1])}
function resolve(base,spec){let clean=spec.replace(/\?.*$/,''); const stack=base.split('/'); stack.pop(); for(const part of clean.split('/')){if(!part||part==='.'){continue}else if(part==='..'){stack.pop()}else{stack.push(part)}} return stack.join('/')}
function badWords(s){return ['NaN','undefined','null','[object Object]','payload','raw','source','debug','model','JSON','workers-ai','fallback','AI_PATH_MODEL','稳进','必录','保证','一定能上','闭眼报','稳赚','捡漏'].filter(w=>String(s||'').includes(w))}
async function runManifest(){const checks=[];let manifest;try{manifest=JSON.parse(await text('./active-assets.json'));checks.push({name:'ASSET-001：active-assets 可读取',ok:true,detail:manifest.version+' / '+manifest.assetVersion})}catch(e){checks.push({name:'ASSET-001：active-assets 可读取',ok:false,detail:String(e)});return checks}
for(const p of [...manifest.html,...manifest.jsEntry,...manifest.cssEntry,...manifest.stableModules]){const e=await exists('./'+p);checks.push({name:'ASSET：'+p,ok:e.ok,detail:e.ok?'存在且没有返回 fallback HTML':'缺失或返回 HTML：'+e.status})}
for(const p of manifest.cssEntry||[]){const t=await text('./'+p).catch(e=>'');checks.push({name:'CSS-NONEMPTY：'+p,ok:String(t).trim().length>20,detail:String(t).trim().length>20?'非空':'CSS 为空或过短'})}
const missing=[];for(const entry of manifest.jsEntry||[]){const js=await text('./'+entry).catch(e=>'');for(const spec of importSpecs(js)){const target=resolve(entry,spec);if(spec.includes('major-bands-response-normalizer'))missing.push('禁止 active 依赖：'+spec);const r=await exists('./'+target);if(!r.ok)missing.push(entry+' -> '+spec+' => '+target)}}checks.push({name:'IMPORT-001：active JS import 递归入口检查',ok:!missing.length,detail:missing.length?missing.slice(0,12).join(' / '):'未发现 active import 缺失或 wrapper 依赖'});
for(const page of ['index.html','selection-pool.html']){const t=await text('./'+page).catch(e=>'');const bad=badWords(t);checks.push({name:'COPY-'+page+'：主页面禁词与坏值',ok:!bad.length,detail:bad.length?bad.join('、'):'未发现主路径禁词或坏值'});}

const indexText=await text('./index.html').catch(e=>'');
checks.push({name:'GUIDE-001：存在“孩子高考分数”',ok:indexText.includes('孩子高考分数'),detail:indexText.includes('孩子高考分数')?'已使用新手文案':'仍是系统化分数文案'});
checks.push({name:'GUIDE-002：存在“先看多大范围”',ok:indexText.includes('先看多大范围'),detail:indexText.includes('先看多大范围')?'已使用范围引导':'查看范围文案仍偏工具化'});
checks.push({name:'GUIDE-003：存在“想看什么方向”',ok:indexText.includes('想看什么方向'),detail:indexText.includes('想看什么方向')?'已使用方向引导':'搜索条件文案仍偏系统化'});
checks.push({name:'GUIDE-004：主按钮不叫“更新条件”',ok:!indexText.includes('更新条件'),detail:!indexText.includes('更新条件')?'未发现旧按钮文案':'仍存在“更新条件”'});
checks.push({name:'LAYOUT-HEAT-001：热度提示不在主按钮之前',ok:indexText.indexOf('filter-action search-action-row') < indexText.indexOf('majorTrendHint'),detail:indexText.indexOf('filter-action search-action-row') < indexText.indexOf('majorTrendHint')?'主按钮在热度提示之前':'热度提示仍在主按钮之前'});
checks.push({name:'LAYOUT-HEAT-002：热度提示使用独立横向摘要类',ok:indexText.includes('ln-heat-summary-row'),detail:indexText.includes('ln-heat-summary-row')?'热度已作为独立摘要行':'缺少热度摘要行 class'});
checks.push({name:'SPECIAL-001：存在特殊项目默认隐藏控件',ok:indexText.includes('specialProjectPanel'),detail:indexText.includes('specialProjectPanel')?'搜索页已提供特殊项目状态条':'缺少特殊项目状态条'});
checks.push({name:'SPECIAL-002：默认隐藏专项/定向/预科文案',ok:indexText.includes('已默认隐藏专项、定向、预科'),detail:indexText.includes('已默认隐藏专项、定向、预科')?'默认隐藏文案存在':'缺少默认隐藏说明'});
checks.push({name:'SPECIAL-003：active-assets 包含特殊项目策略',ok:(manifest.stableModules||[]).includes('js/domain/special-project-policy.js'),detail:(manifest.stableModules||[]).includes('js/domain/special-project-policy.js')?'special-project-policy 已纳入稳定模块':'stableModules 缺少 special-project-policy'});
checks.push({name:'SPECIAL-004：active CSS 包含特殊项目样式',ok:(manifest.cssEntry||[]).includes('css/components/special-project-filter.css'),detail:(manifest.cssEntry||[]).includes('css/components/special-project-filter.css')?'特殊项目样式已纳入 active CSS':'active CSS 缺少 special-project-filter.css'});

const poolControllerText=await text('./js/feature/selection-pool/controller.js').catch(e=>'');
const poolMobileCss=await text('./css/components/selection-pool-mobile-entry.css').catch(e=>'');
checks.push({name:'POOL-MOBILE-001：Android 不显示右下固定自选入口',ok:poolMobileCss.includes('.selection-pool-shell.pool-entry-direct-shell') && poolMobileCss.includes('> .pool-entry-direct'),detail:'手机端保留 toast shell、隐藏桌面固定入口'});
checks.push({name:'POOL-MOBILE-002：添加成功后存在可点击气泡',ok:poolControllerText.includes('pool-entry-action-toast') && poolControllerText.includes('pool-entry-toast-action'),detail:poolControllerText.includes('pool-entry-action-toast')?'已使用操作型气泡':'仍是纯文字 toast'});
checks.push({name:'POOL-MOBILE-003：气泡包含“去整理”链接',ok:poolControllerText.includes('>去整理</a>'),detail:poolControllerText.includes('>去整理</a>')?'气泡包含跳转入口':'缺少去整理入口'});
checks.push({name:'POOL-MOBILE-004：气泡自动关闭时间在 3-5 秒之间',ok:poolControllerText.includes('Date.now() + 3800') && poolControllerText.includes('3900'),detail:'目标停留时间 3.8 秒，3.9 秒清理'});
checks.push({name:'POOL-MOBILE-005：结果区自选状态行不是 sticky',ok:poolMobileCss.includes('position: static !important') && !poolMobileCss.includes('position: sticky'),detail:poolMobileCss.includes('position: static !important')?'自选状态行已降为静态轻提示':'仍可能 sticky 遮挡结果'});
checks.push({name:'POOL-MOBILE-006：toast 允许点击',ok:poolMobileCss.includes('pointer-events: auto !important'),detail:poolMobileCss.includes('pointer-events: auto !important')?'气泡允许点击':'toast 仍不可点击'});
checks.push({name:'POOL-MOBILE-007：toast 链接没有被隐藏',ok:poolMobileCss.includes('display: inline-flex !important') && poolMobileCss.includes('.pool-entry-toast-action'),detail:'新 CSS 覆盖旧 display:none 规则'});

return checks}
function renderClientChecks(checks){const root=document.getElementById('clientChecks')||document.getElementById('uiChecks');if(root)root.innerHTML=(checks||[]).map(row).join('')}
async function run(){const overall=document.getElementById('overallBadge');overall.className='status warn';overall.textContent='正在自测…';const client=await runManifest();try{const res=await fetch('/api/ln-rank-self-check',{cache:'no-store'});const data=await res.json();document.getElementById('versionBox').textContent=JSON.stringify({version:data.version,catalog:data.catalog,policyLine:data.policyLine,clientChecks:client.length},null,2);document.getElementById('cases').innerHTML=(data.cases||[]).map(c=>row({name:c.input,ok:c.ok,detail:`方向：${c.direction||'—'}｜项目：${c.project||'—'}｜代码：${c.code||'—'}`})).join('');document.getElementById('reports').innerHTML=(data.reports||[]).map(r=>row({name:r.name,ok:r.ok,detail:'长度/块数：'+(r.length||'—')})).join('');document.getElementById('uiChecks').innerHTML=[...(data.uiChecks||[]),...client].map(x=>row({name:x.name,ok:x.ok,detail:x.detail,suggestion:x.suggestion})).join('');document.getElementById('errors').textContent=(data.errors&&data.errors.length)?data.errors.join('\n'):'暂无。';const ok=Boolean(data.ok)&&client.every(x=>x.ok);overall.className='status '+(ok?'ok':'bad');overall.textContent=ok?'全部通过':'存在失败'}catch(e){document.getElementById('errors').textContent=String(e?.stack||e);renderClientChecks(client);overall.className='status '+(client.every(x=>x.ok)?'ok':'bad');overall.textContent=client.every(x=>x.ok)?'客户端检查通过，接口未返回':'自测接口或客户端检查失败'}}
document.getElementById('runSelfCheck')?.addEventListener('click',run);run();console.info('v3.9.20.5 移动端自选操作气泡自测：active manifest、import、CSS、文案坏值、新手流程、主按钮与热度顺序检查已启用。');
