const VERSION='v3.9.57.0';
const ASSET='v3957_0';
const $=id=>document.getElementById(id);
const row=(name,ok,detail='')=>({name,ok,detail});
async function json(path){const response=await fetch(path,{cache:'no-store'});const text=await response.text();let data={};try{data=JSON.parse(text||'{}');}catch{throw new Error(`${path} 返回的不是 JSON`);}if(!response.ok)throw new Error(data.message||`${path} HTTP ${response.status}`);return data;}
function renderList(id,items){const root=$(id);if(!root)return;root.innerHTML=items.map(item=>`<div class="self-check-row ${item.ok?'is-ok':'is-bad'}"><b>${item.ok?'✅':'❌'} ${item.name}</b><p>${item.detail||''}</p></div>`).join('')||'<div class="self-check-row">暂无结果</div>';}
function overall(items){const bad=items.filter(item=>!item.ok);const badge=$('overallBadge');badge.className=`status ${bad.length?'bad':'ok'}`;badge.textContent=bad.length?`未通过 ${bad.length} 项`:'自测通过';$('errors').textContent=bad.length?bad.map(item=>`${item.name}: ${item.detail}`).join('\n'):'暂无。';}
async function main(){const checks=[];try{const [active,release,health,self]=await Promise.all([json('/ln-rank/active-assets.json?v=3957_0'),json('/ln-rank/release-meta.json?v=3957_0'),json('/api/feishu-report-health'),json('/api/ln-rank-self-check?v=3957_0')]);checks.push(row('活动资源版本',active.version===VERSION&&active.assetVersion===ASSET,`${active.version} / ${active.assetVersion}`));checks.push(row('发布合同版本',release.version===VERSION&&release.assetVersion===ASSET,`${release.version} / ${release.assetVersion}`));checks.push(row('飞书共享路由',health.ok&&health.dataYear===2026&&health.routes?.currentBand&&health.routes?.selectionPool,JSON.stringify(health.routes||{})));checks.push(row('三处报告构建',self.ok&&Array.isArray(self.reports)&&self.reports.filter(item=>item.name!=='复制文字版/样式块').length===3,(self.reports||[]).map(item=>`${item.name}:${item.ok?'通过':'失败'}`).join('｜')));renderList('reports',(self.reports||[]).map(item=>row(item.name,Boolean(item.ok),(item.errors||[]).join('；')||`长度 ${item.length||0}`)));renderList('cases',(self.cases||[]).map(item=>row(item.input||item.name,Boolean(item.ok),(item.errors||[]).join('；')||'通过')));renderList('uiChecks',(self.uiChecks||[]).map(item=>row(item.name,Boolean(item.ok),item.detail||'')));$('versionBox').textContent=`${active.version} / ${active.assetVersion} / ${release.releaseName||release.release||''}`;}catch(error){checks.push(row('自测执行',false,error?.message||String(error)));}overall(checks);}
document.addEventListener('DOMContentLoaded',()=>$('runSelfCheck')?.addEventListener('click',main));
