import { MAJOR_CATALOG_2026 } from '../kb/major-understanding/major-catalog-2026.generated.js';
import { createMajorCatalogResolver, normalizeMajorCode } from '../../shared/resources/majors/major-catalog-contract.js';

const RELEASE='v016.59-r149';
const STORAGE_KEY='gaokao:simulation-report:v002';
const LEGACY_STORAGE_KEY='gaokao:simulation-report:v001';
const API={rank:'/api/simulation-rank',history:'/api/ai/major-history'};
const FAMILY=['继续考虑','候选','还没决定','排除'];
const MANUAL_CHECK=['institutionCode','groupCode','campus','studyLocation','tuition','accommodationFee','planCount','studyLength','trainingMode','subjectRequirement','remark'];
const resolver=createMajorCatalogResolver(MAJOR_CATALOG_2026);
const norm=v=>String(v??'').normalize('NFKC').replace(/\u00a0/g,' ').trim();
const lower=v=>norm(v).toLowerCase();
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const formatRank=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?n.toLocaleString('zh-CN'):'—'};
const emptyManual=()=>Object.fromEntries(MANUAL_CHECK.map(k=>[k,'']));
const createVolunteer=order=>({id:`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,order,school:'',confirmedSchool:'',majorCode:'',majorName:'',history:{years:{}},error:'',manualCheck:emptyManual(),familyDecision:'',familyStatus:'',familyNote:''});
const defaults=()=>({version:2,studentName:'',subjectTrack:'辽宁物理类（物化生）',totalScore:'',scores:{chinese:'',math:'',english:'',physics:'',chemistry:'',biology:''},rank:null,volunteers:[createVolunteer(1)]});
function stored(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
function normalizeVolunteer(row,index){const x=createVolunteer(index+1);const oldFamily=norm(row?.familyStatus);const familyMap={'待讨论':'还没决定','保留':'继续考虑','备选':'候选','已排除':'排除','删除':'排除'};const mappedFamily=familyMap[oldFamily]||oldFamily;return {...x,...row,order:index+1,confirmedSchool:norm(row?.confirmedSchool),manualCheck:{...emptyManual(),...(row?.manualCheck||{})},familyStatus:FAMILY.includes(mappedFamily)?mappedFamily:'',familyDecision:typeof row?.familyDecision==='string'?row.familyDecision:'',familyNote:typeof row?.familyNote==='string'?row.familyNote:''};}
function loadState(){const parsed=stored(STORAGE_KEY)||stored(LEGACY_STORAGE_KEY);if(!parsed||!Array.isArray(parsed.volunteers))return defaults();const d=defaults();return {...d,...parsed,version:2,scores:{...d.scores,...(parsed.scores||{})},volunteers:parsed.volunteers.length?parsed.volunteers.map(normalizeVolunteer):[createVolunteer(1)]};}
function serializable(s){return {...s,version:2,volunteers:s.volunteers.map((r,i)=>({...r,order:i+1,manualCheck:{...emptyManual(),...(r.manualCheck||{})}}))};}
function createStore(){let state=loadState();const listeners=new Set();return {get:()=>state,commit(fn,notify=true){state=fn(state);localStorage.setItem(STORAGE_KEY,JSON.stringify(serializable(state)));if(notify)listeners.forEach(f=>f(state));},update(fn){this.commit(fn,true)},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}};}
const store=createStore();
const runtime={version:RELEASE,store,worker:null,workerSeq:0,pending:new Map(),schoolTimers:new Map(),factControllers:new Map(),rankController:null,historyCache:new Map(),expanded:new Set(),initialized:false};
function row(id){return store.get().volunteers.find(r=>String(r.id)===String(id))}
function patchRow(id,patch,render=true){store.commit(s=>({...s,volunteers:s.volunteers.map(r=>String(r.id)===String(id)?{...r,...patch}:r)}),render)}
function showToast(text){document.querySelector('.sim-toast')?.remove();const el=document.createElement('div');el.className='sim-toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),2400)}
function status(r){if(!r.school)return ['incomplete','先填写学校'];if(!r.confirmedSchool||lower(r.confirmedSchool)!==lower(r.school))return ['needs-check','学校还没有确认'];if(!r.majorCode)return ['incomplete','再填写专业'];if(!r.majorName)return ['needs-check','专业还没有确认'];return ['complete','当前记录可以继续整理'];}
function historyText(h,y){const x=h?.years?.[y];if(!x||(x.score==null&&x.rank==null))return '无严格记录';return `${x.score==null?'—':x.score+'分'} / ${x.rank==null?'—':formatRank(x.rank)+'位'}`}
function delta(r){const a=Number(r?.history?.years?.[2026]?.rank),b=Number(store.get().rank);if(!Number.isFinite(a)||!Number.isFinite(b)||b<=0)return '—';const d=a-b;return d===0?'同位次':`${d>0?'+':''}${d.toLocaleString('zh-CN')}名`}
function manualField(key,label,r){const value=esc(r.manualCheck?.[key]||'');const control=key==='remark'?`<textarea data-detail-field="${key}" data-id="${esc(r.id)}" rows="2">${value}</textarea>`:`<input data-detail-field="${key}" data-id="${esc(r.id)}" value="${value}" />`;return `<label class="manual-field"><span>${esc(label)}</span>${control}</label>`}
function cardHtml(r,i,total){const [kind,label]=status(r),open=runtime.expanded.has(String(r.id)),family=FAMILY.includes(r.familyStatus)?r.familyStatus:'还没决定';return `<article class="volunteer-card" data-card-id="${esc(r.id)}"><div class="volunteer-top"><div class="order-badge">${i+1}</div><div class="card-field"><label>学校</label><input data-field="school" data-id="${esc(r.id)}" value="${esc(r.school)}" placeholder="输入学校名称" autocomplete="off" /></div><div class="card-field"><label>专业</label><input data-field="majorCode" data-id="${esc(r.id)}" value="${esc(r.majorCode)}" placeholder="输入专业名称或代码" autocomplete="off" inputmode="text" /><div class="major-caption">${esc(r.majorName||'先选择学校，再确认专业')}</div><div class="input-helper" data-helper-id="${esc(r.id)}"></div></div><div class="card-tools"><button type="button" data-action="up" data-id="${esc(r.id)}" ${i===0?'disabled':''}>↑ 上移</button><button type="button" data-action="down" data-id="${esc(r.id)}" ${i===total-1?'disabled':''}>↓ 下移</button><button type="button" data-action="delete" data-id="${esc(r.id)}">删除</button></div></div><div class="candidate-slot" data-candidate-slot="${esc(r.id)}"></div><div class="history-inline"><span>2026 ${historyText(r.history,2026)}</span><span>2025 ${historyText(r.history,2025)}</span><span>2024 ${historyText(r.history,2024)}</span><span>相对当前 ${esc(delta(r))}</span></div><div class="state-line ${kind}"><span>${esc(label)}</span><button type="button" data-action="detail" data-id="${esc(r.id)}">${open?'收起核对':'展开核对'}</button></div>${open?`<section class="detail-panel"><div class="detail-grid">${manualField('institutionCode','院校代码',r)}${manualField('groupCode','专业组/招生代码',r)}${manualField('campus','校区',r)}${manualField('studyLocation','实际培养地点',r)}${manualField('tuition','学费',r)}${manualField('accommodationFee','住宿费',r)}${manualField('planCount','2026招生计划',r)}${manualField('studyLength','学制',r)}${manualField('trainingMode','培养方式',r)}${manualField('subjectRequirement','选科要求',r)}${manualField('remark','专业备注/特殊限制',r)}</div><p>这些是你们自己的核对记录；空白不代表官方资料不存在。</p></section>`:''}<div class="family-decision"><span>这所学校怎么处理？</span>${FAMILY.map(x=>`<button type="button" data-family="${esc(x)}" data-id="${esc(r.id)}" aria-pressed="${family===x?'true':'false'}">${esc(x)}</button>`).join('')}</div>${r.familyNote?`<div class="family-note">备注：${esc(r.familyNote)}</div>`:''}</article>`;}
function renderMeta(s){const name=document.querySelector('#wbStudentName'),subject=document.querySelector('#wbSubject'),score=document.querySelector('#wbTotalScore'),rank=document.querySelector('#wbRank'),src=document.querySelector('#wbRankSource');if(name)name.value=s.studentName||'';if(subject)subject.value=s.subjectTrack||'辽宁物理类（物化生）';if(score&&document.activeElement!==score)score.value=s.totalScore||'';if(rank)rank.textContent=formatRank(s.rank);if(src)src.textContent=s.rank?'2026辽宁物理类官方成绩统计口径':'输入总分后自动换算';}
function render(){const s=store.get();renderMeta(s);const list=document.querySelector('#wbRows');if(!list)return;const summary=document.querySelector('#wbSummary');if(summary){const counts=s.volunteers.reduce((a,r)=>{const k=status(r)[0];k==='complete'?a.complete++:k==='needs-check'?a.check++:a.incomplete++;return a},{complete:0,check:0,incomplete:0});summary.innerHTML=`<span>共 ${s.volunteers.length} 条</span><span>✓ ${counts.complete} 条可继续整理</span><span>⚠ ${counts.check} 条待确认</span><span>○ ${counts.incomplete} 条未完成</span>`;}list.innerHTML=s.volunteers.map((r,i)=>cardHtml(r,i,s.volunteers.length)).join('');const empty=document.querySelector('#wbEmpty');if(empty)empty.hidden=s.volunteers.length>0;const st=document.querySelector('#wbStatus');if(st)st.textContent=s.volunteers.length?'学校、专业可以逐条补；家庭处理可以随时修改。':'先加入一所已经考虑过的学校即可。';}
function slot(id,html){const el=document.querySelector(`[data-candidate-slot="${CSS.escape(String(id))}"]`);if(el)el.innerHTML=html;}
function helper(id,text,tone='neutral'){const el=document.querySelector(`[data-helper-id="${CSS.escape(String(id))}"]`);if(el){el.textContent=text;el.dataset.tone=tone;}}
function candidatesHtml(kind,items,rowId){if(!items.length)return `<div class="candidate-empty">暂未找到合适候选，请继续输入。</div>`;return `<div class="candidate-title">${kind==='school'?'找到以下学校，请选择正确的一所':'专业目录候选，请确认名称和代码'}</div>${items.map(x=>`<button type="button" class="candidate" data-candidate-kind="${kind}" data-row-id="${esc(rowId)}" data-name="${esc(x.name)}" data-code="${esc(x.code||'')}"><strong>${esc(x.name)}</strong><small>${esc(x.meta||'')} ${x.code?`· ${esc(x.code)}`:''}</small><span>选这个</span></button>`).join('')}`;}
function majorCandidates(q){if(!q)return[];const src=/^\d{1,6}$/.test(q)?resolver.search(normalizeMajorCode(q),{limit:8}):resolver.search(q,{limit:8});return src.map(x=>x.item).map(x=>({name:norm(x.name||x.standardMajorName||x.major),code:norm(x.code||x.majorCode2026||x.standardMajorCode)})).filter(x=>x.name);}
function scheduleSchoolSearch(id,q){clearTimeout(runtime.schoolTimers.get(String(id)));if(!q){slot(id,'');return;}runtime.schoolTimers.set(String(id),setTimeout(()=>requestSchoolSearch(id,q),100));}
function requestSchoolSearch(id,q){if(!runtime.worker)return;const key=String(id),seq=++runtime.workerSeq;const old=runtime.pending.get(key);if(old)old.cancelled=true;runtime.pending.set(key,{seq,query:q,cancelled:false});runtime.worker.postMessage({type:'search',id:key,seq,query:q});}
function chooseSchool(id,name){if(!row(id))return;const key=String(id),p=runtime.pending.get(key);if(p)p.cancelled=true;clearTimeout(runtime.schoolTimers.get(key));slot(id,'');patchRow(id,{school:name,confirmedSchool:'',majorCode:'',majorName:'',history:{years:{}},error:''},true);helper(id,`正在确认学校：${name}……`);const seq=++runtime.workerSeq;runtime.pending.set(key,{seq,query:name,cancelled:false,resolving:true});runtime.worker.postMessage({type:'resolve',id:key,seq,query:name});}
function historyFromRecord(exact){const years={};for(const [y,sk,rk,st] of [[2026,'score2026','rank2026','primary-record'],[2025,'score2025','rank2025','strict-match'],[2024,'score2024','rank2024','strict-match']])years[y]={score:exact?.[sk]??null,rank:exact?.[rk]??null,comparable:Boolean(exact),recordStatus:exact?st:'no-strict-record'};return{years};}
function queryHistory(id){const r=row(id);if(!r?.confirmedSchool||!r.majorName)return;const key=`${lower(r.confirmedSchool)}|${lower(r.majorName)}|${norm(r.majorCode)}`;if(runtime.historyCache.has(key)){patchRow(id,{history:runtime.historyCache.get(key),error:''});return;}const old=runtime.factControllers.get(String(id));old?.abort();const controller=new AbortController();runtime.factControllers.set(String(id),controller);const params=new URLSearchParams({major:r.majorName,schoolKeyword:r.confirmedSchool,limit:'120',offset:'0'});if(store.get().totalScore)params.set('candidateScore',store.get().totalScore);fetch(`${API.history}?${params}`,{headers:{accept:'application/json'},signal:controller.signal}).then(async resp=>{const data=await resp.json();if(!resp.ok||data?.ok===false)throw new Error(data?.message||`HTTP ${resp.status}`);return Array.isArray(data.records)?data.records:[]}).then(records=>{const rr=row(id);if(!rr)return;const school=lower(rr.confirmedSchool),name=lower(rr.majorName),code=norm(rr.majorCode);const exact=records.find(x=>lower(x.school)===school&&norm(x.standardMajorCode||x.majorCode2026)===code&&lower(x.standardMajorName||x.major)===name)||records.find(x=>lower(x.school)===school&&lower(x.standardMajorName||x.major)===name);const history=historyFromRecord(exact);runtime.historyCache.set(key,history);patchRow(id,{history,error:exact?'':'没有找到该校该专业的严格历史记录。'});}).catch(e=>{if(e?.name!=='AbortError')patchRow(id,{error:'在线核对暂时失败，可以继续修改专业。'});}).finally(()=>{if(runtime.factControllers.get(String(id))===controller)runtime.factControllers.delete(String(id));});}
function chooseMajor(id,code,name){const r=row(id);if(!r)return;patchRow(id,{majorCode:norm(code),majorName:norm(name),error:'',history:{years:{}}});slot(id,'');helper(id,`${r.confirmedSchool} · 已选择 ${name}，正在读取该校历史记录…`);queryHistory(id);}
function queryMajorMatches(id,q){const r=row(id);if(!r?.confirmedSchool||!q)return;const key=`major:${id}`;runtime.factControllers.get(key)?.abort();const controller=new AbortController();runtime.factControllers.set(key,controller);const params=new URLSearchParams({schoolKeyword:r.confirmedSchool,major:q,limit:'120',offset:'0'});fetch(`${API.history}?${params}`,{headers:{accept:'application/json'},signal:controller.signal}).then(async resp=>{const data=await resp.json();if(!resp.ok||data?.ok===false)throw new Error(data?.message||`HTTP ${resp.status}`);return Array.isArray(data.records)?data.records:[]}).then(records=>{const rr=row(id);if(!rr||norm(rr.majorCode)!==q)return;const matches=records.map(x=>({name:norm(x.standardMajorName||x.major),code:norm(x.standardMajorCode||x.majorCode2026),meta:'该校实际专业'})).filter(x=>x.name).filter(x=>lower(x.name).includes(lower(q))||normalizeMajorCode(x.code).startsWith(normalizeMajorCode(q)||'~')).slice(0,8);if(matches.length){slot(id,candidatesHtml('major',matches,id));helper(id,`找到 ${matches.length} 个该校实际专业，请选择。`);}else{slot(id,'');helper(id,'暂未找到该校与此输入对应的实际专业。','warn');}}).catch(e=>{if(e?.name!=='AbortError')helper(id,'在线核对暂时失败；当前输入仍然保留。','warn');}).finally(()=>{if(runtime.factControllers.get(key)===controller)runtime.factControllers.delete(key);});}
function onSchoolInput(id,value){const v=norm(value);if(!row(id))return;patchRow(id,{school:v,confirmedSchool:'',majorCode:'',majorName:'',history:{years:{}},error:''},false);if(!v){slot(id,'');helper(id,'输入学校名称，不需要等候网络。');return;}helper(id,'正在查找候选学校…');scheduleSchoolSearch(id,v);}
function onMajorInput(id,value){const v=norm(value),r=row(id);if(!r)return;patchRow(id,{majorCode:v,majorName:'',history:{years:{}},error:''},false);if(!r.confirmedSchool){slot(id,'');helper(id,'请先确认学校，再选择该校实际专业。');return;}if(!v){slot(id,'');helper(id,'输入专业名称或代码。');return;}const local=majorCandidates(v);slot(id,candidatesHtml('major',local.map(x=>({name:x.name,code:x.code,meta:'专业目录'})),id));helper(id,'正在按已确认学校核对实际专业记录…');clearTimeout(runtime.schoolTimers.get(`major:${id}`));runtime.schoolTimers.set(`major:${id}`,setTimeout(()=>queryMajorMatches(id,v),160));}
function updateRank(){const score=Math.round(Number(String(store.get().totalScore||'').trim()));if(!Number.isFinite(score)||score<150||score>750){if(store.get().rank!==null)store.commit(s=>({...s,rank:null}),true);return;}runtime.rankController?.abort();const c=new AbortController();runtime.rankController=c;fetch(`${API.rank}?score=${score}`,{headers:{accept:'application/json'},signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d?.message||`HTTP ${r.status}`);if(String(store.get().totalScore)===String(score))store.commit(s=>({...s,rank:d.rank??null}),true)}).catch(e=>{if(e?.name!=='AbortError')showToast('分数位次暂时无法读取')}).finally(()=>{if(runtime.rankController===c)runtime.rankController=null});}
function detailToggle(id){const key=String(id);runtime.expanded.has(key)?runtime.expanded.delete(key):runtime.expanded.add(key);render();}
function reorder(id,d){store.update(s=>{const a=[...s.volunteers],i=a.findIndex(x=>String(x.id)===String(id)),j=i+d;if(i<0||j<0||j>=a.length)return s;[a[i],a[j]]=[a[j],a[i]];return{...s,volunteers:a.map((r,n)=>({...r,order:n+1}))}})}
function removeRow(id){store.update(s=>{const v=s.volunteers.filter(r=>String(r.id)!==String(id));return{...s,volunteers:v.length?v:[createVolunteer(1)]}});runtime.expanded.delete(String(id));}
function addRow(){const s=store.get();if(s.volunteers.some(r=>!r.school&&!r.majorCode)){showToast('已有一条空白志愿，直接填写即可');return;}store.update(s=>({...s,volunteers:[...s.volunteers,createVolunteer(s.volunteers.length+1)]}));}
function reset(){const s=store.get();if(confirm(`确定清空 ${s.volunteers.length} 条模拟志愿？`)){store.update(()=>defaults());runtime.expanded.clear();showToast('已清空模拟清单');}}
function family(id,value){patchRow(id,{familyStatus:value},true)}
function manual(id,key,value){const r=row(id);if(!r)return;store.commit(s=>({...s,volunteers:s.volunteers.map(x=>String(x.id)===String(id)?{...x,manualCheck:{...emptyManual(),...(x.manualCheck||{}),[key]:value}}:x)}),false);}
function inbound(){const p=new URLSearchParams(location.search),school=norm(p.get('school')),code=norm(p.get('majorCode')||p.get('major')),name=norm(p.get('majorName'));if(!school&&!code&&!name)return;const s=store.get();const dup=s.volunteers.find(r=>school&&code&&lower(r.school)===lower(school)&&norm(r.majorCode)===code);if(dup){showToast(`这条内容已在志愿 ${s.volunteers.indexOf(dup)+1}`);return;}let target=s.volunteers.find(r=>!r.school&&!r.majorCode)||null;if(!target){target=createVolunteer(s.volunteers.length+1);store.commit(x=>({...x,volunteers:[...x.volunteers,target]}),false);}if(code||name)patchRow(target.id,{majorCode:code,majorName:name},false);if(school)chooseSchool(target.id,school);if(code||name)render();}
function exportPdf(){const b=document.querySelector('#wbPdf');if(b?.dataset.busy==='1')return;if(b){b.dataset.busy='1';b.textContent='正在生成…';}import('./simulation-report-pdf-service.js').then(m=>m.exportSimulationPdf(store.get(),{android:/Android/i.test(navigator.userAgent)})).then(()=>showToast('方案已生成')).catch(e=>alert(`PDF生成未完成：${e?.message||'未知错误'}`)).finally(()=>{if(b){b.dataset.busy='0';b.textContent='打印 / 保存这份方案';}})}
function bind(){document.body.addEventListener('input',e=>{const t=e.target;if(t.matches('[data-field="school"]'))onSchoolInput(t.dataset.id,t.value);else if(t.matches('[data-field="majorCode"]'))onMajorInput(t.dataset.id,t.value);else if(t.id==='wbStudentName')store.commit(s=>({...s,studentName:t.value}),false);else if(t.id==='wbTotalScore'){store.commit(s=>({...s,totalScore:t.value}),false);updateRank();}else if(t.matches('[data-detail-field]'))manual(t.dataset.id,t.dataset.detailField,t.value);});document.body.addEventListener('change',e=>{const t=e.target;if(t.id==='wbSubject')store.update(s=>({...s,subjectTrack:t.value}));else if(t.matches('[data-detail-field]'))manual(t.dataset.id,t.dataset.detailField,t.value);});document.body.addEventListener('click',e=>{const c=e.target.closest('[data-candidate-kind]');if(c){const id=c.dataset.rowId;if(c.dataset.candidateKind==='school')chooseSchool(id,c.dataset.name);else chooseMajor(id,c.dataset.code,c.dataset.name);return;}const a=e.target.closest('[data-action]');if(a){const id=a.dataset.id,kind=a.dataset.action;if(kind==='detail')detailToggle(id);else if(kind==='delete'){if(confirm('删除这条模拟志愿？只影响这里的整理清单。'))removeRow(id);}else if(kind==='up')reorder(id,-1);else if(kind==='down')reorder(id,1);return;}const f=e.target.closest('[data-family]');if(f){family(f.dataset.id,f.dataset.family);return;}if(e.target.closest('#wbAdd')||e.target.closest('[data-empty-add]'))addRow();else if(e.target.closest('#wbReset'))reset();else if(e.target.closest('#wbPdf'))exportPdf();});}
function initWorker(){runtime.worker=new Worker(`/ln-rank/js/simulation-school-search-worker-v001.js?v=${RELEASE}`,{type:'module'});runtime.worker.addEventListener('message',e=>{const d=e.data||{},key=String(d.id),p=runtime.pending.get(key);if(!p||p.seq!==d.seq||p.cancelled)return;if(lower(row(d.id)?.school)!==lower(p.query))return;if(d.type==='school-candidates'){const items=(d.candidates||[]).slice(0,6).map(x=>({name:norm(x.officialName||x.name),meta:[x.province,x.city,x.level].map(norm).filter(Boolean).join(' · ')}));slot(d.id,candidatesHtml('school',items,d.id));helper(d.id,items.length?'请按名称、地区和层次选择“选这所”。':'暂未找到合适候选学校。',items.length?'neutral':'warn');}else if(d.type==='school-resolved'){const rr=row(d.id);if(!rr)return;const official=norm(d.result?.officialName);if(!official||lower(rr.school)!==lower(official)&&lower(rr.school)!==lower(p.query))return;patchRow(d.id,{confirmedSchool:official,error:''},true);helper(d.id,`✓ 已确认学校：${official}`,'ok');if(rr.majorName)queryHistory(d.id);}else if(d.type==='school-error'){helper(d.id,'学校候选暂时不可用，可以继续输入。','warn');}});}
function init(){if(runtime.initialized)return;runtime.initialized=true;bind();initWorker();store.subscribe(render);render();updateRank();inbound();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.GAOKAO_SIMULATION_RUNTIME=runtime;
export{runtime};
