
import {
  AI_WORKSPACE_CONTRACT_VERSION,AI_EVENT_CONTRACT_VERSION,AI_RESULT_DELTA_VERSION,AI_ACTIVE_VIEW_VERSION,AI_DECISION_PROFILE_VERSION,
  AI_CONVERSATION_MEMORY_VERSION,AI_TURN_HISTORY_VERSION,AI_AGENT_CONTEXT_VERSION,WORKSPACE_LIMITS,DECISION_STAGES,PRIORITY_KEYS,PRIMARY_GOALS,
  nowIso,makeId,cloneValue,cleanText,uniqueStrings,normalizedScore,normalizedRank,viewSeed,turnSeed,agentContextSeed,semanticFrameSeed,decisionSeed,createAiWorkspace,activeViewLabel,regionKeyLabel,applyAiViewPatch
} from './ai-workspace-model.v3992_0.js';
export {AI_WORKSPACE_CONTRACT_VERSION,AI_EVENT_CONTRACT_VERSION,AI_RESULT_DELTA_VERSION,AI_ACTIVE_VIEW_VERSION,AI_DECISION_PROFILE_VERSION,AI_CONVERSATION_MEMORY_VERSION,AI_TURN_HISTORY_VERSION,AI_AGENT_CONTEXT_VERSION,createAiWorkspace,activeViewLabel,regionKeyLabel,applyAiViewPatch,semanticFrameSeed};

function viewIdentity(view={}){return JSON.stringify([normalizedScore(view.score),uniqueStrings(view.majorKeywords||[],8),uniqueStrings(view.regionKeys||['all'],8),uniqueStrings(view.schoolNames||[],4),cleanText(view.bottomLineMode,40),cleanText(view.target,60),cleanText(view.combination,20)]);}
function pushViewHistory(workspace,view){if(!view)return;const snapshot=viewSeed({...view,id:makeId('view-history')},workspace.examContext);if(workspace.viewHistory[0]&&viewIdentity(workspace.viewHistory[0])===viewIdentity(snapshot))return;workspace.viewHistory.unshift(snapshot);workspace.viewHistory=workspace.viewHistory.slice(0,WORKSPACE_LIMITS.views);}
function upsertConstraint(list=[],item={},sourceText=''){const index=list.findIndex(existing=>existing?.key===item.key),next={id:index>=0?list[index].id:makeId('constraint'),key:cleanText(item.key,80),values:uniqueStrings(item.values),label:cleanText(item.label,80),sourceText:cleanText(sourceText,280),updatedAt:nowIso()};if(index>=0)list[index]=next;else list.push(next);}
function applyFamilyChanges(workspace,command={}){if(command.persistence!=='family')return;const changes=command.familyChanges||{};if(Array.isArray(changes.regionIncludeKeys)&&changes.regionIncludeKeys.length)upsertConstraint(workspace.hardConstraints,{key:'regionInclude',values:changes.regionIncludeKeys,label:'家庭长期地区范围'},command.rawText);if(Array.isArray(changes.regionExcludeKeys)&&changes.regionExcludeKeys.length)upsertConstraint(workspace.hardConstraints,{key:'regionExclude',values:changes.regionExcludeKeys,label:'家庭明确排除地区'},command.rawText);if(Array.isArray(changes.majorExcludeKeywords)&&changes.majorExcludeKeywords.length)upsertConstraint(workspace.hardConstraints,{key:'majorExclude',values:changes.majorExcludeKeywords,label:'家庭明确不接受专业'},command.rawText);if(changes.bottomLineMode&&changes.bottomLineMode!=='all')upsertConstraint(workspace.hardConstraints,{key:'bottomLineMode',values:[changes.bottomLineMode],label:'学校性质/费用底线'},command.rawText);}
function mergeExplicitStudentSignals(existing=[],incoming=[]){const map=new Map();for(const item of [...(Array.isArray(existing)?existing:[]),...(Array.isArray(incoming)?incoming:[])]){const dimension=cleanText(item?.dimension,60),value=cleanText(item?.value,120);if(!dimension||!value)continue;map.set(dimension,{dimension,value,polarity:cleanText(item?.polarity,30),source:cleanText(item?.source,40)||'explicit_text'});}return [...map.values()].slice(0,12);}
function mergeDecisionProfile(workspace,command={}){const p=command?.mentorProfile?.persistable;if(!p||typeof p!=='object')return;const explicit=workspace.decisionProfile.explicit;let changed=false;if(PRIMARY_GOALS.has(cleanText(p.primaryGoal,60))&&p.primaryGoal!=='undecided'){explicit.primaryGoal=cleanText(p.primaryGoal,60);changed=true;}const priorities=uniqueStrings(p.priorities||[],12).filter(v=>PRIORITY_KEYS.has(v)&&v!=='feasible_set');if(priorities.length){explicit.priorities=uniqueStrings([...explicit.priorities,...priorities],12);changed=true;}if(p.familyResourceSensitivity==='resource_sensitive'){explicit.familyResourceSensitivity='resource_sensitive';changed=true;}if(['prefer_short','long_ok'].includes(p.studyDurationTolerance)){explicit.studyDurationTolerance=p.studyDurationTolerance;changed=true;}const careerTargets=uniqueStrings(p.careerTargets||[],8);if(careerTargets.length){explicit.careerTargets=uniqueStrings([...(explicit.careerTargets||[]),...careerTargets],8);changed=true;}const studentSignals=mergeExplicitStudentSignals(explicit.studentSignals,p.studentSignals);if(studentSignals.length!==((explicit.studentSignals||[]).length)||JSON.stringify(studentSignals)!==JSON.stringify(explicit.studentSignals||[])){explicit.studentSignals=studentSignals;changed=true;}if(changed){explicit.sourceTexts=uniqueStrings([...explicit.sourceTexts,cleanText(command.rawText,280)],12);explicit.updatedAt=nowIso();workspace.decisionProfile.updatedAt=explicit.updatedAt;}}
function createTaskFromCommand(command={},view={},kind='main'){return{id:makeId('task'),parentTaskId:'',kind,type:cleanText(command.agentTask||command.operation,60)||'search',status:'ready',title:cleanText(command.taskTitle,100)||activeViewLabel(view),command:cloneValue(command),result:null,createdAt:nowIso(),updatedAt:nowIso()};}
function updateMemoryFromTurn(workspace,turn,result){const memory=workspace.conversationMemory;memory.lastUserText=cleanText(turn.userText,600);memory.lastChangeSummary=cleanText(turn.changeSummary,600);if(Array.isArray(result?.pendingChecks))memory.unresolved=uniqueStrings(result.pendingChecks.map(item=>item?.text||item).filter(Boolean),WORKSPACE_LIMITS.memory);const explicit=workspace.decisionProfile.explicit,pieces=[];if(explicit.primaryGoal!=='undecided')pieces.push(`主要目标:${explicit.primaryGoal}`);if(explicit.priorities.length)pieces.push(`优先:${explicit.priorities.join(',')}`);if(explicit.familyResourceSensitivity==='resource_sensitive')pieces.push('家庭资源/预算敏感');if(explicit.studyDurationTolerance!=='unspecified')pieces.push(`培养周期:${explicit.studyDurationTolerance}`);if(explicit.careerTargets?.length)pieces.push(`职业方向:${explicit.careerTargets.join(',')}`);if(explicit.studentSignals?.length)pieces.push(`孩子明确条件:${explicit.studentSignals.map(item=>`${item.dimension}:${item.value}`).join(',')}`);if(workspace.agentContext?.focus?.school)pieces.push(`当前学校:${workspace.agentContext.focus.school}`);if(workspace.agentContext?.focus?.major)pieces.push(`当前专业:${workspace.agentContext.focus.major}`);memory.confirmed=uniqueStrings(pieces,WORKSPACE_LIMITS.memory);memory.summary=cleanText([activeViewLabel(workspace.activeView),...memory.confirmed,turn.changeSummary].filter(Boolean).join('；'),1400);memory.updatedAt=nowIso();}

export function applyAiWorkspaceEvent(workspaceLike,eventLike={}){
  const workspace=createAiWorkspace(workspaceLike||{}),event={version:AI_EVENT_CONTRACT_VERSION,id:cleanText(eventLike.id,120)||makeId('event'),type:cleanText(eventLike.type,80),at:eventLike.at||nowIso(),payload:eventLike.payload&&typeof eventLike.payload==='object'?cloneValue(eventLike.payload):{}};
  if(event.type==='command_committed'){
    const command=event.payload.command||{},resolvedView=event.payload.resolvedView?viewSeed(event.payload.resolvedView,workspace.examContext):workspace.activeView;
    const explicitPersonalScore=normalizedScore(command.score);if(explicitPersonalScore&&command.scoreUsage==='active'&&command.scoreConstraint?.kind==='point')workspace.examContext.score=explicitPersonalScore;
    if(event.payload.commitView!==false&&normalizedScore(resolvedView.score))workspace.examContext.score=normalizedScore(resolvedView.score);
    applyFamilyChanges(workspace,command);mergeDecisionProfile(workspace,command);
    if(event.payload.agentContext)workspace.agentContext=agentContextSeed(event.payload.agentContext,workspace.examContext);
    else if(command.agentTask){workspace.agentContext=agentContextSeed({currentTask:command.agentTask,previousTask:workspace.agentContext?.currentTask||'',focus:command.focus||workspace.agentContext?.focus,contextUsage:command.executionPolicy||{}},workspace.examContext);}
    if(event.payload.commitView!==false&&viewIdentity(workspace.activeView)!==viewIdentity(resolvedView)){pushViewHistory(workspace,workspace.activeView);workspace.activeView={...resolvedView,id:makeId('view'),updatedAt:nowIso()};}
    const stage=cleanText(event.payload.decisionStage,50);if(DECISION_STAGES.has(stage))workspace.decisionStage=stage;
    const taskAction=cleanText(event.payload.taskAction,30)||'update_main';
    if(taskAction==='none'){}else if(!workspace.mainTaskId||taskAction==='create_main'){const task=createTaskFromCommand(command,resolvedView,'main');workspace.tasks.unshift(task);workspace.mainTaskId=task.id;}else if(taskAction==='branch'){const task=createTaskFromCommand(command,resolvedView,'branch');task.parentTaskId=workspace.mainTaskId;workspace.tasks.unshift(task);}else{const main=workspace.tasks.find(task=>task.id===workspace.mainTaskId);if(main){main.command=cloneValue(command);main.title=activeViewLabel(resolvedView);main.updatedAt=nowIso();}}
  }
  if(event.type==='view_restored'){const restored=viewSeed(event.payload.view||{},workspace.examContext);pushViewHistory(workspace,workspace.activeView);workspace.activeView={...restored,id:makeId('view'),updatedAt:nowIso()};if(restored.score)workspace.examContext.score=restored.score;}
  if(event.type==='result_committed'){
    const result=event.payload.result&&typeof event.payload.result==='object'?cloneValue(event.payload.result):null,rawTurn=event.payload.turn||{},personalRankLookup=rawTurn?.command?.agentTask==='fact_rank_lookup'&&rawTurn?.command?.scoreUsage==='active',factOnly=(rawTurn?.command?.agentTask==='fact_rank_lookup'||(rawTurn?.command?.operation==='answer'&&rawTurn?.command?.target==='fact'))&&!personalRankLookup;
    workspace.lastResult=result;workspace.lastTurn=rawTurn&&typeof rawTurn==='object'?cloneValue(rawTurn):workspace.lastTurn;
    if(result?.rank?.rankEnd&&!factOnly)workspace.examContext.rank=Number(result.rank.rankEnd);
    if(DECISION_STAGES.has(cleanText(result?.decisionStage,50)))workspace.decisionStage=cleanText(result.decisionStage,50);
    const taskId=cleanText(event.payload.taskId,120)||workspace.mainTaskId,task=workspace.tasks.find(item=>item.id===taskId);if(task&&result){task.result=result;task.status=result.partial?'partial':'complete';task.updatedAt=nowIso();}
    if(Array.isArray(result?.evidence))workspace.evidence=result.evidence.slice(0,80);if(Array.isArray(result?.pendingChecks))workspace.pendingChecks=result.pendingChecks.slice(0,80);
    if(rawTurn.userText||rawTurn.blocks?.length){const turn=turnSeed({...rawTurn,stage:result?.decisionStage||workspace.decisionStage,viewLabel:activeViewLabel(workspace.activeView)});workspace.turnHistory.push(turn);workspace.turnHistory=workspace.turnHistory.slice(-WORKSPACE_LIMITS.turns);updateMemoryFromTurn(workspace,turn,result);}
  }
  if(event.type==='topic_started'){const previousTask=workspace.agentContext?.currentTask||'';workspace.agentContext=agentContextSeed({currentTask:'',previousTask,focus:{},contextUsage:{score:workspace.examContext?.score?'remembered':'cleared',region:'cleared',major:'cleared',school:'cleared',bottomLine:'cleared'}},workspace.examContext);workspace.mainTaskId='';workspace.activeView={...workspace.activeView,id:makeId('view'),target:'candidates',regionKeys:['all'],majorKeywords:[],schoolNames:[],bottomLineMode:'all',combination:'replace',sourceText:'',updatedAt:nowIso()};}
  if(event.type==='selection_snapshot_imported'){const snapshot=event.payload.snapshot||{};workspace.selectionSnapshot={version:cleanText(snapshot.version,80)||'ln-rank-selection-snapshot-v3992_0',importedAt:nowIso(),items:Array.isArray(snapshot.items)?snapshot.items.slice(0,WORKSPACE_LIMITS.selections):[]};}
  if(event.type==='decision_saved'){const saved=decisionSeed({...event.payload,taskId:cleanText(event.payload.taskId,120)||workspace.mainTaskId});if(saved){workspace.decisions=workspace.decisions.filter(item=>!(item.kind===saved.kind&&JSON.stringify(item.subject)===JSON.stringify(saved.subject)));workspace.decisions.unshift(saved);workspace.decisions=workspace.decisions.slice(0,WORKSPACE_LIMITS.decisions);}}
  workspace.tasks=workspace.tasks.slice(0,WORKSPACE_LIMITS.tasks);workspace.events.push(event);workspace.events=workspace.events.slice(-WORKSPACE_LIMITS.events);workspace.version+=1;workspace.updatedAt=nowIso();return workspace;
}

function recordIds(result={}){const records=Array.isArray(result?.candidates?.records)?result.candidates.records:[];return new Set(records.map(record=>cleanText(record?.id,220)).filter(Boolean));}
function comparableView(view={}){return{score:normalizedScore(view.score),regionKeys:uniqueStrings(view.regionKeys||['all'],8),majorKeywords:uniqueStrings(view.majorKeywords||[],8),schoolNames:uniqueStrings(view.schoolNames||[],4),bottomLineMode:cleanText(view.bottomLineMode,40)||'all'};}
function dimensionDiff(previousView={},nextView={}){const before=comparableView(previousView),after=comparableView(nextView),changes={};for(const key of ['score','regionKeys','majorKeywords','schoolNames','bottomLineMode'])if(JSON.stringify(before[key])!==JSON.stringify(after[key]))changes[key]={before:before[key],after:after[key]};return changes;}
export function buildAiResultDelta(previous=null,next=null,context={}){const prevIds=recordIds(previous||{}),nextIds=recordIds(next||{}),added=[...nextIds].filter(value=>!prevIds.has(value)),removed=[...prevIds].filter(value=>!nextIds.has(value)),previousCounts=previous?.candidates?.counts||{},nextCounts=next?.candidates?.counts||{},countChanges={};for(const key of ['upper','near','steady','total']){const before=Number(previousCounts?.[key]||0),after=Number(nextCounts?.[key]||0);if(before!==after)countChanges[key]={before,after,delta:after-before};}const scopeChanges=dimensionDiff(context.previousView||{},context.nextView||{});return{version:AI_RESULT_DELTA_VERSION,addedPreviewIds:added.slice(0,50),removedPreviewIds:removed.slice(0,50),unchangedPreviewCount:[...nextIds].filter(value=>prevIds.has(value)).length,countChanges,scopeChanges,changed:Boolean(added.length||removed.length||Object.keys(countChanges).length||Object.keys(scopeChanges).length)};}
function compactLastResultForServer(result=null){
  if(!result||typeof result!=='object')return null;
  const compactRecord=record=>({
    id:cleanText(record?.id,220),school:cleanText(record?.school||record?.schoolName,100),major:cleanText(record?.major||record?.majorName,160),
    score2026:Number.isFinite(Number(record?.score2026??record?.score))?Number(record.score2026??record.score):null,
    rank2026:normalizedRank(record?.rank2026??record?.rank),bandKey:cleanText(record?.bandKey||record?.band,30),displayLocation:cleanText(record?.displayLocation||record?.city,80),
    queryMajor:cleanText(record?.queryMajor,160),queryIndex:Number.isFinite(Number(record?.queryIndex))?Number(record.queryIndex):null,queryStatus:cleanText(record?.queryStatus,24)
  });
  const candidates=result.candidates&&typeof result.candidates==='object'?{
    counts:result.candidates.counts||{},records:(Array.isArray(result.candidates.records)?result.candidates.records:[]).map(compactRecord).filter(record=>record.id||record.school||record.major).slice(0,24)
  }:null;
  const history=result.history&&typeof result.history==='object'?{
    school:cleanText(result.history.school,100),majorKeyword:cleanText(result.history.majorKeyword,140),majorKeywords:uniqueStrings(result.history.majorKeywords||[],8),
    partial:result.history.partial===true,allFailed:result.history.allFailed===true,
    queryResults:(result.history.queryResults||[]).slice(0,8).map(item=>({query:cleanText(item?.query,160),index:Number(item?.index||0),status:cleanText(item?.status,24),recordCount:Number(item?.recordCount||0),errorCode:cleanText(item?.errorCode,80),errorMessage:cleanText(item?.errorMessage,200)})),
    records:(result.history.records||[]).slice(0,24).map(compactRecord)
  }:null;
  const majorHistory=result.majorHistory&&typeof result.majorHistory==='object'?{
    majorKeyword:cleanText(result.majorHistory.majorKeyword,160),majorKeywords:uniqueStrings(result.majorHistory.majorKeywords||[],8),bottomLineMode:cleanText(result.majorHistory.bottomLineMode,40),partial:result.majorHistory.partial===true,allFailed:result.majorHistory.allFailed===true,
    queryResults:(result.majorHistory.queryResults||[]).slice(0,8).map(item=>({query:cleanText(item?.query,160),index:Number(item?.index||0),status:cleanText(item?.status,24),recordCount:Number(item?.recordCount||0),errorCode:cleanText(item?.errorCode,80),errorMessage:cleanText(item?.errorMessage,200)})),summary:result.majorHistory.summary||{},records:(result.majorHistory.records||[]).slice(0,24).map(compactRecord)
  }:null;
  return{
    identity:cleanText(result.identity,800),partial:result.partial===true,rank:result.rank?.rankEnd?{rankEnd:Number(result.rank.rankEnd)}:null,candidates,history,majorHistory,
    decisionStage:cleanText(result.decisionStage,50),
    execution:result.execution&&typeof result.execution==='object'?{agentTask:cleanText(result.execution.agentTask,80),scoreUsage:cleanText(result.execution.scoreUsage,30),score:normalizedScore(result.execution.score),focus:result.execution.focus,majorKeywords:uniqueStrings(result.execution.majorKeywords||[],8),bottomLineMode:cleanText(result.execution.bottomLineMode,60),region:result.execution.region&&typeof result.execution.region==='object'?{includeKeys:uniqueStrings(result.execution.region.includeKeys||[],8),excludeKeys:uniqueStrings(result.execution.region.excludeKeys||[],8)}:null}:null
  };
}
function compactSelectionSnapshotForServer(snapshot=null){if(!snapshot||typeof snapshot!=='object')return null;return{version:cleanText(snapshot.version,80),items:(Array.isArray(snapshot.items)?snapshot.items:[]).slice(0,WORKSPACE_LIMITS.selections).map(item=>({id:cleanText(item?.id,180),school:cleanText(item?.school,80),major:cleanText(item?.major,120),rank2026:normalizedRank(item?.rank2026),bandKey:cleanText(item?.bandKey,24),displayLocation:cleanText(item?.displayLocation,60),tuition:cleanText(item?.tuition,60)}))};}
export const AI_TURN_CLIENT_BODY_BUDGET_BYTES=112*1024;
const AI_SERVER_WORKSPACE_DEFAULT_BUDGET_BYTES=88*1024;
const AI_SERVER_WORKSPACE_MIN_BUDGET_BYTES=4*1024;
function jsonBytes(value){return new TextEncoder().encode(JSON.stringify(value)).byteLength;}
function compactFocusForServer(focus={}){return{school:cleanText(focus?.school,80),major:cleanText(focus?.major,100),schools:uniqueStrings(focus?.schools||[],4),majors:uniqueStrings(focus?.majors||[],8)};}
function compactConstraintForServer(item={}){return{key:cleanText(item?.key,60),values:uniqueStrings(item?.values||[],12),label:cleanText(item?.label,60)};}
function compactTaskForServer(task={}){return{id:cleanText(task?.id,120),parentTaskId:cleanText(task?.parentTaskId,120),kind:cleanText(task?.kind,30),type:cleanText(task?.type,60),status:cleanText(task?.status,30),title:cleanText(task?.title,100)};}
function compactTurnForServer(turn={}){return{userText:cleanText(turn?.userText,300),assistantSummary:cleanText(turn?.assistantSummary,360),changeSummary:cleanText(turn?.changeSummary,240),task:cleanText(turn?.task,80),focus:compactFocusForServer(turn?.focus||{}),stage:cleanText(turn?.stage,50),viewLabel:cleanText(turn?.viewLabel,160),at:turn?.at||''};}
function compactDecisionProfileForServer(profile={}){const explicit=profile?.explicit||{};return{version:cleanText(profile?.version,80),explicit:{primaryGoal:cleanText(explicit.primaryGoal,60),priorities:uniqueStrings(explicit.priorities||[],12),familyResourceSensitivity:cleanText(explicit.familyResourceSensitivity,40),studyDurationTolerance:cleanText(explicit.studyDurationTolerance,40),careerTargets:uniqueStrings(explicit.careerTargets||[],8),studentSignals:(Array.isArray(explicit.studentSignals)?explicit.studentSignals:[]).slice(0,12).map(item=>({dimension:cleanText(item?.dimension,60),value:cleanText(item?.value,100),polarity:cleanText(item?.polarity,30),source:cleanText(item?.source,40)}))},inferred:(Array.isArray(profile?.inferred)?profile.inferred:[]).slice(0,8).map(item=>({key:cleanText(item?.key,60),value:cleanText(item?.value,100),confidence:Math.max(0,Math.min(1,Number(item?.confidence||0)))}))};}
function compactDecisionForServer(item={}){return{id:cleanText(item?.id,120),kind:cleanText(item?.kind,60),status:cleanText(item?.status,20),subject:item?.subject&&typeof item.subject==='object'?{school:cleanText(item.subject.school,80),major:cleanText(item.subject.major,100),label:cleanText(item.subject.label,160),value:cleanText(item.subject.value,160)}:{label:cleanText(item?.subject,160)},reason:cleanText(item?.reason||item?.text,220),createdAt:item?.createdAt||''};}
function compactConversationMemoryForServer(memory={}){return{version:cleanText(memory?.version,80),confirmed:uniqueStrings(memory?.confirmed||[],16),unresolved:uniqueStrings(memory?.unresolved||[],12),rejected:uniqueStrings(memory?.rejected||[],8),lastUserText:cleanText(memory?.lastUserText,300),lastChangeSummary:cleanText(memory?.lastChangeSummary,300),summary:cleanText(memory?.summary,800)};}
function selectionReviewInput(text=''){return /(方案|选择池|自选|已选|选了些|选了一些|检查.{0,6}(方案|专业)|看看.{0,6}(方案|已选)|还缺什么)/.test(String(text||''));}
function compactSelectionSnapshotForTurn(snapshot=null,includeDetails=false){if(!snapshot||typeof snapshot!=='object')return null;const raw=Array.isArray(snapshot.items)?snapshot.items:[],base={version:cleanText(snapshot.version,80),itemCount:raw.length};if(!includeDetails)return{...base,items:[]};return{...base,items:raw.slice(0,WORKSPACE_LIMITS.selections).map(item=>({school:cleanText(item?.school,48),major:cleanText(item?.major,72),rank2026:normalizedRank(item?.rank2026),bandKey:cleanText(item?.bandKey,16),displayLocation:cleanText(item?.displayLocation,36),tuition:cleanText(item?.tuition,36)}))};}
function clampWorkspaceBudget(value){const numeric=Math.round(Number(value)||AI_SERVER_WORKSPACE_DEFAULT_BUDGET_BYTES);return Math.max(AI_SERVER_WORKSPACE_MIN_BUDGET_BYTES,Math.min(AI_TURN_CLIENT_BODY_BUDGET_BYTES-4*1024,numeric));}
function shrinkWorkspaceToBudget(out,maxBytes){const reducers=[
  ()=>{out.recentTurns=out.recentTurns.slice(-4);},
  ()=>{out.viewHistory=out.viewHistory.slice(0,3);},
  ()=>{out.tasks=out.tasks.slice(0,4);},
  ()=>{out.pendingChecks=out.pendingChecks.slice(0,8);},
  ()=>{if(out.lastResult?.candidates?.records)out.lastResult.candidates.records=out.lastResult.candidates.records.slice(0,8);if(out.lastResult?.history?.records)out.lastResult.history.records=out.lastResult.history.records.slice(0,8);},
  ()=>{out.recentTurns=out.recentTurns.slice(-2);out.viewHistory=out.viewHistory.slice(0,2);out.tasks=out.tasks.slice(0,2);},
  ()=>{out.conversationMemory={...out.conversationMemory,confirmed:(out.conversationMemory?.confirmed||[]).slice(0,8),unresolved:(out.conversationMemory?.unresolved||[]).slice(0,6),rejected:(out.conversationMemory?.rejected||[]).slice(0,4),lastUserText:cleanText(out.conversationMemory?.lastUserText,180),lastChangeSummary:cleanText(out.conversationMemory?.lastChangeSummary,180),summary:cleanText(out.conversationMemory?.summary,480)};},
  ()=>{out.pendingChecks=[];out.recentTurns=out.recentTurns.slice(-1);out.viewHistory=out.viewHistory.slice(0,1);},
  ()=>{out.tasks=[];if(out.lastResult?.candidates?.records)out.lastResult.candidates.records=[];if(out.lastResult?.history?.records)out.lastResult.history.records=[];},
  ()=>{out.hardConstraints=out.hardConstraints.slice(0,16);out.softPreferences=out.softPreferences.slice(0,16);out.decisionProfile={...out.decisionProfile,inferred:[]};},
  ()=>{out.recentTurns=[];out.viewHistory=[];out.pendingChecks=[];out.lastResult=null;out.conversationMemory={version:out.conversationMemory?.version||'',confirmed:(out.conversationMemory?.confirmed||[]).slice(0,6),summary:cleanText(out.conversationMemory?.summary,320)};}
];for(const reduce of reducers){if(jsonBytes(out)<=maxBytes)break;reduce();}return out;}
export function compactAiWorkspaceForServer(workspaceLike,options={}){const workspace=createAiWorkspace(workspaceLike||{}),input=cleanText(options?.input,1200),includeSelectionDetails=options?.includeSelectionDetails===true||selectionReviewInput(input),maxBytes=clampWorkspaceBudget(options?.maxBytes);const out={contractVersion:workspace.contractVersion,id:workspace.id,version:workspace.version,examContext:workspace.examContext,mainTaskId:workspace.mainTaskId,tasks:workspace.tasks.slice(0,6).map(compactTaskForServer),hardConstraints:workspace.hardConstraints.slice(0,24).map(compactConstraintForServer),softPreferences:workspace.softPreferences.slice(0,24).map(compactConstraintForServer),decisionProfile:compactDecisionProfileForServer(workspace.decisionProfile),decisions:workspace.decisions.slice(0,20).map(compactDecisionForServer),decisionStage:workspace.decisionStage,conversationMemory:compactConversationMemoryForServer(workspace.conversationMemory),agentContext:{version:cleanText(workspace.agentContext?.version,80),currentTask:cleanText(workspace.agentContext?.currentTask,80),previousTask:cleanText(workspace.agentContext?.previousTask,80),focus:compactFocusForServer(workspace.agentContext?.focus||{}),semanticFrame:semanticFrameSeed(workspace.agentContext?.semanticFrame),contextUsage:workspace.agentContext?.contextUsage||{}},activeView:viewSeed(workspace.activeView,workspace.examContext),viewHistory:workspace.viewHistory.slice(0,6).map(view=>({id:view.id,score:view.score,majorKeywords:view.majorKeywords,regionKeys:view.regionKeys,schoolNames:view.schoolNames,bottomLineMode:view.bottomLineMode,target:view.target,combination:view.combination,updatedAt:view.updatedAt})),recentTurns:workspace.turnHistory.slice(-6).map(compactTurnForServer),selectionSnapshot:compactSelectionSnapshotForTurn(workspace.selectionSnapshot,includeSelectionDetails),lastResult:compactLastResultForServer(workspace.lastResult),pendingChecks:workspace.pendingChecks.slice(0,12).map(item=>({key:cleanText(item?.key,100),level:cleanText(item?.level,30),text:cleanText(item?.text,200)}))};return shrinkWorkspaceToBudget(out,maxBytes);}
export function buildAiTurnRequestPayload(workspaceLike,options={}){const input=cleanText(options?.input,1200),confirmedCommand=options?.confirmedCommand&&typeof options.confirmedCommand==='object'?options.confirmedCommand:null,deterministicToolResults=options?.deterministicToolResults&&typeof options.deterministicToolResults==='object'?options.deterministicToolResults:{},envelope={input,confirmedCommand,deterministicToolResults},reserved=jsonBytes(envelope)+2048,workspaceBudget=Math.max(AI_SERVER_WORKSPACE_MIN_BUDGET_BYTES,AI_TURN_CLIENT_BODY_BUDGET_BYTES-reserved);let payload={workspace:compactAiWorkspaceForServer(workspaceLike,{input,maxBytes:workspaceBudget}),...envelope},bytes=jsonBytes(payload);if(bytes>AI_TURN_CLIENT_BODY_BUDGET_BYTES){const tighter=Math.max(AI_SERVER_WORKSPACE_MIN_BUDGET_BYTES,workspaceBudget-(bytes-AI_TURN_CLIENT_BODY_BUDGET_BYTES)-2048);payload={workspace:compactAiWorkspaceForServer(workspaceLike,{input,maxBytes:tighter}),...envelope};bytes=jsonBytes(payload);}if(bytes>AI_TURN_CLIENT_BODY_BUDGET_BYTES)throw new Error('本轮事实桥接超过客户端请求安全预算，请缩小本轮事实范围后继续。');return payload;}

/*
 * AIPLuS fact bridge contract v3992_10.
 * This is the only browser/server boundary for deterministic fact records.
 */
export const AI_FACT_BRIDGE_CONTRACT_VERSION='ai-fact-bridge-v3992_10';
export const AI_FACT_RECORD_FIELDS=Object.freeze(['id','school','major','score2026','rank2026','score2025','rank2025','score2024','rank2024','schoolCode2026','majorCode2026','displayLocation','city','province','projectLabel','bandKey','band','scoreDelta2026','rankGap2026','is985','is211','isSinoForeign','isHighFee','feeType','natureLabel','tuition','matchLevel','matchLabel','matchReason','matchedKeyword','queryMajor','queryIndex','queryStatus','queryErrorCode','queryErrorMessage']);
export function compactAiFactRecord(record={}){
  const out={};
  for(const key of AI_FACT_RECORD_FIELDS){
    const value=record?.[key];
    if(value!==undefined&&value!==null&&value!=='')out[key]=value;
  }
  return out;
}
export function compactSchoolHistoryFactPayload(data={}){
  const summary=data?.summary||{},source=data?.source||{};
  return{
    ok:Boolean(data.ok),
    code:String(data.code||'').slice(0,80),
    message:String(data.message||'').slice(0,300),
    partial:Boolean(data.partial),
    major:String(data.major||'').slice(0,160),
    majorKeyword:String(data.majorKeyword||'').slice(0,160),
    majorKeywords:Array.isArray(data.majorKeywords)?data.majorKeywords.slice(0,8).map(value=>String(value||'').slice(0,160)):[],
    total:Number(data.total||0),
    summary:{...summary,total:Number(summary.total||data.total||0),schoolCount:Number(summary.schoolCount||0),minScore:Number.isFinite(Number(summary.minScore))?Number(summary.minScore):null,maxScore:Number.isFinite(Number(summary.maxScore))?Number(summary.maxScore):null},
    records:Array.isArray(data.records)?data.records.slice(0,120).map(compactAiFactRecord):[],
    majorSuggestions:Array.isArray(data.majorSuggestions)?data.majorSuggestions.slice(0,6).map(item=>({major:String(item?.major||'').slice(0,160),prompt:String(item?.prompt||'').slice(0,240),reason:String(item?.reason||'').slice(0,240)})):[],
    queryResults:Array.isArray(data.queryResults)?data.queryResults.slice(0,8).map(item=>({query:String(item?.query||'').slice(0,160),index:Number(item?.index||0),status:String(item?.status||'').slice(0,24),recordCount:Number(item?.recordCount||0),errorCode:String(item?.errorCode||'').slice(0,80),errorMessage:String(item?.errorMessage||'').slice(0,240)})):[],
    meta:data.meta||{},
    source:{dataYear:Number(source.dataYear||2026),manifestVersion:source.manifestVersion||'',totalRecords:Number(source.totalRecords||0),rawScanned:Number(source.rawScanned||0),exactSchoolRecords:Number(source.exactSchoolRecords||0),mode:source.mode||''},
    bridgeVersion:AI_FACT_BRIDGE_CONTRACT_VERSION
  };
}
