
import {normalizeProjectScope} from './aiplus-product-contract.v002.js';

export const AI_WORKSPACE_CONTRACT_VERSION='ai-workspace-contract-v3992_1';
export const AI_EVENT_CONTRACT_VERSION='ai-event-contract-v3992_1';
export const AI_RESULT_DELTA_VERSION='ai-result-delta-v3992_0';
export const AI_ACTIVE_VIEW_VERSION='ai-active-view-v3992_0';
export const AI_DECISION_PROFILE_VERSION='ai-decision-profile-v3992_1';
export const AI_CONVERSATION_MEMORY_VERSION='ai-conversation-memory-v3992_0';
export const AI_TURN_HISTORY_VERSION='ai-turn-history-v3992_0';
export const AI_AGENT_CONTEXT_VERSION='ai-agent-context-v3992_0';
export const WORKSPACE_LIMITS=Object.freeze({events:240,tasks:24,decisions:80,views:24,selections:112,turns:80,memory:32});
export const DECISION_STAGES=new Set(['start','feasible_set','expand_directions','narrow_region','school_focus','compare','verify','plan_review','history_lookup','background_discovery','fit_assessment']);
export const PRIORITY_KEYS=new Set(['feasible_set','employment','city','school','major','cost','stability','income','study_duration']);
export const PRIMARY_GOALS=new Set(['employment_stability','income_upside','city_opportunity','school_platform','major_fit','cost_control','public_service','undecided']);
export const CONTEXT_STATES=new Set(['active','remembered','suspended','cleared']);

export function nowIso(){try{return new Date().toISOString();}catch{return '';}}
export function makeId(prefix='id'){const cryptoId=globalThis.crypto?.randomUUID?.();return cryptoId?`${prefix}:${cryptoId}`:`${prefix}:${Date.now()}:${Math.random().toString(36).slice(2,9)}`;}
export function cloneValue(value){if(value==null)return value;if(typeof structuredClone==='function')return structuredClone(value);return JSON.parse(JSON.stringify(value));}
export function cleanText(value,max=240){return String(value==null?'':value).trim().slice(0,max);}
export function uniqueStrings(values,max=20){return [...new Set((Array.isArray(values)?values:[]).map(value=>cleanText(value,120)).filter(Boolean))].slice(0,max);}
export function normalizedScore(value){const score=Math.round(Number(value));return Number.isFinite(score)&&score>=150&&score<=750?score:null;}
export function normalizedRank(value){const rank=Math.round(Number(value));return Number.isFinite(rank)&&rank>0?rank:null;}
export function safeArray(values,max=40){return (Array.isArray(values)?values:[]).slice(0,max).map(cloneValue);}

export function viewSeed(seed={},examContext={}){const regions=uniqueStrings(seed.regionKeys||['all'],8);return{version:AI_ACTIVE_VIEW_VERSION,id:cleanText(seed.id,120)||makeId('view'),target:cleanText(seed.target,60)||'candidates',score:normalizedScore(seed.score??examContext.score),majorKeywords:uniqueStrings(seed.majorKeywords||[],8),regionKeys:regions.length?regions:['all'],schoolNames:uniqueStrings(seed.schoolNames||[],4),bottomLineMode:normalizeProjectScope(seed.bottomLineMode),combination:['replace','union'].includes(seed.combination)?seed.combination:'replace',sourceText:cleanText(seed.sourceText,320),updatedAt:seed.updatedAt||nowIso()};}
function explicitStudentSignalSeed(item={}){const dimension=cleanText(item?.dimension,60),value=cleanText(item?.value,120);if(!dimension||!value)return null;return{dimension,value,polarity:cleanText(item?.polarity,30),source:cleanText(item?.source,40)||'explicit_text'};}
export function explicitProfileSeed(seed={}){const primaryGoal=PRIMARY_GOALS.has(cleanText(seed.primaryGoal,60))?cleanText(seed.primaryGoal,60):'undecided',priorities=uniqueStrings(seed.priorities||[],12).filter(value=>PRIORITY_KEYS.has(value)),careerTargets=uniqueStrings(seed.careerTargets||[],8),studentSignals=(Array.isArray(seed.studentSignals)?seed.studentSignals:[]).slice(0,12).map(explicitStudentSignalSeed).filter(Boolean);return{primaryGoal,priorities,familyResourceSensitivity:seed.familyResourceSensitivity==='resource_sensitive'?'resource_sensitive':'unspecified',studyDurationTolerance:['prefer_short','long_ok'].includes(seed.studyDurationTolerance)?seed.studyDurationTolerance:'unspecified',careerTargets,studentSignals,sourceTexts:uniqueStrings(seed.sourceTexts||[],12),updatedAt:seed.updatedAt||nowIso()};}
export function decisionProfileSeed(seed={}){return{version:AI_DECISION_PROFILE_VERSION,explicit:explicitProfileSeed(seed.explicit||seed),inferred:safeArray(seed.inferred,12).map(item=>({key:cleanText(item?.key,80),value:cleanText(item?.value,120),confidence:Math.max(0,Math.min(1,Number(item?.confidence||0))),sourceText:cleanText(item?.sourceText,240),updatedAt:item?.updatedAt||nowIso()})).filter(item=>item.key&&item.value),updatedAt:seed.updatedAt||nowIso()};}
export function conversationMemorySeed(seed={}){return{version:AI_CONVERSATION_MEMORY_VERSION,confirmed:uniqueStrings(seed.confirmed||[],WORKSPACE_LIMITS.memory),unresolved:uniqueStrings(seed.unresolved||[],WORKSPACE_LIMITS.memory),rejected:uniqueStrings(seed.rejected||[],WORKSPACE_LIMITS.memory),lastUserText:cleanText(seed.lastUserText,600),lastChangeSummary:cleanText(seed.lastChangeSummary,600),summary:cleanText(seed.summary,1400),updatedAt:seed.updatedAt||nowIso()};}
export function focusSeed(seed={}){return{school:cleanText(seed.school,120),major:cleanText(seed.major,160),schools:uniqueStrings(seed.schools||[],4),majors:uniqueStrings(seed.majors||[],8),sourceText:cleanText(seed.sourceText,360)};}
export function contextUsageSeed(seed={},examContext={}){return{score:CONTEXT_STATES.has(cleanText(seed.score,30))?cleanText(seed.score,30):(normalizedScore(examContext.score)?'remembered':'cleared'),region:CONTEXT_STATES.has(cleanText(seed.region,30))?cleanText(seed.region,30):'remembered',major:CONTEXT_STATES.has(cleanText(seed.major,30))?cleanText(seed.major,30):'remembered',school:CONTEXT_STATES.has(cleanText(seed.school,30))?cleanText(seed.school,30):'remembered',bottomLine:CONTEXT_STATES.has(cleanText(seed.bottomLine,30))?cleanText(seed.bottomLine,30):'remembered'};}
function semanticPairSeed(item={}){const school=cleanText(item?.school,120),major=cleanText(item?.major,160);if(!school&&!major)return null;return{school,major,label:cleanText(item?.label,300)||[school,major].filter(Boolean).join(' · ') };}
function semanticSignalSeed(item={}){const dimension=cleanText(item?.dimension,60),value=cleanText(item?.value,120);if(!dimension||!value)return null;return{dimension,value,strength:cleanText(item?.strength,30),polarity:cleanText(item?.polarity,30),source:cleanText(item?.source,40)};}
function semanticConstraintSeed(item={}){const dimension=cleanText(item?.dimension,60),value=cleanText(item?.value,120);if(!dimension||!value)return null;return{dimension,operator:cleanText(item?.operator,30),value,strength:cleanText(item?.strength,30),polarity:cleanText(item?.polarity,30),scope:cleanText(item?.scope,40),source:cleanText(item?.source,40)};}
export function semanticFrameSeed(seed={}){if(!seed||typeof seed!=='object')return null;const pairs=(Array.isArray(seed.pairs)?seed.pairs:[]).slice(0,3).map(semanticPairSeed).filter(Boolean),comparisonPairs=(Array.isArray(seed.comparisonPairs)?seed.comparisonPairs:[]).slice(0,3).map(semanticPairSeed).filter(Boolean),reference=seed.reference&&typeof seed.reference==='object'?{kind:cleanText(seed.reference.kind,30),index:Number.isInteger(Number(seed.reference.index))?Math.max(0,Math.min(2,Number(seed.reference.index))):null,word:cleanText(seed.reference.word,30)}:null,counterfactual=seed.counterfactual&&typeof seed.counterfactual==='object'?{active:seed.counterfactual.active===true,changedDimensions:uniqueStrings(seed.counterfactual.changedDimensions||[],12),source:cleanText(seed.counterfactual.source,40)}:{active:false,changedDimensions:[],source:''};const frame={version:cleanText(seed.version,80),speechAct:cleanText(seed.speechAct,30),schools:uniqueStrings(seed.schools||[],4),majors:uniqueStrings(seed.majors||[],8),regionKeys:uniqueStrings(seed.regionKeys||[],8),score:normalizedScore(seed.score),pairs,comparisonPairs,reference,careerTargets:uniqueStrings(seed.careerTargets||[],8),preferenceSignals:(Array.isArray(seed.preferenceSignals)?seed.preferenceSignals:[]).slice(0,16).map(semanticSignalSeed).filter(Boolean),studentSignals:(Array.isArray(seed.studentSignals)?seed.studentSignals:[]).slice(0,10).map(semanticSignalSeed).filter(Boolean),constraints:(Array.isArray(seed.constraints)?seed.constraints:[]).slice(0,18).map(semanticConstraintSeed).filter(Boolean),evidenceNeeds:uniqueStrings(seed.evidenceNeeds||[],9),currentEvidenceNeeds:uniqueStrings(seed.currentEvidenceNeeds||[],9),compositeDecision:seed.compositeDecision===true,counterfactual,source:cleanText(seed.source,60),signature:cleanText(seed.signature,1200)};return frame.version||frame.schools.length||frame.majors.length||frame.comparisonPairs.length?frame:null;}
export function agentContextSeed(seed={},examContext={}){return{version:AI_AGENT_CONTEXT_VERSION,currentTask:cleanText(seed.currentTask,80),previousTask:cleanText(seed.previousTask,80),focus:focusSeed(seed.focus||{}),semanticFrame:semanticFrameSeed(seed.semanticFrame),contextUsage:contextUsageSeed(seed.contextUsage||{},examContext),updatedAt:seed.updatedAt||nowIso()};}
export function turnSeed(seed={}){return{version:AI_TURN_HISTORY_VERSION,id:cleanText(seed.id,120)||makeId('turn'),userText:cleanText(seed.userText,1200),assistantSummary:cleanText(seed.assistantSummary,1200),changeSummary:cleanText(seed.changeSummary,800),stage:DECISION_STAGES.has(cleanText(seed.stage,50))?cleanText(seed.stage,50):'start',task:cleanText(seed.task,80),focus:focusSeed(seed.focus||{}),viewLabel:cleanText(seed.viewLabel,220),blocks:safeArray(seed.blocks,28),command:seed.command&&typeof seed.command==='object'?cloneValue(seed.command):null,at:seed.at||nowIso()};}

export function regionKeyLabel(key='all'){const text=cleanText(key,80);if(!text||text==='all')return'全国';if(text==='ln'||text==='province:辽宁')return'辽宁省内';if(text==='shenyang')return'沈阳';if(text==='dalian')return'大连';if(text==='ln-other')return'辽宁其他';if(text==='outside')return'省外';if(text.startsWith('province:'))return text.slice(9)||'全国';return({jiangzhehu:'江浙沪',huazhong:'华中',southwest:'西南',northwest:'西北'})[text]||text;}
export function activeViewLabel(viewLike={}){const view=viewSeed(viewLike),parts=[];if(view.score)parts.push(`${view.score}分`);if(view.regionKeys.length&&!view.regionKeys.includes('all'))parts.push(view.regionKeys.map(regionKeyLabel).join('、'));if(view.majorKeywords.length)parts.push(view.majorKeywords.join(' / '));if(view.schoolNames.length)parts.push(view.schoolNames.join(' / '));return parts.join(' · ')||'当前探索';}
export function applyAiViewPatch(viewLike={},patchLike={},examContext={}){const base=viewSeed(viewLike,examContext),next=cloneValue(base),patch=patchLike&&typeof patchLike==='object'?patchLike:{};const score=patch.score||{};if(score.op==='set'&&normalizedScore(score.value))next.score=normalizedScore(score.value);const region=patch.region||{};if(region.op==='clear')next.regionKeys=['all'];else if(region.op==='set'){const keys=uniqueStrings(region.keys||[],8);if(keys.length)next.regionKeys=keys;}const major=patch.major||{};if(major.op==='clear'){next.majorKeywords=[];next.combination='replace';}else if(major.op==='set'){next.majorKeywords=uniqueStrings(major.values||[],8);next.combination='replace';}else if(major.op==='add'){next.majorKeywords=uniqueStrings([...base.majorKeywords,...(major.values||[])],8);next.combination='union';}else if(major.op==='remove'){const removing=new Set(uniqueStrings(major.values||[],8));next.majorKeywords=base.majorKeywords.filter(value=>!removing.has(value));next.combination='replace';}const school=patch.school||{};if(school.op==='clear')next.schoolNames=[];else if(school.op==='set')next.schoolNames=uniqueStrings(school.values||[],4);const bottomLine=patch.bottomLine||{};if(bottomLine.op==='set')next.bottomLineMode=normalizeProjectScope(bottomLine.value,base.bottomLineMode);next.target=next.schoolNames.length?'school':'candidates';next.updatedAt=nowIso();return next;}

export function decisionSeed(seed={}){const legacyText=cleanText(seed?.text,360),kind=cleanText(seed?.kind,60)||'note',rawStatus=cleanText(seed?.status,20),status=['keep','reject','pending'].includes(rawStatus)?rawStatus:(legacyText?'pending':'');if(!status)return null;let subject;if(typeof seed?.subject==='string')subject={label:cleanText(seed.subject,220)};else if(seed?.subject&&typeof seed.subject==='object')subject={school:cleanText(seed.subject.school,100),major:cleanText(seed.subject.major,140),label:cleanText(seed.subject.label,220),value:cleanText(seed.subject.value,220)};else subject={label:legacyText};const reason=cleanText(seed?.reason||legacyText,360);return{id:cleanText(seed?.id,120)||makeId('decision'),kind,status,subject,reason,text:reason,taskId:cleanText(seed?.taskId,120),sourceTurnId:cleanText(seed?.sourceTurnId,120),createdAt:seed?.createdAt||nowIso(),updatedAt:seed?.updatedAt||seed?.createdAt||nowIso()};}

export function createAiWorkspace(seed={}){
  const createdAt=seed.createdAt||nowIso(),examContext={province:'辽宁',subject:'物理类',dataYear:2026,audienceYear:2027,score:normalizedScore(seed?.examContext?.score),rank:normalizedRank(seed?.examContext?.rank)},migratedView=seed.activeView||{score:examContext.score,majorKeywords:seed?.lastResult?.execution?.majorKeywords||[],regionKeys:seed?.lastResult?.execution?.region?.includeKeys||['all'],bottomLineMode:seed?.lastResult?.execution?.bottomLineMode||'all'},stage=DECISION_STAGES.has(cleanText(seed.decisionStage,50))?cleanText(seed.decisionStage,50):'start';
  const inferredAgent=seed.agentContext||{currentTask:cleanText(seed?.lastTurn?.task||seed?.lastTurn?.command?.agentTask,80),focus:seed?.lastTurn?.focus||{school:seed?.activeView?.schoolNames?.[0]||'',major:seed?.activeView?.majorKeywords?.[0]||''}};
  return{contractVersion:AI_WORKSPACE_CONTRACT_VERSION,id:cleanText(seed.id,120)||makeId('workspace'),version:Number(seed.version||1),examContext,mainTaskId:cleanText(seed.mainTaskId,120),tasks:safeArray(seed.tasks,WORKSPACE_LIMITS.tasks),hardConstraints:safeArray(seed.hardConstraints,40),softPreferences:safeArray(seed.softPreferences,40),decisionProfile:decisionProfileSeed(seed.decisionProfile||{}),decisionStage:stage,conversationMemory:conversationMemorySeed(seed.conversationMemory||{}),agentContext:agentContextSeed(inferredAgent,examContext),activeView:viewSeed(migratedView,examContext),viewHistory:(Array.isArray(seed.viewHistory)?seed.viewHistory:[]).slice(0,WORKSPACE_LIMITS.views).map(view=>viewSeed(view,examContext)),turnHistory:(Array.isArray(seed.turnHistory)?seed.turnHistory:[]).slice(-WORKSPACE_LIMITS.turns).map(turnSeed),facts:seed.facts&&typeof seed.facts==='object'?cloneValue(seed.facts):{},evidence:safeArray(seed.evidence,80),decisions:(Array.isArray(seed.decisions)?seed.decisions:[]).slice(0,WORKSPACE_LIMITS.decisions).map(decisionSeed).filter(Boolean),pendingChecks:safeArray(seed.pendingChecks,80),selectionSnapshot:seed.selectionSnapshot&&typeof seed.selectionSnapshot==='object'?cloneValue(seed.selectionSnapshot):null,lastResult:seed.lastResult&&typeof seed.lastResult==='object'?cloneValue(seed.lastResult):null,lastTurn:seed.lastTurn&&typeof seed.lastTurn==='object'?cloneValue(seed.lastTurn):null,events:safeArray(seed.events,WORKSPACE_LIMITS.events),createdAt,updatedAt:seed.updatedAt||createdAt};
}
