import {deriveDecisionProgress,FAMILY_DECISION_STAGE_LABELS} from './decision-progress.v003.js?focus=006_0';
import {deriveDecisionFocus} from './decision-focus.v006_1.js?v=006_1';

export const AI_DECISION_BOOK_VERSION='ai-decision-book-v0.03';

const GOAL_LABELS=Object.freeze({employment_stability:'就业稳定',income_upside:'收入上限',city_opportunity:'城市机会',school_platform:'学校平台',major_fit:'专业匹配',cost_control:'成本控制',public_service:'考公/体制路径',undecided:''});
const PRIORITY_LABELS=Object.freeze({employment:'就业',city:'城市机会',school:'学校平台',major:'专业匹配',cost:'成本',stability:'稳定性',income:'收入',study_duration:'培养周期'});
const CAREER_LABELS=Object.freeze({central_soe:'央企方向',state_owned:'国企方向',public_service:'考公/体制',teacher:'教师',manufacturing:'制造业',it:'IT/软件',research:'科研',healthcare:'医疗'});
const SIGNAL_LABELS=Object.freeze({'math_strength:strong':'数学基础较好','physics_strength:strong':'物理基础较好','chemistry_strength:weak':'化学相对弱','programming_affinity:avoid':'不喜欢编程','programming_affinity:accept':'能接受编程','factory_environment:avoid':'不想进工厂/生产一线','shift_work:avoid':'不接受倒班','field_site:avoid':'不想长期现场/工地','travel:avoid':'不接受出差','travel:accept':'可以接受出差','hands_on:strong':'动手/实践能力较好'});
function clean(value,max=240){return String(value==null?'':value).trim().slice(0,max);}
function list(value){return Array.isArray(value)?value:[];}
function unique(values,max=24){return [...new Set(list(values).map(value=>clean(value,180)).filter(Boolean))].slice(0,max);}
function numberText(value){const n=Math.round(Number(value));return Number.isFinite(n)&&n>0?n.toLocaleString('zh-CN'):'';}
function explicitProfileLines(workspace={}){const explicit=workspace?.decisionProfile?.explicit||{},out=[];const goal=GOAL_LABELS[explicit.primaryGoal];if(goal)out.push(goal);for(const key of list(explicit.priorities)){const label=PRIORITY_LABELS[key];if(label)out.push(label);}if(explicit.familyResourceSensitivity==='resource_sensitive')out.push('普通家庭 / 预算资源敏感');if(explicit.studyDurationTolerance==='prefer_short')out.push('更偏本科就业');if(explicit.studyDurationTolerance==='long_ok')out.push('可以接受读研/深造');for(const key of list(explicit.careerTargets)){const label=CAREER_LABELS[key];if(label)out.push(label);}for(const item of list(explicit.studentSignals)){const label=SIGNAL_LABELS[`${item?.dimension}:${item?.value}`];if(label)out.push(label);}return unique(out,16);}
function decisionSubject(item={}){const subject=item?.subject;if(typeof subject==='string')return clean(subject,220);if(subject&&typeof subject==='object'){const school=clean(subject.school,100),major=clean(subject.major,140),label=clean(subject.label,220);return label||[school,major].filter(Boolean).join(' · ')||clean(subject.value,220);}return clean(item?.text,220);}
function decisionGroups(workspace={}){const groups={keep:[],reject:[],pending:[]};for(const item of list(workspace.decisions)){const status=clean(item?.status,20);if(!groups[status])continue;const label=decisionSubject(item);if(!label)continue;groups[status].push({kind:clean(item?.kind,60),label,reason:clean(item?.reason||item?.text,280),createdAt:item?.createdAt||''});}for(const key of Object.keys(groups))groups[key]=groups[key].slice(0,16);return groups;}
function unresolved(workspace={}){return unique([...list(workspace.pendingChecks).map(item=>item?.text||item),...list(workspace?.conversationMemory?.unresolved)],16);}
function evidenceSummary(workspace={}){const evidence=list(workspace.evidence),verified=evidence.filter(item=>clean(item?.sourceUrl,900)&&!/(同学|体验|留言)/.test(`${item?.sourceName||''}${item?.scope||''}`)).length,reference=evidence.filter(item=>/(同学|体验|留言)/.test(`${item?.sourceName||''}${item?.scope||''}`)).length;return{verified,reference,pending:unresolved(workspace).length,total:evidence.length};}
function pairDecisionSummary(pair={}){const dimensions=list(pair.dimensions),pick=key=>dimensions.find(item=>item.key===key),bits=[];for(const key of ['admissions','employment','cost']){const item=pick(key);if(item)bits.push(`${item.label}${item.stateLabel}`);}const family=pick('family_decision');if(family)bits.push(family.stateLabel);return bits.slice(0,4).join(' · ');}
function visiblePairs(workspace={},focus={}){if(list(focus.pairs).length)return focus.pairs.map(pair=>({...pair,label:`${pair.label}｜${pairDecisionSummary(pair)}`})).slice(0,8);const out=[];for(const item of list(workspace?.selectionSnapshot?.items)){const school=clean(item?.school,100),major=clean(item?.major,140);if(school&&major)out.push({school,major,label:`${school} · ${major}`});}return out.slice(0,16);}
export function buildDecisionBook(workspace={}){const progress=deriveDecisionProgress(workspace),focus=deriveDecisionFocus(workspace),profile=explicitProfileLines(workspace),decisions=decisionGroups(workspace),score=Math.round(Number(workspace?.examContext?.score)),rank=numberText(workspace?.examContext?.rank),position=[];if(Number.isFinite(score)&&score>=150&&score<=750)position.push(`${score}分`);if(rank)position.push(`约${rank}位`);const rawGaps=unresolved(workspace),decisionGaps=focus.gaps.slice(0,4).map(item=>`${item.label}：${item.reason}`),gaps=unique([...decisionGaps,...rawGaps],16),pairs=visiblePairs(workspace,focus),next=progress.stages.find(item=>item.key===progress.recommendedStage),evidence=evidenceSummary(workspace);return{version:AI_DECISION_BOOK_VERSION,position:{title:'孩子现在的位置',summary:position.join(' · ')||'分数位置还没确认'},profile:{title:'家庭真正看重什么',items:profile},directions:{title:'当前方向',keep:decisions.keep.filter(item=>item.kind==='major_direction'),reject:decisions.reject.filter(item=>item.kind==='major_direction'),pending:decisions.pending.filter(item=>item.kind==='major_direction'),exploring:progress.majors.slice(0,8)},schoolMajors:{title:'重点学校×专业',items:pairs},focus,decisions,unresolved:{title:'还没解决',items:gaps},evidence:{title:'依据完整度',...evidence,decisionClaimCount:focus.evidenceClaimCount},next:{stage:progress.recommendedStage,label:focus.primaryGap?.label||FAMILY_DECISION_STAGE_LABELS[progress.recommendedStage]||'继续决策',summary:focus.primaryGap?.reason||next?.summary||'',prompt:focus.primaryGap?.prompt||''},progress};}
