from pathlib import Path

def rep(path, old, new, label):
    p = Path(path)
    s = p.read_text()
    if old not in s:
        raise SystemExit('missing ' + label)
    p.write_text(s.replace(old, new, 1))

p = 'functions/_lib/major-bands-static-provider.js'
rep(p, "import { normalizeLocation } from './location-normalizer.js';", "import { normalizeLocation } from './location-normalizer.js';\nimport { matchRegionRule } from '../../shared/resources/geo/china-region-catalog.v3990_1.js';", 'region import')
rep(p, "export const MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION = 'major-bands-rank-order-minimal-projection-v3990_1';", "export const MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION = 'major-bands-rank-order-minimal-projection-v3990_1';\nexport const MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION = 'major-bands-predecode-region-filter-v3990_1';", 'region version')
s = Path(p).read_text()
a = "export function majorBandsRankValueMatchesRange(rankLike, range = null) {"
b = """export function majorBandsStaticRowMatchesRegion(row = [], schema = [], region = 'all') {\n  const key = String(region || 'all').trim();\n  if (!key || key === 'all') return true;\n  const index = name => schema.indexOf(name);\n  const value = indexValue => indexValue >= 0 ? row?.[indexValue] : undefined;\n  return matchRegionRule({\n    lnArea: value(index('lnArea')),\n    province: value(index('province')),\n    city: value(index('city'))\n  }, key);\n}\n\n""" + a
if a not in s:
    raise SystemExit('missing helper anchor')
Path(p).write_text(s.replace(a, b, 1))
old = """  const allowedIds = options.allowedIds instanceof Set ? options.allowedIds : null;\n  const rankFilteredRows = rankRange && rankIndex >= 0\n    ? payload.rows.filter(row => majorBandsRankValueMatchesRange(row?.[rankIndex], rankRange))\n    : payload.rows;\n  const selectedRows = allowedIds && idIndex >= 0\n    ? rankFilteredRows.filter(row => allowedIds.has(String(row?.[idIndex] || '')))\n    : rankFilteredRows;\n"""
new = """  const allowedIds = options.allowedIds instanceof Set ? options.allowedIds : null;\n  const predecodeRegion = String(options.predecodeRegion || 'all').trim() || 'all';\n  const selectedRows = [];\n  let rankFilteredRowCount = 0;\n  let regionFilteredRowCount = 0;\n  for (const row of payload.rows) {\n    if (rankRange && rankIndex >= 0 && !majorBandsRankValueMatchesRange(row?.[rankIndex], rankRange)) continue;\n    rankFilteredRowCount += 1;\n    if (predecodeRegion !== 'all' && !majorBandsStaticRowMatchesRegion(row, schema, predecodeRegion)) continue;\n    regionFilteredRowCount += 1;\n    if (allowedIds && idIndex >= 0 && !allowedIds.has(String(row?.[idIndex] || ''))) continue;\n    selectedRows.push(row);\n  }\n"""
rep(p, old, new, 'row selection')
rep(p, """    rankRowsSkipped: payload.rows.length - selectedRows.length,\n    pageIdRowsSkipped: rankFilteredRows.length - selectedRows.length,\n    pageIdFilterCount: allowedIds?.size || 0,\n""", """    rankRowsSkipped: payload.rows.length - selectedRows.length,\n    rankOnlyRowsSkipped: payload.rows.length - rankFilteredRowCount,\n    regionRowsSkipped: rankFilteredRowCount - regionFilteredRowCount,\n    predecodeRegion,\n    predecodeRegionFilterVersion: MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION,\n    pageIdRowsSkipped: regionFilteredRowCount - selectedRows.length,\n    pageIdFilterCount: allowedIds?.size || 0,\n""", 'provider stats')

p = 'functions/_lib/major-bands-rank-bucket-loader.v3990_1.js'
rep(p, """  MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION,\n  MAJOR_BANDS_RANK_ROW_FILTER_VERSION,\n""", """  MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION,\n  MAJOR_BANDS_RANK_ROW_FILTER_VERSION,\n  MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION,\n""", 'loader import')
rep(p, "export { MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION, MAJOR_BANDS_RANK_ROW_FILTER_VERSION };", "export { MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION, MAJOR_BANDS_RANK_ROW_FILTER_VERSION, MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION };", 'loader export')
rep(p, """  const rawRowStorage = options.rawRowStorage === 'serialized-json' ? 'serialized-json' : 'array-reference';\n  return `${indexBucket.file}|${suffix}|${pageIdFingerprint(options.allowedIds)}|${projection}|${rawRowStorage}`;\n""", """  const rawRowStorage = options.rawRowStorage === 'serialized-json' ? 'serialized-json' : 'array-reference';\n  const predecodeRegion = String(options.predecodeRegion || 'all').trim() || 'all';\n  return `${indexBucket.file}|${suffix}|${pageIdFingerprint(options.allowedIds)}|${projection}|${rawRowStorage}|region:${predecodeRegion}`;\n""", 'cache key')
rep(p, """    allowedIds: options.allowedIds,\n    projection: options.projection,\n""", """    allowedIds: options.allowedIds,\n    predecodeRegion: options.predecodeRegion,\n    projection: options.projection,\n""", 'pass option')
rep(p, """        rankRowsSkipped: 0,\n        pageIdRowsSkipped: 0,\n""", """        rankRowsSkipped: 0,\n        rankOnlyRowsSkipped: 0,\n        regionRowsSkipped: 0,\n        predecodeRegion: String(options.predecodeRegion || 'all').trim() || 'all',\n        predecodeRegionFilterVersion: MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION,\n        pageIdRowsSkipped: 0,\n""", 'empty stats')
rep(p, """  let rankRowsSkipped = 0;\n  let pageIdRowsSkipped = 0;\n""", """  let rankRowsSkipped = 0;\n  let rankOnlyRowsSkipped = 0;\n  let regionRowsSkipped = 0;\n  let pageIdRowsSkipped = 0;\n""", 'counters')
rep(p, """    rankRowsSkipped += Number(result.loaded.rankRowsSkipped || 0);\n    pageIdRowsSkipped += Number(result.loaded.pageIdRowsSkipped || 0);\n""", """    rankRowsSkipped += Number(result.loaded.rankRowsSkipped || 0);\n    rankOnlyRowsSkipped += Number(result.loaded.rankOnlyRowsSkipped || 0);\n    regionRowsSkipped += Number(result.loaded.regionRowsSkipped || 0);\n    pageIdRowsSkipped += Number(result.loaded.pageIdRowsSkipped || 0);\n""", 'aggregate')
rep(p, """      rankRowsSkipped,\n      pageIdRowsSkipped,\n""", """      rankRowsSkipped,\n      rankOnlyRowsSkipped,\n      regionRowsSkipped,\n      predecodeRegion: String(options.predecodeRegion || 'all').trim() || 'all',\n      predecodeRegionFilterVersion: MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION,\n      pageIdRowsSkipped,\n""", 'output stats')

p = 'functions/api/major-bands.js'
rep(p, """      const loaded = await loadMajorBandsRankWindow(context, selected, {\n        projection: minimalOrderProjection ? MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION : undefined\n      });\n""", """      const loaded = await loadMajorBandsRankWindow(context, selected, {\n        projection: minimalOrderProjection ? MAJOR_BANDS_RANK_ORDER_PROJECTION_VERSION : undefined,\n        predecodeRegion: filters.region\n      });\n""", 'api region')

Path('tools/verify-major-bands-predecode-region-v3990_1.mjs').write_text("""import assert from 'node:assert/strict';\nimport fs from 'node:fs';\nimport { majorBandsStaticRowMatchesRegion, MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION } from '../functions/_lib/major-bands-static-provider.js';\nimport { matchRegionRule } from '../shared/resources/geo/china-region-catalog.v3990_1.js';\nconst manifest=JSON.parse(fs.readFileSync('ln-rank/data/major-bands-static-v3972_2/manifest.json','utf8'));\nconst schema=manifest.recordSchema;\nconst idx=Object.fromEntries(['lnArea','province','city'].map(key=>[key,schema.indexOf(key)]));\nconst regions=['all','ln','outside','shenyang','dalian','ln-other','northwest','province:新疆','province:西藏','any:province:新疆|province:西藏','any:province:安徽|province:江苏'];\nlet total=0, west=0;\nfor(const bucket of manifest.buckets){\n  const payload=JSON.parse(fs.readFileSync(bucket.file.replace(/^\\//,''),'utf8'));\n  for(const row of payload.rows){\n    total+=1;\n    const tiny={lnArea:row[idx.lnArea],province:row[idx.province],city:row[idx.city]};\n    for(const region of regions){ assert.equal(majorBandsStaticRowMatchesRegion(row,schema,region),matchRegionRule(tiny,region),`${bucket.file} ${region}`); }\n    if(majorBandsStaticRowMatchesRegion(row,schema,'any:province:新疆|province:西藏')) west+=1;\n  }\n}\nassert.equal(total,11628);\nassert.ok(west>0&&west<total/5,`west reduction ${west}/${total}`);\nassert.equal(MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION,'major-bands-predecode-region-filter-v3990_1');\nconst api=fs.readFileSync('functions/api/major-bands.js','utf8');\nconst loader=fs.readFileSync('functions/_lib/major-bands-rank-bucket-loader.v3990_1.js','utf8');\nassert.ok(api.includes('predecodeRegion: filters.region'));\nassert.ok(loader.includes('predecodeRegion: options.predecodeRegion'));\nconsole.log(JSON.stringify({ok:true,version:MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION,total,west,regions:regions.length},null,2));\n""")

p = 'tools/audit-major-bands-rank-kernel-v3990_1.mjs'
rep(p, "  'payload.rows.filter(row => majorBandsRankValueMatchesRange',", "  'for (const row of payload.rows) {',\n  'majorBandsRankValueMatchesRange(row?.[rankIndex], rankRange)',\n  'majorBandsStaticRowMatchesRegion(row, schema, predecodeRegion)',\n  'selectedRows.push(row)',\n  \"MAJOR_BANDS_PREDECODE_REGION_FILTER_VERSION = 'major-bands-predecode-region-filter-v3990_1'\",", 'audit implementation shape')
anchor = "const bucketLoaderSource = fs.readFileSync('functions/_lib/major-bands-rank-bucket-loader.v3990_1.js', 'utf8');"
ordered = """const rankFilterOrder = [\n  staticProviderSource.indexOf('majorBandsRankValueMatchesRange(row?.[rankIndex], rankRange)'),\n  staticProviderSource.indexOf(\"predecodeRegion !== 'all' && !majorBandsStaticRowMatchesRegion\"),\n  staticProviderSource.indexOf(\"allowedIds && idIndex >= 0 && !allowedIds.has\"),\n  staticProviderSource.indexOf('selectedRows.push(row)')\n];\nassert.ok(rankFilterOrder.every(index => index >= 0), 'predecode filter stages missing');\nassert.ok(rankFilterOrder.every((value, index) => index === 0 || value > rankFilterOrder[index - 1]), 'predecode filter stage order must be rank -> region -> page-id -> select');\n\n""" + anchor
s = Path(p).read_text()
if anchor not in s:
    raise SystemExit('missing audit order anchor')
Path(p).write_text(s.replace(anchor, ordered, 1))
