from pathlib import Path


def patch(path, replacements):
    p=Path(path); text=p.read_text()
    for old,new,count in replacements:
        actual=text.count(old)
        if actual!=count:
            raise SystemExit(f'{path}: anchor count {actual} != {count}: {old[:120]!r}')
        text=text.replace(old,new,count)
    p.write_text(text)

# Agent task kernel: official-school questions are a separate, score-independent task.
patch('functions/_lib/ai/agent-task-kernel.js',[
("  'school_major_history','school_history','fit_assessment',", "  'school_major_history','school_history','school_official_qa','fit_assessment',",1),
("function looksVerify(source){return /(章程|招生计划|学费|校区|体检|选科|官方|来源|核验|资格|培养方案)/.test(source);}", "function looksVerify(source){return /(章程|招生计划|学费|校区|体检|选科|官方|来源|核验|资格|培养方案)/.test(source);}\nfunction looksOfficialSchoolInfo(source){return /(学校简介|院校简介|学校介绍|什么学校|学校定位|办学性质|主管部门|校区|宿舍|住宿|食堂|食宿|奖学金|助学金|奖助|联系方式|联系办法|招生电话|学校官网|招生网址|招生章程|录取规则|调档|退档|专业级差|志愿级差|转专业|学费|收费|院系设置|专业介绍|答考生问|毕业生就业|体检要求|(大学|学院).{0,4}(怎么样|如何|咋样)[？?]?$|这所学校.{0,6}(怎么样|如何|咋样)|这个学校.{0,6}(怎么样|如何|咋样)|该校.{0,6}(怎么样|如何|咋样))/.test(source);}",1),
("  if(directSchoolMajorFollowup)return'school_major_history';", "  if(directSchoolMajorFollowup)return'school_major_history';\n  if(school&&!major&&looksOfficialSchoolInfo(source)&&!looksHistory(source)&&!looksFit(source)&&!looksBackground(source))return'school_official_qa';",1),
("  if(explicitScoreUsage(source,workspace)==='suspended'){\n    if(['school_major_history','school_history','school_background','major_background','background_discovery','school_comparison','major_comparison'].includes(priorTask))return priorTask;", "  if(explicitScoreUsage(source,workspace)==='suspended'){\n    if(['school_major_history','school_history','school_official_qa','school_background','major_background','background_discovery','school_comparison','major_comparison'].includes(priorTask))return priorTask;",1),
("  if(['fact_rank_lookup','school_major_history','school_history','fit_assessment','school_comparison','major_comparison','background_discovery','background_fit_discovery','school_background','major_background','evidence_verification','restore_view','plan_review','save_family'].includes(agentTask))return true;", "  if(['fact_rank_lookup','school_major_history','school_history','school_official_qa','fit_assessment','school_comparison','major_comparison','background_discovery','background_fit_discovery','school_background','major_background','evidence_verification','restore_view','plan_review','save_family'].includes(agentTask))return true;",1),
("    case'school_major_history':case'school_history':case'school_background':case'major_background':case'background_discovery':return{score:score==='suspended'?'suspended':'remembered',region:'remembered',major:'active',school:'active',bottomLine:'remembered',commitView:false};", "    case'school_major_history':case'school_history':case'school_official_qa':case'school_background':case'major_background':case'background_discovery':return{score:score==='suspended'?'suspended':'remembered',region:'remembered',major:'active',school:'active',bottomLine:'remembered',commitView:false};",1),
("school_history:'查询学校招生历史',fit_assessment:", "school_history:'查询学校招生历史',school_official_qa:'查询学校官方信息',fit_assessment:",1),
])

# Command interpreter: lock and focus the official-school task exactly like other school fact tasks.
patch('functions/_lib/ai/command-interpreter.js',[
("else if(['school_major_history','school_history','fit_assessment','school_background'].includes(agentTask)){operation='answer';target='school';}", "else if(['school_major_history','school_history','school_official_qa','fit_assessment','school_background'].includes(agentTask)){operation='answer';target='school';}",1),
("if(['fact_rank_lookup','school_major_history','school_history','fit_assessment','school_comparison'", "if(['fact_rank_lookup','school_major_history','school_history','school_official_qa','fit_assessment','school_comparison'",1),
("needsSchool=['school_major_history','school_history','fit_assessment','school_background'].includes(agentTask)", "needsSchool=['school_major_history','school_history','school_official_qa','fit_assessment','school_background'].includes(agentTask)",1),
("if(['school_major_history','school_history','fit_assessment','school_background'].includes(agentTask)&&!command.focus.school)", "if(['school_major_history','school_history','school_official_qa','fit_assessment','school_background'].includes(agentTask)&&!command.focus.school)",1),
])

# Tool registry: browser-delegated same-site endpoint; server never accepts an arbitrary external URL.
patch('functions/_lib/ai/tool-registry.js',[
("export const AI_BACKGROUND_ADAPTER_VERSION=AI_BACKGROUND_RESOURCE_ADAPTER_VERSION;", "export const AI_BACKGROUND_ADAPTER_VERSION=AI_BACKGROUND_RESOURCE_ADAPTER_VERSION;\nexport const AI_SCHOOL_OFFICIAL_ADAPTER_VERSION='ai-school-official-browser-bridge-v3990_2';",1),
("  school_major_history:Object.freeze({name:'school_major_history',deterministic:true,maxConcurrency:1}),", "  school_major_history:Object.freeze({name:'school_major_history',deterministic:true,maxConcurrency:1}),\n  school_official_info:Object.freeze({name:'school_official_info',deterministic:true,maxConcurrency:1}),",1),
("function schoolHistoryToolKey(request){const url=new URL(request.url);return `${url.pathname}${url.search}`;}", "function schoolHistoryToolKey(request){const url=new URL(request.url);return `${url.pathname}${url.search}`;}\nfunction requestForSchoolOfficial(context,{school,question=''}={}){const sourceUrl=new URL(context.request.url),url=new URL('/api/ai/school-official',sourceUrl.origin);url.searchParams.set('school',clean(school,120));if(question)url.searchParams.set('question',clean(question,600));return new Request(url.toString(),{method:'GET',headers:{accept:'application/json'}});}\nfunction schoolOfficialToolKey(request){const url=new URL(request.url);return `${url.pathname}${url.search}`;}\nfunction schoolOfficialClientToolRequest(request){const key=schoolOfficialToolKey(request);return{kind:'school_official',key,url:key,method:'GET',headers:{accept:'application/json'},bridgeVersion:AI_DETERMINISTIC_TOOL_BRIDGE_VERSION};}\nfunction delegatedSchoolOfficialEntry(context,request){const key=schoolOfficialToolKey(request),entry=context?.aiDeterministicToolResults?.[key];if(!entry)return{ok:false,code:'client_tool_required',toolRequest:schoolOfficialClientToolRequest(request)};if(entry.kind!=='school_official'||entry.key!==key||entry.url!==key)return{ok:false,code:'client_tool_invalid',message:'学校官方信息回传与本轮请求不匹配。'};const status=Number(entry.status),payload=entry.payload;if(!Number.isFinite(status)||!payload||typeof payload!=='object')return{ok:false,code:'client_tool_invalid',message:'学校官方信息回传格式不完整。'};return{ok:true,status,payload};}",1),
("export async function runSchoolMajorHistory(context,{school,majorKeyword=''}={}){", "export async function runSchoolOfficialInfo(context,{school,question=''}={}){\n  if(!school)return{ok:false,code:'school_required',message:'需要先明确一所学校。'};\n  const request=requestForSchoolOfficial(context,{school,question}),delegated=delegatedSchoolOfficialEntry(context,request);if(!delegated.ok)return delegated;const{status,payload}=delegated;if(status<200||status>=300||!payload?.ok)return{ok:false,status,code:payload?.code||'official_source_failed',message:clean(payload?.message||'学校官方信息读取失败。',260)};\n  return{ok:true,school:clean(payload.school||school,120),schId:clean(payload.schId,40),topic:clean(payload.topic,40),topicLabel:clean(payload.topicLabel,80),updatedAt:clean(payload.updatedAt,80),evidenceText:clean(payload.evidenceText,16000),sources:Array.isArray(payload.sources)?payload.sources.slice(0,4).map(item=>({sourceName:clean(item?.sourceName,120),sourceUrl:clean(item?.sourceUrl,900),scope:clean(item?.scope,160),updatedAt:clean(item?.updatedAt,80)})):[],fetchedAt:clean(payload.fetchedAt,80),boundary:clean(payload.boundary,360),adapterVersion:AI_SCHOOL_OFFICIAL_ADAPTER_VERSION};\n}\n\nexport async function runSchoolMajorHistory(context,{school,majorKeyword=''}={}){",1),
])

# Orchestrator: summarize only the official evidence; deterministic fallback gives source navigation, never invented school facts.
patch('functions/_lib/ai/turn-orchestrator.js',[
("  runSchoolMajorHistory,runFitAssessment,runSchoolBackground,runMajorBackground,runBackgroundDiscovery,runBackgroundFitDiscovery,", "  runSchoolMajorHistory,runSchoolOfficialInfo,runFitAssessment,runSchoolBackground,runMajorBackground,runBackgroundDiscovery,runBackgroundFitDiscovery,",1),
("import {agentFocusSeed,taskExecutionPolicy,agentTaskLabel} from './agent-task-kernel.js';", "import {agentFocusSeed,taskExecutionPolicy,agentTaskLabel} from './agent-task-kernel.js';\nimport {runAiProvider} from './provider-router.js';",1),
("function focusForTurn(command={},workspace={}){const prior=workspace?.agentContext?.focus||{},seed=command.focus||{},task=command.agentTask;const school=seed.school||((['school_major_history','school_history','fit_assessment','school_background'].includes(task))?prior.school:'');", "function focusForTurn(command={},workspace={}){const prior=workspace?.agentContext?.focus||{},seed=command.focus||{},task=command.agentTask;const school=seed.school||((['school_major_history','school_history','school_official_qa','fit_assessment','school_background'].includes(task))?prior.school:'');",1),
("function pendingDeterministicTool(result={}){for(const value of [result.candidates,result.history,result.fit,result.background,result.comparison])", "function pendingDeterministicTool(result={}){for(const value of [result.candidates,result.history,result.officialSchool,result.fit,result.background,result.comparison])",1),
("function pendingComparisonPlan(command={}){", "function officialFallbackAnswer(official={}){const school=clean(official.school,120),topic=clean(official.topicLabel,80)||'学校官方信息',updated=clean(official.updatedAt,80);return `已定位到阳光高考的${school}${topic}官方页面${updated?`（资料更新时间：${updated}）`:''}。当前语义模型没有形成可靠归纳，我不替学校补写；请直接查看下方官方来源，本轮录取分数和位次不会受影响。`;}\nasync function summarizeOfficialSchool(context,official={},question=''){if(!official?.ok)return official;const fallback=officialFallbackAnswer(official),evidence=clean(official.evidenceText,9000);let provider={ok:false,provider:'',model:'',latencyMs:0,failures:[]};if(evidence){provider=await runAiProvider(context?.env||{},[{role:'system',content:'你是高考学校官方资料归纳器。只能依据用户提供的阳光高考原文回答，不能使用常识补充，不能制造学校排名、就业率、薪资、录取概率、学费或招生事实。原文没有的信息必须明确说“本次官方材料未提供”。回答面向家长，先直接回答问题，再说明边界；不要长段复制原文。'},{role:'user',content:JSON.stringify({school:official.school,question:clean(question,600),topic:official.topicLabel,updatedAt:official.updatedAt,evidence})}],{maxTokens:700,reasoningEffort:'low'});}\n  const answer=provider?.ok?clean(provider.text,2200):fallback;const sources=(official.sources||[]).map(item=>({...item}));return{...official,evidenceText:undefined,answer,answerMode:provider?.ok?'official-evidence-ai-summary':'official-source-navigation-fallback',answerProvider:{provider:provider?.provider||'',model:provider?.model||'',latencyMs:Number(provider?.latencyMs||0),fallbackUsed:Boolean(provider?.fallbackUsed)},sources};}\nfunction pendingComparisonPlan(command={}){",1),
("else if(command.agentTask==='school_history')changeText=`这轮只看${focus.school}在辽宁物理类的实际招生专业记录${score?'；你的分数仍记着，但不参与筛选':''}。`;", "else if(command.agentTask==='school_history')changeText=`这轮只看${focus.school}在辽宁物理类的实际招生专业记录${score?'；你的分数仍记着，但不参与筛选':''}。`;\n  else if(command.agentTask==='school_official_qa')changeText=`这轮只查${focus.school}的阳光高考官方资料${score?'；你的分数仍记着，但不参与学校介绍和章程归纳':''}。`;",1),
("background:null,comparison:null,selectionReview:", "background:null,officialSchool:null,comparison:null,selectionReview:",1),
("      case'school_history':\n        result.history=await runSchoolMajorHistory(executionContext,{school:focus.school,majorKeyword:''});result.partial=!result.history.ok;break;", "      case'school_history':\n        result.history=await runSchoolMajorHistory(executionContext,{school:focus.school,majorKeyword:''});result.partial=!result.history.ok;break;\n      case'school_official_qa':\n        result.officialSchool=await runSchoolOfficialInfo(executionContext,{school:focus.school,question:command.question||command.rawText||''});if(result.officialSchool?.ok)result.officialSchool=await summarizeOfficialSchool(context,result.officialSchool,command.question||command.rawText||'');result.partial=!result.officialSchool?.ok;break;",1),
("  result.evidence=evidenceForIntent(evidenceIntent(command,result));", "  result.evidence=evidenceForIntent(evidenceIntent(command,result));\n  if(result.officialSchool?.sources?.length)for(const source of result.officialSchool.sources)result.evidence.push({level:'A',sourceName:source.sourceName||'阳光高考',sourceUrl:source.sourceUrl||'',scope:source.scope||result.officialSchool.topicLabel||'学校官方信息',updatedAt:source.updatedAt||result.officialSchool.updatedAt||''});",1),
])

# Presentation: add a distinct official-information block and useful followups.
patch('functions/_lib/ai/advisor-presentation.js',[
("case'school_major_history':case'school_history':return'history_lookup';", "case'school_major_history':case'school_history':return'history_lookup';case'school_official_qa':return'school_official';",1),
("if(result?.fit?.boundary)checks.push({key:'fit-boundary',level:'review',text:clean(result.fit.boundary,280)});", "if(result?.fit?.boundary)checks.push({key:'fit-boundary',level:'review',text:clean(result.fit.boundary,280)});if(result?.officialSchool?.boundary)checks.push({key:'official-school-boundary',level:'review',text:clean(result.officialSchool.boundary,280)});",1),
("  if(task==='school_major_history'){", "  if(task==='school_official_qa'){add('official-charter','看招生章程',`${focus.school}2026招生章程要注意什么`,'继续只看官方资料。');add('official-living','看宿舍和食宿',`${focus.school}宿舍和食宿条件怎么样`,'不拿宣传语替代官方页面。');if(workspace?.examContext?.score)add('official-fit','回到我的分数',`那按我${workspace.examContext.score}分，${focus.school}够得着吗`,'这一步才重新激活分数判断。');else add('official-history','看辽宁投档历史',`${focus.school}所有专业的最低录取分`,'把学校介绍和投档事实分开。');return actions;}\n  if(task==='school_major_history'){",1),
("  if(result.history)blocks.push({type:'history_records'", "  if(result.officialSchool)blocks.push({type:'official_school_info',title:`${result.officialSchool.school||focus.school} · ${result.officialSchool.topicLabel||'官方信息'}`,text:result.officialSchool.answer||result.officialSchool.message||'学校官方信息暂不可用。',official:{school:result.officialSchool.school||focus.school,topicLabel:result.officialSchool.topicLabel||'',updatedAt:result.officialSchool.updatedAt||'',fetchedAt:result.officialSchool.fetchedAt||'',answerMode:result.officialSchool.answerMode||'',sources:result.officialSchool.sources||[],boundary:result.officialSchool.boundary||''}});\n  if(result.history)blocks.push({type:'history_records'",1),
])

# Browser app: AI Plus starters + deterministic school_official bridge + bounded session cache.
patch('ai/app.v3990_1.js',[
("const DB_NAME='gaokao-ai-workspace-v3990_0'", "const AI_PLUS_SCHOOL_MODE=document.body?.dataset?.aiPlus==='school-official-qa';\nconst AI_PLUS_SCHOOL_STARTERS=Object.freeze([{label:'先把学校看懂',prompt:'辽宁石油化工大学到底是什么定位？',reason:'只读官方资料，不拿分数替代学校判断。'},{label:'看2026招生章程',prompt:'辽宁石油化工大学2026招生章程要注意什么？',reason:'规则以官方页面为准。'},{label:'看宿舍和食宿',prompt:'辽宁石油化工大学宿舍和食宿条件怎么样？',reason:'官方页面没写的就不补猜。'},{label:'看另一所学校',prompt:'东北石油大学录取规则和学校定位怎么样？',reason:'继续从阳光高考取证。'}]);\nconst DB_NAME='gaokao-ai-workspace-v3990_0'",1),
("const items=starterScenariosForScore(score);if(!items.length)", "const items=AI_PLUS_SCHOOL_MODE?AI_PLUS_SCHOOL_STARTERS:starterScenariosForScore(score);if(!items.length)",1),
("function compactSchoolHistoryToolPayload(data={}){", "function compactSchoolOfficialToolPayload(data={}){return{ok:Boolean(data.ok),code:String(data.code||'').slice(0,80),message:String(data.message||'').slice(0,300),school:String(data.school||'').slice(0,120),schId:String(data.schId||'').slice(0,40),topic:String(data.topic||'').slice(0,40),topicLabel:String(data.topicLabel||'').slice(0,80),updatedAt:String(data.updatedAt||'').slice(0,80),evidenceText:String(data.evidenceText||'').slice(0,12000),sources:Array.isArray(data.sources)?data.sources.slice(0,4).map(item=>({sourceName:String(item?.sourceName||'').slice(0,120),sourceUrl:String(item?.sourceUrl||'').slice(0,900),scope:String(item?.scope||'').slice(0,160),updatedAt:String(item?.updatedAt||'').slice(0,80)})):[],fetchedAt:String(data.fetchedAt||'').slice(0,80),boundary:String(data.boundary||'').slice(0,360)};}\nfunction compactSchoolHistoryToolPayload(data={}){",1),
("const SCHOOL_HISTORY_SESSION_CACHE_TTL_MS=5*60*1000,SCHOOL_HISTORY_SESSION_CACHE_MAX_ENTRIES=4,schoolHistorySessionCache=new Map();", "const SCHOOL_HISTORY_SESSION_CACHE_TTL_MS=5*60*1000,SCHOOL_HISTORY_SESSION_CACHE_MAX_ENTRIES=4,schoolHistorySessionCache=new Map();\nconst SCHOOL_OFFICIAL_SESSION_CACHE_TTL_MS=10*60*1000,SCHOOL_OFFICIAL_SESSION_CACHE_MAX_ENTRIES=6,schoolOfficialSessionCache=new Map();",1),
("function putSchoolHistorySessionCache(tool,entry){if(tool?.kind!=='school_history'||!entry)return;", "function readSchoolOfficialSessionCache(tool){if(tool?.kind!=='school_official')return null;const entry=schoolOfficialSessionCache.get(tool.url);if(!entry)return null;if(Date.now()-entry.time>SCHOOL_OFFICIAL_SESSION_CACHE_TTL_MS){schoolOfficialSessionCache.delete(tool.url);return null;}schoolOfficialSessionCache.delete(tool.url);schoolOfficialSessionCache.set(tool.url,entry);try{return JSON.parse(entry.serialized);}catch{schoolOfficialSessionCache.delete(tool.url);return null;}}\nfunction putSchoolOfficialSessionCache(tool,entry){if(tool?.kind!=='school_official'||!entry)return;const serialized=JSON.stringify(entry);schoolOfficialSessionCache.delete(tool.url);schoolOfficialSessionCache.set(tool.url,{time:Date.now(),serialized});while(schoolOfficialSessionCache.size>SCHOOL_OFFICIAL_SESSION_CACHE_MAX_ENTRIES){const oldest=schoolOfficialSessionCache.keys().next().value;schoolOfficialSessionCache.delete(oldest);}}\nfunction putSchoolHistorySessionCache(tool,entry){if(tool?.kind!=='school_history'||!entry)return;",1),
("if(tool.kind==='school_history'&&tool.url.startsWith('/api/school-majors?'))return{kind:'school_history',budget:48*1024,compact:compactSchoolHistoryToolPayload,label:'学校历史事实'};return null;", "if(tool.kind==='school_history'&&tool.url.startsWith('/api/school-majors?'))return{kind:'school_history',budget:48*1024,compact:compactSchoolHistoryToolPayload,label:'学校历史事实'};if(tool.kind==='school_official'&&tool.url.startsWith('/api/ai/school-official?'))return{kind:'school_official',budget:48*1024,compact:compactSchoolOfficialToolPayload,label:'学校官方信息'};return null;",1),
("const cached=readSchoolHistorySessionCache(tool);if(cached)return cached;", "const cached=readSchoolHistorySessionCache(tool)||readSchoolOfficialSessionCache(tool);if(cached)return cached;",1),
("putSchoolHistorySessionCache(tool,entry);return entry;", "putSchoolHistorySessionCache(tool,entry);putSchoolOfficialSessionCache(tool,entry);return entry;",1),
])

# Renderer: official sources are first-class and clickable.
patch('ai/render.v3992_0.js',[
("fit_assessment:'判断当前位置'", "fit_assessment:'判断当前位置',school_official:'看学校官方信息'",1),
("function renderDecisionDetails(block){", "function renderOfficialSchool(block,box){const official=block.official||{},list=node('div','detail-list');if(official.updatedAt)list.append(node('div','detail-item',`阳光高考资料更新时间：${official.updatedAt}`));if(official.answerMode==='official-source-navigation-fallback')list.append(node('div','detail-item','语义模型未形成可靠归纳，本轮只提供已定位的官方来源。'));for(const item of official.sources||[]){const row=node('div','detail-item'),href=safeHref(item.sourceUrl);if(href){const a=node('a','',item.sourceName||'阳光高考');a.href=href;a.target='_blank';a.rel='noopener noreferrer';row.append(a);}else row.append(node('span','',item.sourceName||'阳光高考'));if(item.scope)row.append(node('div','muted',item.scope));list.append(row);}if(official.boundary)list.append(node('div','detail-item',official.boundary));box.append(list);}\nfunction renderDecisionDetails(block){",1),
("if(type==='background_routes')classes.push('background');", "if(type==='background_routes')classes.push('background');if(type==='official_school_info')classes.push('fact');",1),
("if(type==='background_routes')renderBackground(block,box,onPrompt);", "if(type==='background_routes')renderBackground(block,box,onPrompt);if(type==='official_school_info')renderOfficialSchool(block,box);",1),
])

# Existing AI page exposes AI Plus without changing workspace ownership.
patch('ai/index.html',[
("      <a href=\"/ln-rank/selection-pool.html\">家庭方案</a>\n      <button id=\"newWorkspace\"", "      <a href=\"/ln-rank/selection-pool.html\">家庭方案</a>\n      <a href=\"/aiplus/\">AI Plus · 问学校</a>\n      <button id=\"newWorkspace\"",1),
])

# The existing AI gate imports the AI Plus contracts; no second validation workflow.
patch('tools/verify-ai-workspace-v3990_1.mjs',[
("import assert from 'node:assert/strict';", "import assert from 'node:assert/strict';\nimport './verify-aiplus-school-official-v3990_2.mjs';",1),
])

# AI Plus score button wording must not claim persistence that the shared UI does not perform.
patch('aiplus/index.html',[
("<button id=\"starterScoreApply\" type=\"button\">记住这个讨论坐标</button>", "<button id=\"starterScoreApply\" type=\"button\">按这个分数给我入口</button>",1),
])
