from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def read(rel): return (ROOT / rel).read_text(encoding='utf-8')
def write(rel, text): (ROOT / rel).write_text(text, encoding='utf-8')
def replace_once(text, old, new, label):
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected 1 occurrence, got {count}')
    return text.replace(old, new, 1)
def replace_all(text, old, new, expected, label):
    count = text.count(old)
    if count != expected:
        raise SystemExit(f'{label}: expected {expected} occurrences, got {count}')
    return text.replace(old, new)

# agent task kernel
rel='functions/_lib/ai/agent-task-kernel.js'; t=read(rel)
t=replace_once(t,"'school_major_history','school_history','school_official_qa'","'school_major_history','school_history','major_region_history','school_official_qa'",'kernel task list')
t=replace_once(t,"  if(school&&explicitMajors.length&&looksHistory(source))return'school_major_history';\n  if(school&&looksHistory(source))return'school_history';","  if(!school&&explicitMajors.length&&looksHistory(source)&&!looksFit(source))return'major_region_history';\n  if(school&&explicitMajors.length&&looksHistory(source))return'school_major_history';\n  if(school&&looksHistory(source))return'school_history';",'kernel major history classifier')
t=replace_once(t,"    case'fit_assessment':return{score:'active',region:'remembered',major:'active',school:'active',bottomLine:'remembered',commitView:false};","    case'major_region_history':return{score:'suspended',region:'active',major:'active',school:'remembered',bottomLine:'remembered',commitView:true};\n    case'fit_assessment':return{score:'active',region:'remembered',major:'active',school:'active',bottomLine:'remembered',commitView:false};",'kernel execution policy')
t=replace_once(t,"school_history:'查询学校招生历史',school_official_qa","school_history:'查询学校招生历史',major_region_history:'查询专业地区历史分数',school_official_qa",'kernel label')
write(rel,t)

# command interpreter
rel='functions/_lib/ai/command-interpreter.js'; t=read(rel)
t=replace_once(t,"else if(['major_background','background_discovery','background_fit_discovery'].includes(agentTask)){operation='answer';target='major';}","else if(['major_region_history','major_background','background_discovery','background_fit_discovery'].includes(agentTask)){operation='answer';target='major';}",'legacy major target')
t=replace_once(t,"'school_major_history','school_history','school_official_qa','fit_assessment'","'school_major_history','school_history','major_region_history','school_official_qa','fit_assessment'",'task lock major history')
t=replace_once(t,"const rawScoreUsage=explicitScoreUsage(source,workspace),scoreUsage=(['candidate_discovery','candidate_refinement','fit_assessment','background_fit_discovery','fact_rank_lookup'].includes(agentTask)&&score)?'active':rawScoreUsage,taskLocked=explicitTaskLock", "const rawScoreUsage=explicitScoreUsage(source,workspace),scoreUsage=agentTask==='major_region_history'?'suspended':((['candidate_discovery','candidate_refinement','fit_assessment','background_fit_discovery','fact_rank_lookup'].includes(agentTask)&&score)?'active':rawScoreUsage),taskLocked=explicitTaskLock",'score suspension')
t=replace_once(t,"needsMajor=['school_major_history','fit_assessment','major_background'].includes(agentTask)","needsMajor=['school_major_history','major_region_history','fit_assessment','major_background'].includes(agentTask)",'needs major')
t=replace_once(t,"if(['school_major_history','fit_assessment','major_background'].includes(agentTask)&&!command.focus.major)","if(['school_major_history','major_region_history','fit_assessment','major_background'].includes(agentTask)&&!command.focus.major)",'model major confirmation')
write(rel,t)

# deterministic tool registry
rel='functions/_lib/ai/tool-registry.js'; t=read(rel)
t=replace_once(t,"export const AI_SCHOOL_HISTORY_ADAPTER_VERSION='ai-school-history-browser-bridge-v3992_2';","export const AI_SCHOOL_HISTORY_ADAPTER_VERSION='ai-school-history-browser-bridge-v3992_2';\nexport const AI_MAJOR_HISTORY_ADAPTER_VERSION='ai-major-region-history-browser-bridge-v3992_3';",'major history adapter const')
t=replace_once(t,"  school_major_history:Object.freeze({name:'school_major_history',deterministic:true,maxConcurrency:1}),","  school_major_history:Object.freeze({name:'school_major_history',deterministic:true,maxConcurrency:1}),\n  major_region_history:Object.freeze({name:'major_region_history',deterministic:true,maxConcurrency:1}),",'tool registry entry')
t=replace_once(t,"function schoolHistoryToolKey(request){const url=new URL(request.url);return `${url.pathname}${url.search}`;}","function requestForMajorRegionHistory(context,{majorKeyword='',regionKeys=['all']}={}){const sourceUrl=new URL(context.request.url),url=new URL('/api/ai/major-history',sourceUrl.origin),regions=normalizeRegionKeys(regionKeys).slice(0,4),region=regions.length>1?`any:${regions.join('|')}`:(regions[0]||'all');url.searchParams.set('major',clean(majorKeyword,160));url.searchParams.set('region',region);url.searchParams.set('offset','0');url.searchParams.set('limit','100');return new Request(url.toString(),{method:'GET',headers:{accept:'application/json'}});}\nfunction schoolHistoryToolKey(request){const url=new URL(request.url);return `${url.pathname}${url.search}`;}\nfunction majorHistoryToolKey(request){const url=new URL(request.url);return `${url.pathname}${url.search}`;}",'major history request')
t=replace_once(t,"function schoolHistoryClientToolRequest(request){const key=schoolHistoryToolKey(request);return{kind:'school_history',key,url:key,method:'GET',headers:{accept:'application/json'},bridgeVersion:AI_DETERMINISTIC_TOOL_BRIDGE_VERSION};}","function schoolHistoryClientToolRequest(request){const key=schoolHistoryToolKey(request);return{kind:'school_history',key,url:key,method:'GET',headers:{accept:'application/json'},bridgeVersion:AI_DETERMINISTIC_TOOL_BRIDGE_VERSION};}\nfunction majorHistoryClientToolRequest(request){const key=majorHistoryToolKey(request);return{kind:'major_history',key,url:key,method:'GET',headers:{accept:'application/json'},bridgeVersion:AI_DETERMINISTIC_TOOL_BRIDGE_VERSION};}",'major history client request')
t=replace_once(t,"function delegatedMajorBandsEntry(context,request){","function delegatedMajorHistoryEntry(context,request){const key=majorHistoryToolKey(request),entry=context?.aiDeterministicToolResults?.[key];if(!entry)return{ok:false,code:'client_tool_required',toolRequest:majorHistoryClientToolRequest(request)};if(entry.kind!=='major_history'||entry.key!==key||entry.url!==key)return{ok:false,code:'client_tool_invalid',message:'专业地区历史事实回传与本轮请求不匹配。'};const status=Number(entry.status),payload=entry.payload;if(!Number.isFinite(status)||!payload||typeof payload!=='object')return{ok:false,code:'client_tool_invalid',message:'专业地区历史事实回传格式不完整。'};return{ok:true,status,payload};}\nfunction delegatedMajorBandsEntry(context,request){",'major history delegated entry')
t=replace_once(t,"export async function runSchoolMajorHistory(context,{school,majorKeyword=''}={}){","function majorHistoryRecord(record={}){return{...historyRecord(record),score2025:Number.isFinite(Number(record.score2025))?Number(record.score2025):null,rank2025:Number.isFinite(Number(record.rank2025))?Number(record.rank2025):null,score2024:Number.isFinite(Number(record.score2024))?Number(record.score2024):null,rank2024:Number.isFinite(Number(record.rank2024))?Number(record.rank2024):null,province:clean(record.province,80),city:clean(record.city,80),standardMajorName:clean(record.standardMajorName,160),standardMajorCode:clean(record.standardMajorCode,40)};}\nexport async function runMajorRegionHistory(context,{majorKeyword='',regionKeys=['all']}={}){\n  if(!majorKeyword)return{ok:false,code:'major_required',message:'需要先明确一个专业方向。'};\n  const request=requestForMajorRegionHistory(context,{majorKeyword,regionKeys}),delegated=delegatedMajorHistoryEntry(context,request);if(!delegated.ok)return delegated;const{status,payload}=delegated;if(status<200||status>=300||!payload?.ok)return{ok:false,status,message:clean(payload?.message||'专业地区历史查询失败。',260)};\n  return{ok:true,majorKeyword:clean(payload.major||majorKeyword,160),region:clean(payload.region,220),matchedMajors:unique(payload.matchedMajors||[],8),records:(payload.records||[]).map(majorHistoryRecord),summary:payload.summary||{},total:Number(payload.total||0),complete:payload.complete===true,source:payload.source||{},adapterVersion:AI_MAJOR_HISTORY_ADAPTER_VERSION,scoreUsed:false,boundary:clean(payload.boundary,360)||'只展示2026辽宁物理类实际投档记录，不使用考生个人分数过滤。'};\n}\n\nexport async function runSchoolMajorHistory(context,{school,majorKeyword=''}={}){",'run major region history')
write(rel,t)

# turn orchestrator
rel='functions/_lib/ai/turn-orchestrator.js'; t=read(rel)
t=replace_once(t,"resolveRegionExecution,runMajorBandSearch,runRankLookup,runSchoolComparison,runMajorComparison,\n  runSchoolMajorHistory", "resolveRegionExecution,runMajorBandSearch,runRankLookup,runSchoolComparison,runMajorComparison,\n  runSchoolMajorHistory,runMajorRegionHistory",'orchestrator import')
t=replace_once(t,"const CANDIDATE_TASKS=new Set(['candidate_discovery','candidate_refinement']);","const CANDIDATE_TASKS=new Set(['candidate_discovery','candidate_refinement']);\nconst VIEW_MUTATING_TASKS=new Set([...CANDIDATE_TASKS,'major_region_history']);",'mutating tasks')
t=replace_once(t,"mutates=CANDIDATE_TASKS.has(command.agentTask);","mutates=VIEW_MUTATING_TASKS.has(command.agentTask);",'resolve mutating task')
t=replace_once(t,"(['school_major_history','fit_assessment','major_background'].includes(task))?prior.major:'')","(['school_major_history','major_region_history','fit_assessment','major_background'].includes(task))?prior.major:'')",'focus major inheritance')
t=replace_once(t,"[result.candidates,result.history,result.fit,result.officialSchool,result.background,result.comparison]","[result.candidates,result.history,result.majorHistory,result.fit,result.officialSchool,result.background,result.comparison]",'pending deterministic tool')
t=replace_once(t,"if(CANDIDATE_TASKS.has(command.agentTask))changeText=changeSummary(resolved.previousView,view,command);\n  else if(command.agentTask==='fact_rank_lookup')", "if(CANDIDATE_TASKS.has(command.agentTask))changeText=changeSummary(resolved.previousView,view,command);\n  else if(command.agentTask==='major_region_history')changeText=`${changeSummary(resolved.previousView,view,command)} 同时直接查${view.majorKeywords.join(' / ')||focus.major}在当前地区的2026物理类实际投档分数；这轮不需要先给个人分数。`;\n  else if(command.agentTask==='fact_rank_lookup')",'major history change text')
t=replace_once(t,"candidates:null,history:null,fit:null","candidates:null,history:null,majorHistory:null,fit:null",'result major history slot')
t=replace_once(t,"      case'school_major_history':\n        result.history=await runSchoolMajorHistory", "      case'major_region_history':\n        result.majorHistory=await runMajorRegionHistory(executionContext,{majorKeyword:focus.major||(view.majorKeywords||[])[0]||'',regionKeys:regionExecution.exact?regionExecution.includeKeys:(view.regionKeys||['all'])});result.partial=!result.majorHistory.ok;break;\n      case'school_major_history':\n        result.history=await runSchoolMajorHistory",'major history execution')
t=replace_once(t,"command.agentTask==='evidence_verification'?'verification':CANDIDATE_TASKS.has(command.agentTask)?'candidate_search':'general_question'", "command.agentTask==='evidence_verification'?'verification':(CANDIDATE_TASKS.has(command.agentTask)||command.agentTask==='major_region_history')?'candidate_search':'general_question'",'major history evidence topic')
t=replace_once(t,"const taskAction=CANDIDATE_TASKS.has(command.agentTask)?", "const taskAction=VIEW_MUTATING_TASKS.has(command.agentTask)?",'major history task action')
write(rel,t)

# presentation
rel='functions/_lib/ai/advisor-presentation.js'; t=read(rel)
t=replace_once(t,"case'school_major_history':case'school_history':return'history_lookup';","case'school_major_history':case'school_history':case'major_region_history':return'history_lookup';",'major history stage')
t=replace_once(t,"function platformUpgradeSummary(platform)","function majorRegionHistorySummary(history,view){if(!history?.ok)return history?.message||'专业地区历史没有读取成功。';const total=Number(history.total||history.records?.length||0),schools=Number(history.summary?.schoolCount||0),min=Number(history.summary?.minScore),max=Number(history.summary?.maxScore),range=[];if(Number.isFinite(min))range.push(`最低${min}分`);if(Number.isFinite(max))range.push(`最高${max}分`);return`${history.majorKeyword||view.majorKeywords?.[0]||'这个专业'}在${regionLabel(view.regionKeys)}的辽宁2026物理类实际投档记录共 ${total} 条${schools?`，涉及 ${schools} 所学校`:''}${range.length?`；${range.join('，')}`:''}。下面按2026投档分从高到低列出${history.complete?'全部':'当前页'}记录；这轮不拿你的个人分数过滤。`;}\nfunction platformUpgradeSummary(platform)",'major history summary')
t=replace_once(t,"if(result?.history?.boundary)checks.push", "if(result?.majorHistory?.boundary)checks.push({key:'major-history-boundary',level:'review',text:clean(result.majorHistory.boundary,280)});if(result?.history?.boundary)checks.push",'major history boundary')
t=replace_once(t,"if(result?.candidates?.counts?.total>0||result?.history?.records?.length||result?.fit?.records?.length)","if(result?.candidates?.counts?.total>0||result?.majorHistory?.records?.length||result?.history?.records?.length||result?.fit?.records?.length)",'major history annual plan')
t=replace_once(t,"  if(task==='school_major_history'){", "  if(task==='major_region_history'){if(workspace?.examContext?.score)add('candidate-fit','再按我的分数看可达性',`按我${workspace.examContext.score}分，${regionLabel(view.regionKeys)}${view.majorKeywords?.[0]||focus.major}有哪些学校够得着`,'历史分数已经看清，再把个人位置放回来。');else add('set-score','带上我的分数判断','我580分，这些学校哪些更现实','只有做可达判断时才需要个人分数。');add('major-bg','看省内专业背景',`${view.majorKeywords?.[0]||focus.major}在辽宁哪些学校有背景证据`,'从分数事实切到学校背景。');return actions;}\n  if(task==='school_major_history'){",'major history next questions')
t=replace_once(t,"  if(result.history)blocks.push", "  if(result.majorHistory)blocks.push({type:'history_records',title:`${regionLabel(view.regionKeys)} · ${result.majorHistory.majorKeyword||view.majorKeywords?.[0]||focus.major} · 2026投档分数`,text:majorRegionHistorySummary(result.majorHistory,view),records:(result.majorHistory.records||[]).slice(0,100),allMajors:false,summary:result.majorHistory.summary||{},scoreUsed:false,dataYear:2026});\n  if(result.history)blocks.push",'major history block')
write(rel,t)

# browser bridge/app
rel='aiplus/app.v3990_1.js'; t=read(rel)
t=replace_once(t,"'score2026','rank2026','schoolCode2026'","'score2026','rank2026','score2025','rank2025','score2024','rank2024','schoolCode2026'",'bridge record history years')
t=replace_once(t,"function compactSchoolOfficialToolPayload", "function compactMajorHistoryToolPayload(data={}){const summary=data?.summary||{},source=data?.source||{};return{ok:Boolean(data.ok),code:String(data.code||'').slice(0,80),message:String(data.message||'').slice(0,300),major:String(data.major||'').slice(0,160),region:String(data.region||'').slice(0,220),matchedMajors:Array.isArray(data.matchedMajors)?data.matchedMajors.slice(0,8).map(value=>String(value||'').slice(0,160)):[],total:Number(data.total||0),summary:{total:Number(summary.total||0),schoolCount:Number(summary.schoolCount||0),minScore:Number.isFinite(Number(summary.minScore))?Number(summary.minScore):null,maxScore:Number.isFinite(Number(summary.maxScore))?Number(summary.maxScore):null},records:Array.isArray(data.records)?data.records.slice(0,100).map(compactMajorBandsBridgeRecord):[],complete:data.complete===true,source:{level:String(source.level||'').slice(0,20),sourceName:String(source.sourceName||'').slice(0,160),sourceVersion:String(source.sourceVersion||'').slice(0,100),sourceRecordCount:Number(source.sourceRecordCount||0),derivedIndex:source.derivedIndex===true,sameTruthSet:source.sameTruthSet===true},boundary:String(data.boundary||'').slice(0,360)};}\nfunction compactSchoolOfficialToolPayload",'compact major history')
t=replace_once(t,"const SCHOOL_HISTORY_SESSION_CACHE_TTL_MS=5*60*1000,SCHOOL_HISTORY_SESSION_CACHE_MAX_ENTRIES=4,schoolHistorySessionCache=new Map();", "const SCHOOL_HISTORY_SESSION_CACHE_TTL_MS=5*60*1000,SCHOOL_HISTORY_SESSION_CACHE_MAX_ENTRIES=4,schoolHistorySessionCache=new Map();\nconst MAJOR_HISTORY_SESSION_CACHE_TTL_MS=5*60*1000,MAJOR_HISTORY_SESSION_CACHE_MAX_ENTRIES=4,majorHistorySessionCache=new Map();",'major history session cache')
t=replace_once(t,"function readSchoolOfficialSessionCache(tool)", "function readMajorHistorySessionCache(tool){if(tool?.kind!=='major_history')return null;const entry=majorHistorySessionCache.get(tool.url);if(!entry)return null;if(Date.now()-entry.time>MAJOR_HISTORY_SESSION_CACHE_TTL_MS){majorHistorySessionCache.delete(tool.url);return null;}majorHistorySessionCache.delete(tool.url);majorHistorySessionCache.set(tool.url,entry);try{return JSON.parse(entry.serialized);}catch{majorHistorySessionCache.delete(tool.url);return null;}}\nfunction readSchoolOfficialSessionCache(tool)",'read major history cache')
t=replace_once(t,"function putSchoolHistorySessionCache(tool,entry)", "function putMajorHistorySessionCache(tool,entry){if(tool?.kind!=='major_history'||!entry)return;const serialized=JSON.stringify(entry);majorHistorySessionCache.delete(tool.url);majorHistorySessionCache.set(tool.url,{time:Date.now(),serialized});while(majorHistorySessionCache.size>MAJOR_HISTORY_SESSION_CACHE_MAX_ENTRIES){const oldest=majorHistorySessionCache.keys().next().value;majorHistorySessionCache.delete(oldest);}}\nfunction putSchoolHistorySessionCache(tool,entry)",'put major history cache')
t=replace_once(t,"if(tool.kind==='school_history'&&tool.url.startsWith('/api/school-majors?'))return{kind:'school_history',budget:48*1024,compact:compactSchoolHistoryToolPayload,label:'学校历史事实'};", "if(tool.kind==='school_history'&&tool.url.startsWith('/api/school-majors?'))return{kind:'school_history',budget:48*1024,compact:compactSchoolHistoryToolPayload,label:'学校历史事实'};if(tool.kind==='major_history'&&tool.url.startsWith('/api/ai/major-history?'))return{kind:'major_history',budget:64*1024,compact:compactMajorHistoryToolPayload,label:'专业地区历史事实'};",'major history tool spec')
t=replace_once(t,"const cached=readSchoolHistorySessionCache(tool);if(cached)return cached;const officialCached", "const cached=readSchoolHistorySessionCache(tool);if(cached)return cached;const majorHistoryCached=readMajorHistorySessionCache(tool);if(majorHistoryCached)return majorHistoryCached;const officialCached",'major history cache read execution')
t=replace_once(t,"if(tool.kind==='school_history'){putSchoolHistorySessionCache(tool,entry);return entry;}if(tool.kind==='school_official')", "if(tool.kind==='school_history'){putSchoolHistorySessionCache(tool,entry);return entry;}if(tool.kind==='major_history'){putMajorHistorySessionCache(tool,entry);return entry;}if(tool.kind==='school_official')",'major history cache put execution')
write(rel,t)

# Browser e2e contract
rel='tools/browser-ai-workspace-v3990_1.mjs'; t=read(rel)
t=replace_once(t,"if(requirements.history)assert(data?.result?.history?.ok===true,`${text}: history not ok ${bodySummary(data?.result?.history)}`);if(requirements.background)", "if(requirements.history)assert(data?.result?.history?.ok===true,`${text}: history not ok ${bodySummary(data?.result?.history)}`);if(requirements.majorHistory)assert(data?.result?.majorHistory?.ok===true,`${text}: major history not ok ${bodySummary(data?.result?.majorHistory)}`);if(requirements.background)",'browser requirement')
anchor="async function scoreBandParentJourneys(page,name){"
journey="async function majorRegionHistoryJourney(page,name){if(name!=='pc')return;await reset(page);const data=await submitTurn(page,'测控专业 省内都多少分',{majorHistory:true});assert(data.command.agentTask==='major_region_history',`major history task drift: ${data.command.agentTask}`);assert(data.resolvedView?.majorKeywords?.includes('测控技术与仪器'),'major history view major missing');assert(data.resolvedView?.regionKeys?.some(key=>key==='ln'||key==='province:辽宁'),'major history view region missing');assert((data.result.majorHistory.records||[]).length>0,'major history records missing');assert((data.result.majorHistory.records||[]).every(item=>item.province==='辽宁'),'major history leaked outside Liaoning');const stream=(await page.locator('#conversationStream').innerText()).replace(/\\s+/g,' ');assert(stream.includes('测控技术与仪器'),'major history major not rendered');assert(/最低\\d+分/.test(stream)&&/最高\\d+分/.test(stream),`major history score range not rendered: ${stream.slice(-1500)}`);assert(stream.includes('2026参考'),'major history record cards missing');}\n"
t=replace_once(t,anchor,journey+anchor,'browser major history journey')
# invoke journey before scoreBand journey in per-device execution
call_anchor="await schoolHistoryAliasJourney(page,d.name);"
t=replace_once(t,call_anchor,call_anchor+"await majorRegionHistoryJourney(page,d.name);",'browser major history call')
write(rel,t)

# AI workflow: include generated data/build/verifier and run deterministic gate
rel='.github/workflows/verify-ai-workspace-v3990_1.yml'; t=read(rel)
t=replace_all(t,"      - 'tools/verify-aiplus-human-dialog-v3990_2.mjs'\n", "      - 'tools/verify-aiplus-human-dialog-v3990_2.mjs'\n      - 'tools/build-ai-major-history-index-v3990_1.mjs'\n      - 'tools/verify-ai-major-region-history-v3992_3.mjs'\n      - 'ln-rank/data/ai-major-history-v3990_1/**'\n",2,'workflow paths')
t=replace_once(t,"          node --check tools/verify-aiplus-human-dialog-v3990_2.mjs\n", "          node --check tools/verify-aiplus-human-dialog-v3990_2.mjs\n          node --check tools/build-ai-major-history-index-v3990_1.mjs\n          node --check tools/verify-ai-major-region-history-v3992_3.mjs\n          node --check functions/api/ai/major-history.js\n",'workflow syntax')
t=replace_once(t,"          node tools/verify-aiplus-human-dialog-v3990_2.mjs\n", "          node tools/verify-aiplus-human-dialog-v3990_2.mjs\n          node tools/build-ai-major-history-index-v3990_1.mjs\n          git diff --exit-code -- ln-rank/data/ai-major-history-v3990_1\n          node tools/verify-ai-major-region-history-v3992_3.mjs\n",'workflow deterministic gate')
write(rel,t)

for rel in [
  'functions/_lib/ai/agent-task-kernel.js','functions/_lib/ai/command-interpreter.js','functions/_lib/ai/tool-registry.js',
  'functions/_lib/ai/turn-orchestrator.js','functions/_lib/ai/advisor-presentation.js','aiplus/app.v3990_1.js',
  'tools/browser-ai-workspace-v3990_1.mjs','.github/workflows/verify-ai-workspace-v3990_1.yml'
]:
    print(rel)
