from pathlib import Path

p = Path('tools/verify-aiplus-parent-semantics-v003.mjs')
s = p.read_text()
old = """const request=new Request('https://example.test/api/ai/turn',{method:'POST'}),ctx={request,env:{}};
const fullPairText='沈阳工业大学电气和大连交通大学自动化怎么选，考虑就业和考研';
const fullPair=deterministicCommand(fullPairText,base,['沈阳工业大学','大连交通大学']);
const turn=await orchestrateAiTurn(ctx,{input:fullPairText,workspace:base,confirmedCommand:fullPair});assert.equal(turn.ok,true);assert.equal(turn.pendingDeterministicTool,true);assert.equal(turn.commitView,false);assert.equal(turn.command.agentTask,'decision_research');assert.ok(turn.command.semanticFrame?.signature);assert.equal(turn.result?.decisionResearch?.plan?.scoreUsed,false,'remembered score must not silently execute in orchestrator');assert.ok(turn.toolRequests.length>=1&&turn.toolRequests.length<=4);assert.ok(turn.toolRequests.every(item=>item.kind==='school_official'),'no-score composite decision should request current official evidence, not admissions history');
const explicitPair=deterministicCommand(`568分，${fullPairText}`,base,['沈阳工业大学','大连交通大学']);const explicitTurn=await orchestrateAiTurn(ctx,{input:`568分，${fullPairText}`,workspace:base,confirmedCommand:explicitPair});assert.equal(explicitTurn.ok,true);assert.equal(explicitTurn.pendingDeterministicTool,true);assert.equal(explicitTurn.command.agentTask,'decision_research');assert.equal(explicitTurn.result?.decisionResearch?.plan?.scoreUsed,true);assert.equal(explicitTurn.toolRequests.length,2);assert.ok(explicitTurn.toolRequests.every(item=>item.kind==='school_history'),'explicit score pair must first request exact school-major admissions facts');
const followTurn=await orchestrateAiTurn(ctx,{input:'那如果我愿意读研呢',workspace:followWorkspace,confirmedCommand:follow});assert.equal(followTurn.ok,true);assert.equal(followTurn.command.agentTask,'decision_research');assert.equal(followTurn.commitView,false);assert.deepEqual(followTurn.command.semanticFrame.schools,pairFrame.schools);assert.equal(followTurn.command.semanticFrame.counterfactual.active,true);assert.equal(followTurn.result?.decisionResearch?.plan?.scoreUsed,false);
const refCommand=deterministicCommand('第二个就业呢',followWorkspace,[],[]);const refTurn=await orchestrateAiTurn(ctx,{input:'第二个就业呢',workspace:followWorkspace,confirmedCommand:refCommand});assert.equal(refTurn.ok,true);assert.equal(refTurn.command.agentTask,'decision_research');assert.equal(refTurn.command.semanticFrame.reference.index,1);assert.deepEqual(refTurn.command.semanticFrame.pairs.map(item=>item.school),['大连交通大学']);assert.ok(refTurn.toolRequests.every(item=>item.kind==='school_official'));assert.equal(refTurn.toolRequests.length,1,'reference follow-up must only research the selected school/pair');
"""
new = """const request=new Request('https://example.test/api/ai/turn',{method:'POST'});
const resolverSchools=[
  {officialName:'沈阳工业大学',province:'辽宁',city:'沈阳'},
  {officialName:'大连交通大学',province:'辽宁',city:'大连'},
  ...Array.from({length:58},(_,index)=>({officialName:`测试占位大学${index+1}`,province:'辽宁',city:'沈阳'}))
];
const emptyBackground={version:'local-strength-static-v3971_2',records:[],schools:[],meta:{dataYear:2026},academicBackgroundMeta:{boundary:'test empty background'}};
const testAssets={fetch:async input=>{const pathname=new URL(input.url).pathname;if(pathname==='/ln-rank/data/local-strength/local-strength-audit.v3971_2.json')return new Response(JSON.stringify({schools:resolverSchools}),{status:200,headers:{'content-type':'application/json'}});if(pathname==='/ln-rank/data/local-strength/local-strength-index.v3971_2.json')return new Response(JSON.stringify(emptyBackground),{status:200,headers:{'content-type':'application/json'}});return new Response('{}',{status:404,headers:{'content-type':'application/json'}});}};
const ctx={request,env:{ASSETS:testAssets}};
const fullPairText='沈阳工业大学电气和大连交通大学自动化怎么选，考虑就业和考研';
const turn=await orchestrateAiTurn(ctx,{input:fullPairText,workspace:base});assert.equal(turn.ok,true);assert.equal(turn.pendingDeterministicTool,true);assert.equal(turn.commitView,false);assert.equal(turn.command.agentTask,'decision_research');assert.deepEqual(turn.command.schoolNames,['沈阳工业大学','大连交通大学']);assert.deepEqual(turn.command.majorKeywords,['电气','自动化']);assert.ok(turn.command.semanticFrame?.signature);assert.equal(turn.result?.decisionResearch?.plan?.scoreUsed,false,'remembered score must not silently execute in orchestrator');assert.ok(turn.toolRequests.length>=1&&turn.toolRequests.length<=4);assert.ok(turn.toolRequests.every(item=>item.kind==='school_official'),'no-score composite decision should request current official evidence, not admissions history');
const completedOfficialResults={};for(const item of turn.toolRequests){completedOfficialResults[item.key]={kind:item.kind,key:item.key,url:item.url,status:200,payload:{ok:false,code:'test_no_official_text',school:new URL(item.url,'https://example.test').searchParams.get('school')||'',message:'test evidence unavailable'}};}
const continuationCtx={request,env:{}};
const continued=await orchestrateAiTurn(continuationCtx,{input:fullPairText,workspace:base,confirmedCommand:turn.command,deterministicToolResults:completedOfficialResults});assert.equal(continued.ok,true);assert.equal(continued.pendingDeterministicTool,false);assert.equal(continued.command.agentTask,'decision_research');assert.deepEqual(continued.command.schoolNames,['沈阳工业大学','大连交通大学'],'tool continuation must preserve bounded server-resolved school hints when resolver is unavailable');assert.deepEqual(continued.command.majorKeywords,['电气','自动化'],'tool continuation must preserve bounded server-resolved major hints');assert.equal(continued.commitView,false);assert.equal(continued.result?.decisionResearch?.plan?.scoreUsed,false);
const explicitTurn=await orchestrateAiTurn(ctx,{input:`568分，${fullPairText}`,workspace:base});assert.equal(explicitTurn.ok,true);assert.equal(explicitTurn.pendingDeterministicTool,true);assert.equal(explicitTurn.command.agentTask,'decision_research');assert.equal(explicitTurn.result?.decisionResearch?.plan?.scoreUsed,true);assert.equal(explicitTurn.toolRequests.length,2);assert.ok(explicitTurn.toolRequests.every(item=>item.kind==='school_history'),'explicit score pair must first request exact school-major admissions facts');
const followTurn=await orchestrateAiTurn(ctx,{input:'那如果我愿意读研呢',workspace:persistedFollowWorkspace});assert.equal(followTurn.ok,true);assert.equal(followTurn.command.agentTask,'decision_research');assert.equal(followTurn.commitView,false);assert.deepEqual(followTurn.command.semanticFrame.schools,pairFrame.schools);assert.equal(followTurn.command.semanticFrame.counterfactual.active,true);assert.equal(followTurn.result?.decisionResearch?.plan?.scoreUsed,false);
const refTurn=await orchestrateAiTurn(ctx,{input:'第二个就业呢',workspace:persistedFollowWorkspace});assert.equal(refTurn.ok,true);assert.equal(refTurn.command.agentTask,'decision_research');assert.equal(refTurn.command.semanticFrame.reference.index,1);assert.deepEqual(refTurn.command.semanticFrame.pairs.map(item=>item.school),['大连交通大学']);assert.ok(refTurn.toolRequests.every(item=>item.kind==='school_official'));assert.equal(refTurn.toolRequests.length,1,'reference follow-up must only research the selected school/pair');
"""
count=s.count(old)
if count!=1:
    raise SystemExit(f'protocol test block count={count}')
p.write_text(s.replace(old,new))
